-- =============================================================================
-- Louella audit — damage-sizing queries (READ-ONLY)
--
-- Every statement here is a SELECT. Nothing writes.
-- Companion to audit-findings.md; each query names the finding it sizes.
--
-- How to run: Supabase dashboard → SQL editor. The editor shows only the LAST
-- result set of a script, so select ONE query and run it on its own
-- (highlight → Run). For extra safety, prefix a query with
--   SET TRANSACTION READ ONLY;
-- or run the whole thing inside  BEGIN READ ONLY; … ROLLBACK;  from psql.
--
-- Assumes PRODUCTION_BRANCH_ID = 1 (query 12). Change the literal if not.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Q1 · F07 — Finished-goods chain breaks: opening ≠ previous day's leftover
-- Summary per branch and month. `units_off` is the absolute error that flowed
-- straight into "sold"; `revenue_off_approx` prices it at the CURRENT price.
-- -----------------------------------------------------------------------------
WITH chain AS (
  SELECT i.id, i."branchId", i."productId", i.date, i.quantity, i."isAutoGenerated",
         LAG(i.leftover) OVER w AS prev_leftover,
         LAG(i.date)     OVER w AS prev_date
  FROM "Inventory" i
  WHERE i."deletedAt" IS NULL
  WINDOW w AS (PARTITION BY i."branchId", i."productId" ORDER BY i.date)
)
SELECT b.name                               AS branch,
       to_char(c.date, 'YYYY-MM')           AS month,
       COUNT(*)                             AS broken_rows,
       COUNT(*) FILTER (WHERE NOT c."isAutoGenerated") AS broken_manual_rows,
       SUM(ABS(c.quantity - c.prev_leftover))          AS units_off,
       ROUND(SUM(ABS(c.quantity - c.prev_leftover) * p.price), 2) AS revenue_off_approx
FROM chain c
JOIN "Branch"  b ON b.id = c."branchId"
JOIN "Product" p ON p.id = c."productId"
WHERE c.prev_leftover IS NOT NULL
  AND c.quantity <> c.prev_leftover
GROUP BY 1, 2
ORDER BY 2 DESC, 1;

-- Q1b · detail (latest 200 breaks)
WITH chain AS (
  SELECT i.id, i."branchId", i."productId", i.date, i.quantity, i."isAutoGenerated",
         LAG(i.leftover) OVER w AS prev_leftover,
         LAG(i.date)     OVER w AS prev_date
  FROM "Inventory" i
  WHERE i."deletedAt" IS NULL
  WINDOW w AS (PARTITION BY i."branchId", i."productId" ORDER BY i.date)
)
SELECT c.id, b.name AS branch, p.name AS product, c.prev_date, c.prev_leftover,
       c.date, c.quantity AS opening, c.quantity - c.prev_leftover AS diff,
       c."isAutoGenerated"
FROM chain c
JOIN "Branch"  b ON b.id = c."branchId"
JOIN "Product" p ON p.id = c."productId"
WHERE c.prev_leftover IS NOT NULL AND c.quantity <> c.prev_leftover
ORDER BY c.date DESC
LIMIT 200;


-- -----------------------------------------------------------------------------
-- Q2 · F14 — Impossible rows: negative "sold" (leftover+reject > on hand)
-- -----------------------------------------------------------------------------
WITH adj AS (
  SELECT "inventoryId",
         SUM(CASE WHEN type = 'PULL_IN' THEN value ELSE -value END) AS adj_sum
  FROM "InventoryAdjustment"
  WHERE "deletedAt" IS NULL
  GROUP BY 1
)
SELECT i.id, b.name AS branch, p.name AS product, i.date,
       i.quantity, i.delivery, COALESCE(a.adj_sum, 0) AS adj_sum,
       i.leftover, i.reject,
       i.quantity + i.delivery + COALESCE(a.adj_sum, 0) - i.leftover - i.reject AS sold
FROM "Inventory" i
JOIN "Branch"  b ON b.id = i."branchId"
JOIN "Product" p ON p.id = i."productId"
LEFT JOIN adj a ON a."inventoryId" = i.id
WHERE i."deletedAt" IS NULL
  AND i.quantity + i.delivery + COALESCE(a.adj_sum, 0) - i.leftover - i.reject < 0
ORDER BY i.date DESC;


-- -----------------------------------------------------------------------------
-- Q3 · F01 — Placeholder rows carrying a delivery (reported as fully "sold")
-- A still-auto row with delivery > 0 and leftover = opening means nobody counted,
-- yet computeSold() books the whole delivery as sales.
-- -----------------------------------------------------------------------------
SELECT b.name AS branch, to_char(i.date, 'YYYY-MM') AS month,
       COUNT(*)                        AS rows,
       SUM(i.delivery)                 AS phantom_units_sold,
       ROUND(SUM(i.delivery * p.price), 2) AS phantom_revenue_approx
FROM "Inventory" i
JOIN "Branch"  b ON b.id = i."branchId"
JOIN "Product" p ON p.id = i."productId"
WHERE i."deletedAt" IS NULL
  AND i."isAutoGenerated"
  AND i.delivery > 0
GROUP BY 1, 2
ORDER BY 2 DESC, 1;


-- -----------------------------------------------------------------------------
-- Q4 · F05 — Revenue repriced retroactively
-- Products that HAVE price history but whose earliest history row starts after
-- their earliest inventory row: every row before it is priced at today's price.
-- -----------------------------------------------------------------------------
WITH first_price AS (
  SELECT "productId", MIN("effectiveAt") AS first_effective
  FROM "ProductPriceHistory" GROUP BY 1
)
SELECT p.id, p.name, p.price AS current_price, fp.first_effective,
       COUNT(i.id)  AS rows_priced_at_current,
       MIN(i.date)  AS from_date,
       MAX(i.date)  AS to_date
FROM "Product" p
JOIN first_price fp ON fp."productId" = p.id
JOIN "Inventory" i  ON i."productId" = p.id
                   AND i."deletedAt" IS NULL
                   AND i.date < fp.first_effective
GROUP BY p.id, p.name, p.price, fp.first_effective
ORDER BY rows_priced_at_current DESC;

-- Q4b · Products with NO price history at all (safe today; exposed on first price change)
SELECT p.id, p.name, p.price, p."createdAt"
FROM "Product" p
WHERE p."deletedAt" IS NULL
  AND NOT EXISTS (SELECT 1 FROM "ProductPriceHistory" h WHERE h."productId" = p.id)
ORDER BY p."createdAt" DESC;


-- -----------------------------------------------------------------------------
-- Q5 · F03 — Recipe lines whose unit has no conversion to the material's unit
-- (consumed at factor 1 — e.g. grams counted as kilograms)
-- -----------------------------------------------------------------------------
SELECT pr.name AS product, r.id AS recipe_id, r."deletedAt" AS recipe_deleted,
       m.name AS material, ri.quantity, ri.unit AS recipe_unit, m.unit AS material_unit
FROM "RecipeItem" ri
JOIN "Recipe"   r  ON r.id = ri."recipeId"
JOIN "Product"  pr ON pr.id = r."productId"
JOIN "Material" m  ON m.id = ri."materialId"
WHERE ri.unit <> m.unit
  AND NOT EXISTS (
    SELECT 1 FROM "UnitConversion" uc
    WHERE uc."fromUnit" = ri.unit AND uc."toUnit" = m.unit
  )
ORDER BY pr.name, m.name;


-- -----------------------------------------------------------------------------
-- Q6 · F04 — Production saved against a product whose recipe was deleted
-- (these saves still incremented MaterialInventory.used)
-- -----------------------------------------------------------------------------
SELECT pr.name AS product, r."deletedAt" AS recipe_deleted_at,
       COUNT(p.id)   AS production_rows_after_delete,
       SUM(p."yield") AS yield_after_delete,
       MIN(p.date)   AS first_date, MAX(p.date) AS last_date
FROM "Recipe" r
JOIN "Product"    pr ON pr.id = r."productId"
JOIN "Production" p  ON p."productId" = r."productId"
                    AND p."updatedAt" >= r."deletedAt"
                    AND p."yield" > 0
WHERE r."deletedAt" IS NOT NULL
GROUP BY pr.name, r."deletedAt"
ORDER BY yield_after_delete DESC;


-- -----------------------------------------------------------------------------
-- Q7 · F01/F03/F04/F09/F12 combined — Stored `used` vs what production implies
-- Expected = Σ yield / recipeYield × qty × factor using only LIVE recipes and
-- real conversions (same-unit = 1, missing conversion = NULL → flagged).
-- Any difference is the sum of every consumption bug plus manual overwrites.
-- Uses today's recipes (no history exists), so recipe edits also show here.
-- -----------------------------------------------------------------------------
WITH expected AS (
  SELECT ri."materialId", p.date,
         SUM( p."yield"::numeric / r."recipeYield"::numeric
              * ri.quantity::numeric
              * CASE WHEN ri.unit = m.unit THEN 1
                     ELSE uc.factor::numeric END ) AS expected_used,
         BOOL_OR(ri.unit <> m.unit AND uc.factor IS NULL) AS missing_conversion
  FROM "Production" p
  JOIN "Recipe"     r  ON r."productId" = p."productId" AND r."deletedAt" IS NULL
  JOIN "RecipeItem" ri ON ri."recipeId" = r.id
  JOIN "Material"   m  ON m.id = ri."materialId"
  LEFT JOIN "UnitConversion" uc ON uc."fromUnit" = ri.unit AND uc."toUnit" = m.unit
  WHERE p."yield" <> 0
  GROUP BY 1, 2
),
stored AS (
  SELECT "materialId", date, used::numeric AS stored_used
  FROM "MaterialInventory"
  WHERE "deletedAt" IS NULL
)
SELECT m.name AS material, m.unit,
       COALESCE(e.date, s.date)                   AS date,
       ROUND(COALESCE(s.stored_used, 0), 4)      AS stored_used,
       ROUND(COALESCE(e.expected_used, 0), 4)    AS expected_used,
       ROUND(COALESCE(s.stored_used, 0) - COALESCE(e.expected_used, 0), 4) AS diff,
       e.missing_conversion
FROM expected e
FULL JOIN stored s ON s."materialId" = e."materialId" AND s.date = e.date
JOIN "Material" m  ON m.id = COALESCE(e."materialId", s."materialId")
WHERE ABS(COALESCE(s.stored_used, 0) - COALESCE(e.expected_used, 0)) > 0.001
   OR e.missing_conversion
ORDER BY ABS(COALESCE(s.stored_used, 0) - COALESCE(e.expected_used, 0)) DESC
LIMIT 300;


-- -----------------------------------------------------------------------------
-- Q8 · F02 — Material opening ≠ previous card's closing
-- closing = max(0, quantity + delivery + Σadj − used), same as metrics.ts
-- -----------------------------------------------------------------------------
WITH adj AS (
  SELECT "materialInventoryId",
         SUM(CASE WHEN type = 'PULL_IN' THEN value ELSE -value END) AS adj_sum
  FROM "MaterialAdjustment"
  WHERE "deletedAt" IS NULL
  GROUP BY 1
),
cards AS (
  SELECT mi.id, mi."materialId", mi.date, mi.quantity,
         GREATEST(0, mi.quantity + mi.delivery + COALESCE(a.adj_sum, 0) - mi.used) AS closing
  FROM "MaterialInventory" mi
  LEFT JOIN adj a ON a."materialInventoryId" = mi.id
  WHERE mi."deletedAt" IS NULL
),
chain AS (
  SELECT c.*, LAG(c.closing) OVER w AS prev_closing, LAG(c.date) OVER w AS prev_date
  FROM cards c
  WINDOW w AS (PARTITION BY c."materialId" ORDER BY c.date)
)
SELECT m.name AS material, m.unit, ch.prev_date, ROUND(ch.prev_closing::numeric, 4) AS prev_closing,
       ch.date, ROUND(ch.quantity::numeric, 4) AS opening,
       ROUND((ch.quantity - ch.prev_closing)::numeric, 4) AS diff
FROM chain ch
JOIN "Material" m ON m.id = ch."materialId"
WHERE ch.prev_closing IS NOT NULL
  AND ABS(ch.quantity - ch.prev_closing) > 0.001
ORDER BY ch.date DESC, m.name
LIMIT 300;


-- -----------------------------------------------------------------------------
-- Q9 · F14 — Material cards that went negative (hidden by the clamp to 0)
-- -----------------------------------------------------------------------------
WITH adj AS (
  SELECT "materialInventoryId",
         SUM(CASE WHEN type = 'PULL_IN' THEN value ELSE -value END) AS adj_sum
  FROM "MaterialAdjustment" WHERE "deletedAt" IS NULL GROUP BY 1
)
SELECT m.name AS material, m.unit, mi.date,
       ROUND((mi.quantity + mi.delivery + COALESCE(a.adj_sum, 0) - mi.used)::numeric, 4) AS unclamped_closing
FROM "MaterialInventory" mi
JOIN "Material" m ON m.id = mi."materialId"
LEFT JOIN adj a ON a."materialInventoryId" = mi.id
WHERE mi."deletedAt" IS NULL
  AND mi.quantity + mi.delivery + COALESCE(a.adj_sum, 0) - mi.used < -0.001
ORDER BY unclamped_closing ASC
LIMIT 200;


-- -----------------------------------------------------------------------------
-- Q10 · F10/F11 — Likely double-submits (same row, type, value, user within 10 s)
-- -----------------------------------------------------------------------------
SELECT 'inventory' AS kind, a1.id AS first_id, a2.id AS second_id, a1."inventoryId" AS row_id,
       a1.type, a1.value, a1."createdById", a1."createdAt", a2."createdAt" AS second_at
FROM "InventoryAdjustment" a1
JOIN "InventoryAdjustment" a2
  ON a2."inventoryId" = a1."inventoryId" AND a2.type = a1.type AND a2.value = a1.value
 AND a2.id > a1.id
 AND a2."createdById" IS NOT DISTINCT FROM a1."createdById"
 AND a2."createdAt" BETWEEN a1."createdAt" AND a1."createdAt" + interval '10 seconds'
WHERE a1."deletedAt" IS NULL AND a2."deletedAt" IS NULL
UNION ALL
SELECT 'material', a1.id, a2.id, a1."materialInventoryId",
       a1.type, a1.value, a1."createdById", a1."createdAt", a2."createdAt"
FROM "MaterialAdjustment" a1
JOIN "MaterialAdjustment" a2
  ON a2."materialInventoryId" = a1."materialInventoryId" AND a2.type = a1.type AND a2.value = a1.value
 AND a2.id > a1.id
 AND a2."createdById" IS NOT DISTINCT FROM a1."createdById"
 AND a2."createdAt" BETWEEN a1."createdAt" AND a1."createdAt" + interval '10 seconds'
WHERE a1."deletedAt" IS NULL AND a2."deletedAt" IS NULL
ORDER BY 8 DESC;


-- -----------------------------------------------------------------------------
-- Q11 · Transfer legs out of sync (one leg deleted, or values differ)
-- -----------------------------------------------------------------------------
SELECT o.id AS out_id, i.id AS in_id, o.value AS out_value, i.value AS in_value,
       o."deletedAt" AS out_deleted, i."deletedAt" AS in_deleted, o."createdAt"
FROM "InventoryAdjustment" o
JOIN "InventoryAdjustment" i ON i.id = o."linkedAdjustmentId"
WHERE o.type = 'PULL_OUT'
  AND ( o.value <> i.value
     OR (o."deletedAt" IS NULL) <> (i."deletedAt" IS NULL) )
ORDER BY o."createdAt" DESC;


-- -----------------------------------------------------------------------------
-- Q12 · F01 — Kitchen yield vs finalized orders (overwrite instead of sum)
-- Days where more than one finalized order covered the same product, and the
-- recorded Production yield (branch 1) is not their total.
-- -----------------------------------------------------------------------------
WITH po AS (
  SELECT o.date, it."productId",
         COUNT(DISTINCT o.id) AS orders, SUM(it."yield") AS ordered_total
  FROM "ProductionOrder" o
  JOIN "ProductionOrderItem" it ON it."productionOrderId" = o.id
  WHERE o.status = 'FINALIZED' AND o."deletedAt" IS NULL AND it."yield" > 0
  GROUP BY 1, 2
)
SELECT po.date, pr.name AS product, po.orders, po.ordered_total,
       p."yield" AS recorded_kitchen_yield,
       po.ordered_total - COALESCE(p."yield", 0) AS shortfall
FROM po
JOIN "Product" pr ON pr.id = po."productId"
LEFT JOIN "Production" p
       ON p."productId" = po."productId" AND p.date = po.date AND p."branchId" = 1  -- PRODUCTION_BRANCH_ID
WHERE po.orders > 1
  AND COALESCE(p."yield", 0) <> po.ordered_total
ORDER BY po.date DESC;


-- -----------------------------------------------------------------------------
-- Q13 · F15 — Future-dated rows that suppress today's autofill
-- -----------------------------------------------------------------------------
SELECT 'Inventory' AS tbl, date, COUNT(*) AS rows
FROM "Inventory"
WHERE date > (now() AT TIME ZONE 'Asia/Manila')::date
GROUP BY date
UNION ALL
SELECT 'MaterialInventory', date, COUNT(*)
FROM "MaterialInventory"
WHERE "deletedAt" IS NULL AND date > (now() AT TIME ZONE 'Asia/Manila')::date
GROUP BY date
ORDER BY 1, 2;


-- -----------------------------------------------------------------------------
-- Q14 · F08 — Material deliveries possibly posted to the wrong day
-- Cards whose delivery was last edited between 00:00 and 08:00 Manila on the
-- day AFTER the card's date — the window when the page defaulted to yesterday.
-- (updatedAt is stored in UTC; heuristic — later edits overwrite updatedAt.)
-- -----------------------------------------------------------------------------
SELECT m.name AS material, mi.date AS card_date, mi.delivery,
       (mi."updatedAt" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Manila') AS edited_manila
FROM "MaterialInventory" mi
JOIN "Material" m ON m.id = mi."materialId"
WHERE mi."deletedAt" IS NULL
  AND mi.delivery > 0
  AND (mi."updatedAt" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Manila')::date = mi.date + 1
  AND EXTRACT(HOUR FROM (mi."updatedAt" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Manila')) < 8
ORDER BY mi.date DESC;
