'use client';

import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import dayjs from 'dayjs';
import { Loader2 } from 'lucide-react';
import type { AuditEvent } from '@/types';
import { Badge } from '@/components/ui/badge';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

/** Field names as the sheet calls them. */
const FIELD_LABELS: Record<string, string> = {
  quantity: 'Opening',
  delivery: 'Delivery',
  leftover: 'Leftover',
  reject: 'Reject',
  notes: 'Notes',
  isAutoGenerated: 'Placeholder',
  used: 'Used',
  yield: 'Yield',
};

const ACTION_LABELS: Record<string, string> = {
  create: 'Entered',
  update: 'Changed',
  delete: 'Deleted',
  restore: 'Restored',
  'carry-forward': 'Carried forward',
};

const show = (v: unknown) => (v === null || v === undefined || v === '' ? '—' : String(v));

/**
 * How a row reached its current values: every recorded change, who made it,
 * and from what. Loaded only when opened.
 */
export default function ChangeHistory({
  queryKey,
  load,
}: {
  queryKey: readonly unknown[];
  load: () => Promise<AuditEvent[]>;
}) {
  const [open, setOpen] = useState(false);
  const { data: events = [], isLoading, isError } = useQuery({
    queryKey: [...queryKey, 'history'],
    queryFn: load,
    enabled: open,
  });

  return (
    <Accordion type="single" collapsible onValueChange={(v) => setOpen(v === 'history')}>
      <AccordionItem value="history">
        <AccordionTrigger className="text-sm">Change history</AccordionTrigger>
        <AccordionContent>
          {isLoading ? (
            <Loader2 className="animate-spin" aria-label="Loading history" />
          ) : isError ? (
            <p className="text-sm text-destructive">Could not load the history.</p>
          ) : events.length === 0 ? (
            <p className="text-sm text-muted-foreground">No changes recorded yet.</p>
          ) : (
            <ol className="flex flex-col gap-2">
              {events.map((e) => (
                <li key={e.id} className="flex flex-col gap-1 text-sm">
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge variant={e.action === 'carry-forward' ? 'secondary' : 'outline'}>
                      {ACTION_LABELS[e.action] ?? e.action}
                    </Badge>
                    <span className="text-muted-foreground">
                      {dayjs(e.at).format('MMM D, h:mm A')} · {e.user?.email ?? 'system'}
                    </span>
                  </div>
                  <ul className="flex flex-col pl-2 text-muted-foreground">
                    {Object.entries(e.changes).map(([field, [from, to]]) => (
                      <li key={field}>
                        {FIELD_LABELS[field] ?? field}: {show(from)} → <span className="text-foreground">{show(to)}</span>
                      </li>
                    ))}
                  </ul>
                </li>
              ))}
            </ol>
          )}
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  );
}
