-- A day's leftover is a count only once someone has entered it. Until now the
-- chain inferred that from isAutoGenerated, which any edit (a delivery, a
-- reject, the sheet's Initialize button) switched off — booking uncounted stock
-- as sold. The count is now explicit.
ALTER TABLE "Inventory" ADD COLUMN "leftoverCountedAt" TIMESTAMP(3);

-- Every row the chain treated as counted stays counted, so history and
-- revenue are unchanged by this migration.
UPDATE "Inventory"
SET "leftoverCountedAt" = "updatedAt"
WHERE "isAutoGenerated" = false;

-- Product prices are dated to the Manila day. Every writer already stores
-- UTC midnight; the column now enforces it. Any older timestamp is resolved
-- to its Manila calendar day.
ALTER TABLE "ProductPriceHistory"
  ALTER COLUMN "effectiveAt" TYPE DATE
  USING ((("effectiveAt" AT TIME ZONE 'UTC') AT TIME ZONE 'Asia/Manila')::date);
