import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { computeSold } from '../common/utils/inventory-metrics.util';

export type SuggestionPeriod = 'prev-day' | '7d' | '30d';

const PERIOD_DAYS: Record<SuggestionPeriod, number> = {
  'prev-day': 1,
  '7d': 7,
  '30d': 30,
};

const MS_PER_DAY = 86_400_000;

/**
 * Computes suggested production quantities per product for a branch, from
 * real historical sales (spec §9: never hardcoded estimates). The averaging
 * window is relative to and EXCLUDES the reference date. Untouched CRON
 * placeholder rows (isAutoGenerated) are excluded — they are "no data
 * recorded" days and would drag every average toward zero.
 */
@Injectable()
export class SuggestionsService {
  constructor(private readonly prisma: PrismaService) {}

  async getSuggestions(
    branchId: number,
    period: SuggestionPeriod = '7d',
    date?: string,
  ) {
    const refStr =
      date ??
      new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Manila' }).format(
        new Date(),
      );
    const ref = new Date(`${refStr}T00:00:00.000Z`);
    const days = PERIOD_DAYS[period];
    const end = new Date(ref.getTime() - MS_PER_DAY);
    const start = new Date(ref.getTime() - days * MS_PER_DAY);

    const rows = await this.prisma.inventory.findMany({
      where: {
        branchId,
        deletedAt: null,
        isAutoGenerated: false,
        date: { gte: start, lte: end },
      },
      select: {
        productId: true,
        quantity: true,
        delivery: true,
        leftover: true,
        reject: true,
        adjustments: {
          where: { deletedAt: null },
          select: { type: true, value: true },
        },
      },
    });

    const byProduct = new Map<
      number,
      { totalSold: number; daysWithData: number }
    >();
    for (const row of rows) {
      const agg = byProduct.get(row.productId) ?? {
        totalSold: 0,
        daysWithData: 0,
      };
      agg.totalSold += computeSold(row);
      agg.daysWithData += 1;
      byProduct.set(row.productId, agg);
    }

    const suggestions = Array.from(byProduct.entries()).map(
      ([productId, agg]) => {
        const avgSold = agg.totalSold / agg.daysWithData;
        return {
          productId,
          avgSold,
          suggestedQty: Math.max(0, Math.ceil(avgSold)),
          daysWithData: agg.daysWithData,
        };
      },
    );

    return {
      branchId,
      period,
      window: {
        startDate: start.toISOString().slice(0, 10),
        endDate: end.toISOString().slice(0, 10),
      },
      suggestions,
    };
  }
}
