import { Test, TestingModule } from '@nestjs/testing';
import { SuggestionsService } from './suggestions.service';
import { PrismaService } from '../prisma/prisma.service';

function makePrisma() {
  return {
    inventory: { findMany: jest.fn().mockResolvedValue([]) },
  };
}

function makeRow(
  productId: number,
  sold: {
    quantity: number;
    delivery?: number;
    leftover?: number;
    reject?: number;
  },
  adjustments: { type: string; value: number }[] = [],
) {
  return {
    productId,
    quantity: sold.quantity,
    delivery: sold.delivery ?? 0,
    leftover: sold.leftover ?? 0,
    reject: sold.reject ?? 0,
    adjustments,
  };
}

describe('SuggestionsService', () => {
  let service: SuggestionsService;
  let prisma: ReturnType<typeof makePrisma>;

  beforeEach(async () => {
    prisma = makePrisma();
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        SuggestionsService,
        { provide: PrismaService, useValue: prisma },
      ],
    }).compile();
    service = module.get(SuggestionsService);
  });

  it('queries only real (non-placeholder, non-deleted) rows for the branch', async () => {
    await service.getSuggestions(2, '7d', '2026-06-13');

    expect(prisma.inventory.findMany).toHaveBeenCalledWith(
      expect.objectContaining({
        where: expect.objectContaining({
          branchId: 2,
          deletedAt: null,
          isAutoGenerated: false,
        }),
      }),
    );
  });

  it('uses a 7-day window ending the day before the reference date', async () => {
    const result = await service.getSuggestions(2, '7d', '2026-06-13');

    expect(result.window).toEqual({
      startDate: '2026-06-06',
      endDate: '2026-06-12',
    });
    const where = prisma.inventory.findMany.mock.calls[0][0].where;
    expect(where.date).toEqual({
      gte: new Date('2026-06-06T00:00:00.000Z'),
      lte: new Date('2026-06-12T00:00:00.000Z'),
    });
  });

  it('uses a single-day window for prev-day', async () => {
    const result = await service.getSuggestions(2, 'prev-day', '2026-06-13');

    expect(result.window).toEqual({
      startDate: '2026-06-12',
      endDate: '2026-06-12',
    });
  });

  it('uses a 30-day window for 30d', async () => {
    const result = await service.getSuggestions(2, '30d', '2026-06-13');

    expect(result.window).toEqual({
      startDate: '2026-05-14',
      endDate: '2026-06-12',
    });
  });

  it('averages sold across days and rounds suggestions up', async () => {
    // sold = quantity + delivery + adjSum - leftover - reject
    prisma.inventory.findMany.mockResolvedValue([
      makeRow(5, { quantity: 20, leftover: 0 }), // sold 20
      makeRow(5, { quantity: 30, leftover: 3 }), // sold 27
    ]);

    const result = await service.getSuggestions(2, '7d', '2026-06-13');

    expect(result.suggestions).toEqual([
      { productId: 5, avgSold: 23.5, suggestedQty: 24, daysWithData: 2 },
    ]);
  });

  it('excludes rejects so spoilage does not inflate suggestions', async () => {
    prisma.inventory.findMany.mockResolvedValue([
      makeRow(5, { quantity: 20, leftover: 0, reject: 5 }), // sold 15
    ]);

    const result = await service.getSuggestions(2, '7d', '2026-06-13');

    expect(result.suggestions).toEqual([
      { productId: 5, avgSold: 15, suggestedQty: 15, daysWithData: 1 },
    ]);
  });

  it('folds adjustments into sold and clamps negative averages to 0', async () => {
    // sold = 5 + 0 + (-10) - 0 = -5
    prisma.inventory.findMany.mockResolvedValue([
      makeRow(7, { quantity: 5 }, [{ type: 'PULL_OUT', value: 10 }]),
    ]);

    const result = await service.getSuggestions(2, '7d', '2026-06-13');

    expect(result.suggestions).toEqual([
      { productId: 7, avgSold: -5, suggestedQty: 0, daysWithData: 1 },
    ]);
  });

  it('groups products independently', async () => {
    prisma.inventory.findMany.mockResolvedValue([
      makeRow(1, { quantity: 10 }), // sold 10
      makeRow(2, { quantity: 4 }), // sold 4
      makeRow(1, { quantity: 20 }), // sold 20
    ]);

    const result = await service.getSuggestions(2, '7d', '2026-06-13');

    expect(result.suggestions).toEqual(
      expect.arrayContaining([
        { productId: 1, avgSold: 15, suggestedQty: 15, daysWithData: 2 },
        { productId: 2, avgSold: 4, suggestedQty: 4, daysWithData: 1 },
      ]),
    );
  });

  it('returns an empty list when the branch has no history', async () => {
    const result = await service.getSuggestions(2, '7d', '2026-06-13');
    expect(result.suggestions).toEqual([]);
  });
});
