import { PrismaClient, UserRole } from '@prisma/client';
import bcrypt from 'bcrypt';
import { BCRYPT_COST_FACTOR } from '@/server/common/constants/security.constants';
import { manilaToday } from '@/lib/manilaDate';
import { ADMIN, KITCHEN_BRANCH_ID, MANAGER, VIEWER } from '../support/credentials';

/** Only what the API cannot create or every test needs. Everything else is per-test (fixtures/world.ts). */
export async function seedBase(prisma: PrismaClient): Promise<void> {
  await prisma.branch.create({ data: { id: KITCHEN_BRANCH_ID, name: 'E2E Kitchen', isActive: true } });
  // Explicit id above does not advance the sequence.
  await prisma.$executeRawUnsafe(
    `SELECT setval(pg_get_serial_sequence('"Branch"', 'id'), (SELECT MAX(id) FROM "Branch"))`,
  );

  // User.branchId is @unique: the manager holds the kitchen; admin and viewer have no branch.
  const users: Array<[typeof ADMIN, UserRole, number | null]> = [
    [ADMIN, UserRole.ADMIN, null],
    [MANAGER, UserRole.MANAGER, KITCHEN_BRANCH_ID],
    [VIEWER, UserRole.VIEWER, null],
  ];
  for (const [u, role, branchId] of users) {
    await prisma.user.create({
      data: {
        email: u.email,
        passwordHash: await bcrypt.hash(u.password, BCRYPT_COST_FACTOR),
        role,
        branchId,
        isActive: true,
      },
    });
  }

  await prisma.jobRole.create({ data: { name: 'E2E Baker' } });
  await prisma.expenseCategory.create({ data: { name: 'E2E Supplies' } });

  // One inventory row for today, so on-demand autofill sees the day as already current.
  //
  // AutofillOnDemandService keys off the newest inventory row anywhere. With none dated today, the first
  // read of any sheet during a run tops up EVERY branch with an uncounted placeholder for EVERY product —
  // 39 of them by mid-run — and a test that has just counted its own single row suddenly has a day it
  // cannot verify ("39 products have no leftover count yet"). Whether that hit depended on which test
  // read a sheet first, so it showed up as an intermittent branch-cash failure.
  const today = manilaToday();
  const product = await prisma.product.create({
    data: {
      name: 'E2E Base Bread',
      type: 'BREAD',
      price: 10,
      priceHistory: { create: { price: 10, effectiveAt: new Date(`${today}T00:00:00.000Z`) } },
    },
  });
  await prisma.inventory.create({
    data: {
      branchId: KITCHEN_BRANCH_ID,
      productId: product.id,
      date: new Date(`${today}T00:00:00.000Z`),
      quantity: 0,
      isAutoGenerated: true,
    },
  });
}
