import { InventoryService } from './inventory.service';

/**
 * addDeliveryInTx: how a finalized production order lands on a branch sheet.
 */
describe('InventoryService.addDeliveryInTx', () => {
  const DATE = new Date('2026-09-19T00:00:00.000Z');
  const KEY = { branchId: 2, productId: 7, date: DATE };

  let tx: {
    inventory: {
      findUnique: jest.Mock;
      findFirst: jest.Mock;
      findMany: jest.Mock;
      create: jest.Mock;
      update: jest.Mock;
    };
  };
  let service: InventoryService;

  beforeEach(() => {
    tx = {
      inventory: {
        findUnique: jest.fn(),
        findFirst: jest.fn(),
        findMany: jest.fn().mockResolvedValue([]),
        create: jest.fn(),
        update: jest.fn(),
      },
    };
    service = new InventoryService({} as never, {} as never);
  });

  const placeholder = (id: number, delivery = 0) => ({
    id,
    isAutoGenerated: true,
    delivery,
    adjustments: [],
  });

  it('adds to the delivery on a counted row and leaves its leftover as counted', async () => {
    tx.inventory.findUnique.mockResolvedValue({ id: 1, isAutoGenerated: false, deletedAt: null });

    await service.addDeliveryInTx(tx as never, KEY, 40);

    expect(tx.inventory.update).toHaveBeenCalledTimes(1);
    expect(tx.inventory.update).toHaveBeenCalledWith({
      where: { id: 1 },
      data: { delivery: { increment: 40 }, deletedAt: null },
    });
    expect(tx.inventory.findMany).not.toHaveBeenCalled();
  });

  // Raising only delivery on a placeholder made computeSold() report the whole
  // delivery as sold before anyone had counted anything.
  it('raises delivery and the closing balance together on a placeholder', async () => {
    tx.inventory.findUnique.mockResolvedValue({ id: 1, isAutoGenerated: true, deletedAt: null });
    tx.inventory.update.mockResolvedValueOnce({ leftover: 55 });

    await service.addDeliveryInTx(tx as never, KEY, 40);

    expect(tx.inventory.update.mock.calls[0][0]).toEqual({
      where: { id: 1 },
      data: {
        delivery: { increment: 40 },
        leftover: { increment: 40 },
        deletedAt: null,
      },
      select: { leftover: true },
    });
  });

  it('carries the new close forward through later placeholders, stopping at a counted day', async () => {
    tx.inventory.findUnique.mockResolvedValue({ id: 1, isAutoGenerated: true, deletedAt: null });
    tx.inventory.update.mockResolvedValueOnce({ leftover: 55 });
    tx.inventory.findMany.mockResolvedValue([
      placeholder(2),
      placeholder(3, 10), // a delivery already booked on this later day
      { id: 4, isAutoGenerated: false, delivery: 0, adjustments: [] },
      placeholder(5),
    ]);

    await service.addDeliveryInTx(tx as never, KEY, 40);

    const writes = tx.inventory.update.mock.calls.slice(1).map(([a]) => a);
    expect(writes).toEqual([
      { where: { id: 2 }, data: { quantity: 55, leftover: 55 } },
      { where: { id: 3 }, data: { quantity: 55, leftover: 65 } },
    ]);
  });

  // It used to be created with quantity 0, dropping the stock carried over.
  it('creates a missing row as a placeholder carrying forward the prior leftover', async () => {
    tx.inventory.findUnique.mockResolvedValue(null);
    tx.inventory.findFirst.mockResolvedValue({ leftover: 12 });

    await service.addDeliveryInTx(tx as never, KEY, 40);

    expect(tx.inventory.findFirst).toHaveBeenCalledWith(
      expect.objectContaining({
        where: { branchId: 2, productId: 7, date: { lt: DATE }, deletedAt: null },
      }),
    );
    expect(tx.inventory.create.mock.calls[0][0].data).toEqual(
      expect.objectContaining({
        branchId: 2,
        productId: 7,
        date: DATE,
        quantity: 12,
        delivery: 40,
        leftover: 52,
        isAutoGenerated: true,
      }),
    );
  });

  it('does nothing for a zero quantity', async () => {
    await service.addDeliveryInTx(tx as never, KEY, 0);

    expect(tx.inventory.findUnique).not.toHaveBeenCalled();
  });
});
