import { BadRequestException, NotFoundException } from '@nestjs/common';
import { InventoryService } from './inventory.service';
import { FakeStockDb, day } from '../common/testing/fake-stock-db';

/**
 * Carry-forward, tested on outcomes: after each write, every day must open on
 * the previous day's close (decision 2026-09-19), however the write arrived.
 */
describe('InventoryService — opening stock follows the previous close', () => {
  let db: FakeStockDb;
  let service: InventoryService;

  beforeEach(() => {
    db = new FakeStockDb();
    service = new InventoryService(db as never, {} as never);
  });

  const B = 1;
  const P = 7;
  const row = (date: string, r: Record<string, unknown>) =>
    db.seed('inventory', { branchId: B, productId: P, date: day(date), ...r });
  const chain = () =>
    db.live('inventory', { branchId: B, productId: P }).map((r) => ({
      date: r.date.toISOString().slice(0, 10),
      opening: r.quantity,
      leftover: r.leftover,
    }));

  /** Mon counted 20; Tue counted (hand-entered) opening 20; Wed–Thu placeholders. */
  function seedWeek() {
    const mon = row('2026-09-14', { quantity: 10, delivery: 50, leftover: 20 });
    const tue = row('2026-09-15', { quantity: 20, delivery: 40, leftover: 15 });
    const wed = row('2026-09-16', { quantity: 15, delivery: 0, leftover: 15, isAutoGenerated: true });
    const thu = row('2026-09-17', { quantity: 15, delivery: 0, leftover: 15, isAutoGenerated: true });
    return { mon, tue, wed, thu };
  }

  describe('editing a count', () => {
    // The old cascade stopped at the first hand-entered day, so Tuesday kept
    // opening on 20 and its "sold" was overstated by 5.
    it('re-opens a hand-entered next day on the corrected leftover', async () => {
      const { mon } = seedWeek();

      await service.update(mon.id, { leftover: 15 });

      expect(chain()).toEqual([
        { date: '2026-09-14', opening: 10, leftover: 15 },
        { date: '2026-09-15', opening: 15, leftover: 15 }, // counted leftover kept
        { date: '2026-09-16', opening: 15, leftover: 15 },
        { date: '2026-09-17', opening: 15, leftover: 15 },
      ]);
    });

    it('carries a new close through placeholder days', async () => {
      const { tue } = seedWeek();

      const result = await service.update(tue.id, { leftover: 12 });

      expect(chain().slice(1)).toEqual([
        { date: '2026-09-15', opening: 20, leftover: 12 },
        { date: '2026-09-16', opening: 12, leftover: 12 },
        { date: '2026-09-17', opening: 12, leftover: 12 },
      ]);
      expect(result.cascadeUpdated).toBe(2);
    });

    it('includes a placeholder day’s delivery and transfers in its carried close', async () => {
      const { tue, wed } = seedWeek();
      db.tables.inventory.find((r) => r.id === wed.id)!.delivery = 30;
      db.seed('inventoryAdjustment', { inventoryId: wed.id, type: 'PULL_OUT', value: 4 });

      await service.update(tue.id, { leftover: 10 });

      expect(chain().slice(2)).toEqual([
        { date: '2026-09-16', opening: 10, leftover: 36 }, // 10 + 30 − 4
        { date: '2026-09-17', opening: 36, leftover: 36 },
      ]);
    });

    it('overrides a typed opening wherever a previous day exists', async () => {
      const { tue } = seedWeek();

      await service.update(tue.id, { quantity: 99 });

      expect(chain()[1].opening).toBe(20);
    });

    it('records who edited the row', async () => {
      const { tue } = seedWeek();

      await service.update(tue.id, { leftover: 12 }, undefined, 42);

      expect(db.tables.inventory.find((r) => r.id === tue.id)!.updatedById).toBe(42);
    });

    it('marks an edited placeholder as counted', async () => {
      const { wed } = seedWeek();

      await service.update(wed.id, { leftover: 5 });

      expect(db.tables.inventory.find((r) => r.id === wed.id)!.isAutoGenerated).toBe(false);
    });

    it('refuses a row outside the caller’s branch', async () => {
      const { tue } = seedWeek();

      await expect(service.update(tue.id, { leftover: 1 }, 99)).rejects.toThrow(
        NotFoundException,
      );
    });
  });

  describe('impossible counts', () => {
    it('refuses leftover + reject above what was on hand, and writes nothing', async () => {
      const { tue } = seedWeek();

      // Tue has 20 opening + 40 delivered = 60.
      await expect(
        service.update(tue.id, { leftover: 50, reject: 11 }),
      ).rejects.toThrow(BadRequestException);
      expect(chain()[1]).toEqual({ date: '2026-09-15', opening: 20, leftover: 15 });
    });

    it('counts transfers in the stock on hand', async () => {
      const { tue } = seedWeek();
      db.seed('inventoryAdjustment', { inventoryId: tue.id, type: 'PULL_IN', value: 10 });

      await expect(service.update(tue.id, { leftover: 70 })).resolves.toBeDefined();
    });

    // POST used to skip this check entirely.
    it('applies to a new entry, judged on the opening it will actually have', async () => {
      seedWeek();

      await expect(
        service.create({
          branchId: B,
          productId: P,
          date: '2026-09-18',
          quantity: 500, // ignored: Thursday closed on 15
          delivery: 10,
          leftover: 30,
          reject: 0,
        }),
      ).rejects.toThrow(/only 25 units existed/);
      expect(chain()).toHaveLength(4);
    });

    it('rolls back the whole bulk save when one row is impossible', async () => {
      const { mon, tue } = seedWeek();

      await expect(
        service.updateBulk([
          { id: mon.id, leftover: 18 },
          { id: tue.id, leftover: 500 },
        ]),
      ).rejects.toThrow(BadRequestException);
      expect(chain()[0].leftover).toBe(20);
      expect(chain()[1].opening).toBe(20);
    });
  });

  describe('bulk save', () => {
    it('applies chained edits in one go', async () => {
      const { mon, tue } = seedWeek();

      const result = await service.updateBulk([
        { id: mon.id, leftover: 18 },
        { id: tue.id, leftover: 11 },
      ]);

      expect(chain().map((r) => [r.opening, r.leftover])).toEqual([
        [10, 18],
        [18, 11],
        [11, 11],
        [11, 11],
      ]);
      expect(result.updated).toBe(2);
      expect(result.cascadeWarnings).toEqual([]);
    });

    it('refuses the whole batch when a row is missing or outside the branch', async () => {
      const { mon } = seedWeek();

      await expect(
        service.updateBulk([{ id: mon.id, leftover: 1 }, { id: 9999, leftover: 1 }]),
      ).rejects.toThrow(/9999/);
      expect(chain()[0].leftover).toBe(20);
    });
  });

  describe('entering a day', () => {
    it('makes later days follow a back-dated entry', async () => {
      seedWeek();
      // A Sunday nobody entered, before Monday.
      await service.create({
        branchId: B,
        productId: P,
        date: '2026-09-13',
        quantity: 0,
        delivery: 30,
        leftover: 8,
        reject: 0,
      });

      expect(chain()[1]).toEqual({ date: '2026-09-14', opening: 8, leftover: 20 });
    });

    it('keeps the typed opening on a product’s first ever day', async () => {
      await service.create({
        branchId: B,
        productId: P,
        date: '2026-09-14',
        quantity: 12,
        delivery: 5,
        leftover: 3,
        reject: 0,
      });

      expect(chain()).toEqual([{ date: '2026-09-14', opening: 12, leftover: 3 }]);
    });

    it('restores a soft-deleted day when it is entered again', async () => {
      const { tue } = seedWeek();
      db.tables.inventory.find((r) => r.id === tue.id)!.deletedAt = new Date();

      await service.create({
        branchId: B,
        productId: P,
        date: '2026-09-15',
        quantity: 0,
        delivery: 40,
        leftover: 14,
        reject: 0,
      });

      const restored = db.tables.inventory.find((r) => r.id === tue.id)!;
      expect(restored.deletedAt).toBeNull();
      expect(restored.leftover).toBe(14);
    });
  });

  describe('deleting a day', () => {
    it('re-opens the next day on the day before the deleted one', async () => {
      const { tue } = seedWeek();

      await service.remove(tue.id);

      expect(chain()).toEqual([
        { date: '2026-09-14', opening: 10, leftover: 20 },
        { date: '2026-09-16', opening: 20, leftover: 20 },
        { date: '2026-09-17', opening: 20, leftover: 20 },
      ]);
    });
  });

  describe('recascade (repair)', () => {
    it('walks the whole chain, past days that already look consistent', async () => {
      row('2026-09-14', { quantity: 10, leftover: 20 });
      row('2026-09-15', { quantity: 20, leftover: 15 }); // consistent
      row('2026-09-16', { quantity: 99, leftover: 9 }); // broken by old code

      const result = await service.recascadeLeftovers(B, P, '2026-09-14');

      expect(result.updated).toBe(1);
      expect(chain()[2].opening).toBe(15);
    });

    it('404s when the start day does not exist', async () => {
      await expect(
        service.recascadeLeftovers(B, P, '2026-09-14'),
      ).rejects.toThrow(NotFoundException);
    });
  });

  describe('a finalized production order’s delivery (addDeliveryInTx)', () => {
    it('adds to a counted day and keeps its leftover as counted', async () => {
      const { tue } = seedWeek();

      await service.addDeliveryInTx(db as never, { branchId: B, productId: P, date: day('2026-09-15') }, 25);

      const t = db.tables.inventory.find((r) => r.id === tue.id)!;
      expect(t.delivery).toBe(65);
      expect(t.leftover).toBe(15);
    });

    // Raising only delivery on a placeholder made computeSold() report the
    // whole delivery as sold before anyone had counted anything.
    it('raises a placeholder’s close with it and carries it on', async () => {
      seedWeek();

      await service.addDeliveryInTx(db as never, { branchId: B, productId: P, date: day('2026-09-16') }, 25);

      expect(chain().slice(2)).toEqual([
        { date: '2026-09-16', opening: 15, leftover: 40 },
        { date: '2026-09-17', opening: 40, leftover: 40 },
      ]);
    });

    it('creates a missing day as a placeholder opening on the previous close', async () => {
      seedWeek();

      await service.addDeliveryInTx(db as never, { branchId: B, productId: P, date: day('2026-09-18') }, 25);

      const fri = db.live('inventory', { date: day('2026-09-18') })[0];
      expect(fri).toEqual(
        expect.objectContaining({ quantity: 15, delivery: 25, leftover: 40, isAutoGenerated: true }),
      );
    });

    it('adds deliveries from two orders rather than keeping the last', async () => {
      const { tue } = seedWeek();
      const key = { branchId: B, productId: P, date: day('2026-09-15') };

      await service.addDeliveryInTx(db as never, key, 25);
      await service.addDeliveryInTx(db as never, key, 5);

      expect(db.tables.inventory.find((r) => r.id === tue.id)!.delivery).toBe(70);
    });
  });
});
