import { BadRequestException, NotFoundException } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { InventoryService } from './inventory.service';
import { PrismaService } from '../prisma/prisma.service';
import { CacheNamespaceService } from '../common/cache/cache-namespace.service';

// ---------------------------------------------------------------------------
// Minimal Prisma mock factory
// ---------------------------------------------------------------------------

function makePrisma() {
  return {
    inventory: {
      findFirst: jest.fn(),
      findUnique: jest.fn(),
      findMany: jest.fn(),
      update: jest.fn(),
      updateMany: jest.fn(),
      count: jest.fn(),
      upsert: jest.fn(),
      delete: jest.fn(),
    },
    productPriceHistory: {
      findMany: jest.fn(),
    },
    branch: { findMany: jest.fn() },
    product: { findMany: jest.fn() },
    $transaction: jest.fn(),
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeInvRow(
  overrides: Partial<{
    id: number;
    branchId: number;
    productId: number;
    date: Date;
    quantity: number;
    delivery: number;
    leftover: number;
    reject: number;
    isAutoGenerated: boolean;
    adjustments: { type: string; value: number }[];
    product: { id: number; type: string; price: number; name: string };
  }> = {},
) {
  return {
    id: 1,
    branchId: 1,
    productId: 1,
    date: new Date('2024-01-01'),
    quantity: 100,
    delivery: 0,
    leftover: 20,
    reject: 0,
    isAutoGenerated: true,
    adjustments: [],
    product: { id: 1, type: 'BREAD', price: 10, name: 'Pandesal' },
    ...overrides,
  };
}

function makeCache() {
  const store = new Map<string, unknown>();
  return {
    store,
    wrap: jest.fn(
      async (
        ns: string,
        parts: (string | number)[],
        fn: () => Promise<unknown>,
      ) => {
        const key = `${ns}:${parts.join(':')}`;
        if (store.has(key)) return store.get(key);
        const val = await fn();
        store.set(key, val);
        return val;
      },
    ),
    bump: jest.fn((ns: string) => {
      for (const k of [...store.keys()])
        if (k.startsWith(`${ns}:`)) store.delete(k);
    }),
  };
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('InventoryService', () => {
  let service: InventoryService;
  let prisma: ReturnType<typeof makePrisma>;
  let cache: ReturnType<typeof makeCache>;

  beforeEach(async () => {
    prisma = makePrisma();
    cache = makeCache();
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        InventoryService,
        { provide: PrismaService, useValue: prisma },
        { provide: CacheNamespaceService, useValue: cache },
      ],
    }).compile();

    service = module.get<InventoryService>(InventoryService);
  });

  afterEach(() => jest.clearAllMocks());

  // Carry-forward, create/update/remove and the leftover check are covered on
  // real data in inventory.chain.spec.ts.

  // ─────────────────────────────────────────────────────────────────────────
  // getSummary
  // ─────────────────────────────────────────────────────────────────────────

  describe('getSummary', () => {
    it('returns zeroed summary when there are no inventory rows', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.totalRevenue).toBe(0);
      expect(result.totalSold).toBe(0);
      expect(result.topProduct).toBeNull();
      expect(result.zeroSales).toEqual([]);
    });

    it('calculates sold as quantity + delivery + adjSum - leftover', async () => {
      const row = makeInvRow({
        quantity: 50,
        delivery: 20,
        leftover: 10,
        reject: 0,
        adjustments: [{ type: 'PULL_IN', value: 5 }],
        product: { id: 1, type: 'BREAD', price: 10, name: 'Pandesal' },
      });
      prisma.inventory.findMany.mockResolvedValue([row]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      // sold = 50 + 20 + 5 (PULL_IN, positive) - 10 = 65; revenue = 65 * 10 = 650
      expect(result.totalSold).toBe(65);
      expect(result.totalRevenue).toBe(650);
    });

    // Leftover carries into the next day's opening, so the old sum counted
    // Monday's unsold bread again on Tuesday.
    it('reports leftover over a range as the stock on hand at its end', async () => {
      prisma.inventory.findMany.mockResolvedValue([
        makeInvRow({ id: 1, branchId: 1, date: new Date('2024-01-01'), leftover: 10 }),
        makeInvRow({ id: 2, branchId: 1, date: new Date('2024-01-02'), leftover: 6 }),
        makeInvRow({ id: 3, branchId: 2, date: new Date('2024-01-02'), leftover: 3 }),
        makeInvRow({ id: 4, branchId: 2, date: new Date('2024-01-01'), leftover: 9 }),
      ]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01', '2024-01-02');

      expect(result.totalLeftover).toBe(6 + 3);
    });

    it('excludes rejects from sold and revenue', async () => {
      const row = makeInvRow({
        quantity: 50,
        delivery: 20,
        leftover: 10,
        reject: 8,
        adjustments: [{ type: 'PULL_IN', value: 5 }],
        product: { id: 1, type: 'BREAD', price: 10, name: 'Pandesal' },
      });
      prisma.inventory.findMany.mockResolvedValue([row]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      // sold = 50 + 20 + 5 - 10 - 8 (reject) = 57; revenue = 57 * 10 = 570
      expect(result.totalSold).toBe(57);
      expect(result.totalRevenue).toBe(570);
    });

    it('accumulates revenue by product type', async () => {
      const bread = makeInvRow({
        productId: 1,
        quantity: 100,
        delivery: 0,
        leftover: 0,
        adjustments: [],
        product: { id: 1, type: 'BREAD', price: 5, name: 'Tasty' },
      });
      const cake = makeInvRow({
        id: 2,
        productId: 2,
        quantity: 10,
        delivery: 0,
        leftover: 0,
        adjustments: [],
        product: { id: 2, type: 'CAKE', price: 100, name: 'Birthday' },
      });
      prisma.inventory.findMany.mockResolvedValue([bread, cake]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.revenueByType['BREAD']).toBe(500);
      expect(result.revenueByType['CAKE']).toBe(1000);
    });

    it('reports zero-sales products correctly', async () => {
      const row = makeInvRow({
        quantity: 0,
        delivery: 0,
        leftover: 0,
        adjustments: [],
        product: { id: 1, type: 'BREAD', price: 10, name: 'Unsold' },
      });
      prisma.inventory.findMany.mockResolvedValue([row]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.zeroSales).toHaveLength(1);
      expect(result.zeroSales[0].name).toBe('Unsold');
      // productId is what the UI keys React children on. Names are NOT unique
      // — the catalog deliberately seeds two products called "Bonette",
      // separated only by price — so a name-keyed list drops or duplicates
      // entries. See prisma/seed-products-apr2026.sql.
      expect(result.zeroSales[0].productId).toBe(1);
    });

    it('gives each same-named product its own zeroSales entry, distinguishable by productId', async () => {
      // Two real SKUs share the name "Bonette" at different prices.
      const rows = [
        makeInvRow({
          productId: 120,
          quantity: 0,
          delivery: 0,
          leftover: 0,
          reject: 0,
          product: { id: 120, type: 'SPECIAL', price: 30, name: 'Bonette' },
        }),
        makeInvRow({
          productId: 124,
          quantity: 0,
          delivery: 0,
          leftover: 0,
          reject: 0,
          product: { id: 124, type: 'SPECIAL', price: 8, name: 'Bonette' },
        }),
      ];
      prisma.inventory.findMany.mockResolvedValue(rows);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.zeroSales).toHaveLength(2);
      expect(result.zeroSales.map((z) => z.productId).sort()).toEqual([120, 124]);
      // Both carry the same name, which is exactly why the id is required.
      expect(result.zeroSales.every((z) => z.name === 'Bonette')).toBe(true);
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Branch scoping (#2) — managers must not read/modify other branches
  // ─────────────────────────────────────────────────────────────────────────

  describe('branch scoping', () => {
    it('findAll filters by branchId when a scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.findAll(1, 50, 7);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('findAll does not filter by branch when no scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.findAll(1, 50);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({ where: { deletedAt: null } }),
      );
    });

    it('search filters by branchId when a scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.search('pan', 1, 50, 7);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({ branchId: 7 }),
        }),
      );
    });

    it('findByProduct filters by branchId when a scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.findByProduct(3, 1, 50, 7);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { productId: 3, deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('findOne includes the branch scope in its where clause', async () => {
      prisma.inventory.findFirst.mockResolvedValue(makeInvRow());

      await service.findOne(10, 7);

      expect(prisma.inventory.findFirst).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 10, deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('findOne throws NotFound when the row is outside the branch scope', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(service.findOne(10, 7)).rejects.toThrow(NotFoundException);
    });

    it('remove scopes its existence check to the branch', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(service.remove(10, 7)).rejects.toThrow(NotFoundException);
      expect(prisma.inventory.findFirst).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 10, deletedAt: null, branchId: 7 },
        }),
      );
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Date-range bounds
  //
  // Every other aggregate bounds its range. getSummary did not, so one request
  // could ask for a decade of rows with their adjustments and products —
  // across a cross-region database.
  // ─────────────────────────────────────────────────────────────────────────

  describe('date-range bounds', () => {
    // With no start date this read returned the whole table, adjustments and
    // all. It now means today.
    it('reads only today when the date range is omitted', async () => {
      jest.useFakeTimers({ doNotFake: ['nextTick', 'setImmediate'] });
      jest.setSystemTime(new Date('2026-09-18T22:30:00Z')); // 06:30 Manila, the 19th
      prisma.inventory.findMany.mockResolvedValue([]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      await service.findByDateAllBranches();

      jest.useRealTimers();
      expect(prisma.inventory.findMany.mock.calls[0][0].where.date).toEqual(
        new Date('2026-09-19T00:00:00.000Z'),
      );
    });

    it('refuses a summary range wider than the shared limit', async () => {
      await expect(
        service.getSummary(null, '2020-01-01', '2030-01-01'),
      ).rejects.toBeInstanceOf(BadRequestException);
      expect(prisma.inventory.findMany).not.toHaveBeenCalled();
    });

    it('refuses a summary whose end precedes its start', async () => {
      await expect(
        service.getSummary(null, '2026-09-08', '2026-09-01'),
      ).rejects.toBeInstanceOf(BadRequestException);
    });

    it('still allows a summary inside the limit', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await expect(
        service.getSummary(null, '2026-09-01', '2026-09-10'),
      ).resolves.toMatchObject({ totalRevenue: 0 });
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Aggregation caching
  // ─────────────────────────────────────────────────────────────────────────

  describe('aggregation caching', () => {
    it('getSummary computes once, then serves from cache for identical args', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await service.getSummary(1, '2024-01-01', '2024-01-01');
      await service.getSummary(1, '2024-01-01', '2024-01-01');

      expect(prisma.inventory.findMany).toHaveBeenCalledTimes(1);
    });

    it('getSummary recomputes after the inventory namespace is bumped', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await service.getSummary(1, '2024-01-01', '2024-01-01');
      cache.bump('inventory-agg');
      await service.getSummary(1, '2024-01-01', '2024-01-01');

      expect(prisma.inventory.findMany).toHaveBeenCalledTimes(2);
    });

    it('getSummary caches per-branch/date (different args miss separately)', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await service.getSummary(1, '2024-01-01', '2024-01-01');
      await service.getSummary(2, '2024-01-01', '2024-01-01');

      expect(prisma.inventory.findMany).toHaveBeenCalledTimes(2);
    });
  });
});
