import { BadRequestException, NotFoundException } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { InventoryService } from './inventory.service';
import { PrismaService } from '../prisma/prisma.service';
import { CacheNamespaceService } from '../common/cache/cache-namespace.service';

// ---------------------------------------------------------------------------
// Minimal Prisma mock factory
// ---------------------------------------------------------------------------

function makePrisma() {
  return {
    inventory: {
      findFirst: jest.fn(),
      findUnique: jest.fn(),
      findMany: jest.fn(),
      update: jest.fn(),
      updateMany: jest.fn(),
      count: jest.fn(),
      upsert: jest.fn(),
      delete: jest.fn(),
    },
    productPriceHistory: {
      findMany: jest.fn(),
    },
    branch: { findMany: jest.fn() },
    product: { findMany: jest.fn() },
    $transaction: jest.fn(),
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeInvRow(
  overrides: Partial<{
    id: number;
    branchId: number;
    productId: number;
    date: Date;
    quantity: number;
    delivery: number;
    leftover: number;
    reject: number;
    isAutoGenerated: boolean;
    adjustments: { type: string; value: number }[];
    product: { id: number; type: string; price: number; name: string };
  }> = {},
) {
  return {
    id: 1,
    branchId: 1,
    productId: 1,
    date: new Date('2024-01-01'),
    quantity: 100,
    delivery: 0,
    leftover: 20,
    reject: 0,
    isAutoGenerated: true,
    adjustments: [],
    product: { id: 1, type: 'BREAD', price: 10, name: 'Pandesal' },
    ...overrides,
  };
}

function makeCache() {
  const store = new Map<string, unknown>();
  return {
    store,
    wrap: jest.fn(
      async (
        ns: string,
        parts: (string | number)[],
        fn: () => Promise<unknown>,
      ) => {
        const key = `${ns}:${parts.join(':')}`;
        if (store.has(key)) return store.get(key);
        const val = await fn();
        store.set(key, val);
        return val;
      },
    ),
    bump: jest.fn((ns: string) => {
      for (const k of [...store.keys()])
        if (k.startsWith(`${ns}:`)) store.delete(k);
    }),
  };
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('InventoryService', () => {
  let service: InventoryService;
  let prisma: ReturnType<typeof makePrisma>;
  let cache: ReturnType<typeof makeCache>;

  beforeEach(async () => {
    prisma = makePrisma();
    cache = makeCache();
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        InventoryService,
        { provide: PrismaService, useValue: prisma },
        { provide: CacheNamespaceService, useValue: cache },
      ],
    }).compile();

    service = module.get<InventoryService>(InventoryService);
  });

  afterEach(() => jest.clearAllMocks());

  // ─────────────────────────────────────────────────────────────────────────
  // create / createBulk — soft-delete resurrection
  //
  // `@@unique([branchId, productId, date])` does not include `deletedAt`, so an
  // upsert re-entering a previously deleted day matches the tombstone and
  // updates it. Without clearing `deletedAt` the write succeeds and the row
  // stays invisible to every read, all of which filter `deletedAt: null`.
  // ─────────────────────────────────────────────────────────────────────────

  describe('create — soft-deleted rows', () => {
    const dto = {
      branchId: 1,
      productId: 5,
      date: '2026-09-02',
      quantity: 10,
      delivery: 0,
      leftover: 0,
      reject: 0,
    };

    it('clears deletedAt so re-entering a deleted day restores the row', async () => {
      prisma.inventory.upsert.mockResolvedValue({ id: 1 });

      await service.create(dto, 7);

      const args = prisma.inventory.upsert.mock.calls[0][0];
      expect(args.update.deletedAt).toBeNull();
    });

    it('clears deletedAt on every row of a bulk write', async () => {
      prisma.$transaction.mockResolvedValue([]);
      prisma.inventory.upsert.mockReturnValue({});

      await service.createBulk([dto, { ...dto, productId: 6 }], 7);

      for (const call of prisma.inventory.upsert.mock.calls) {
        expect(call[0].update.deletedAt).toBeNull();
      }
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // recascadeLeftovers
  // ─────────────────────────────────────────────────────────────────────────

  describe('recascadeLeftovers', () => {
    it('throws NotFoundException when the seed row does not exist', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(
        service.recascadeLeftovers(1, 1, '2024-01-01'),
      ).rejects.toThrow(NotFoundException);
    });

    it('returns { updated: 0 } when there are no subsequent auto-generated rows', async () => {
      prisma.inventory.findFirst.mockResolvedValue(
        makeInvRow({ leftover: 30 }),
      );
      prisma.inventory.findMany.mockResolvedValue([]);

      const result = await service.recascadeLeftovers(1, 1, '2024-01-01');

      expect(result).toEqual({ updated: 0 });
      expect(prisma.inventory.update).not.toHaveBeenCalled();
    });

    it('adds a delivery landing on a placeholder day to the carried balance', async () => {
      // A flat updateMany of seed.leftover overwrote whatever a placeholder day
      // actually received. Nothing was sold on that day — it is a placeholder —
      // so its closing balance is everything it had on hand.
      const seed = makeInvRow({ leftover: 30, date: new Date('2024-01-01') });
      const day2 = makeInvRow({
        id: 2,
        date: new Date('2024-01-02'),
        delivery: 12,
        isAutoGenerated: true,
        adjustments: [],
      });
      const day3 = makeInvRow({
        id: 3,
        date: new Date('2024-01-03'),
        delivery: 0,
        isAutoGenerated: true,
        adjustments: [],
      });

      prisma.inventory.findFirst.mockResolvedValue(seed);
      prisma.inventory.findMany.mockResolvedValue([day2, day3]);
      prisma.$transaction.mockResolvedValue([]);

      const result = await service.recascadeLeftovers(1, 1, '2024-01-01');

      expect(result).toEqual({ updated: 2 });
      const written = prisma.inventory.update.mock.calls.map((c) => c[0]);
      expect(written[0]).toMatchObject({
        where: { id: 2 },
        data: { quantity: 30, leftover: 42 },
      });
      // Day 3 opens on day 2's closing balance, not on the seed's.
      expect(written[1]).toMatchObject({
        where: { id: 3 },
        data: { quantity: 42, leftover: 42 },
      });
    });

    it('carries a transfer booked against a placeholder day', async () => {
      const seed = makeInvRow({ leftover: 30, date: new Date('2024-01-01') });
      const day2 = makeInvRow({
        id: 2,
        date: new Date('2024-01-02'),
        delivery: 0,
        isAutoGenerated: true,
        adjustments: [{ type: 'PULL_OUT', value: 5 }],
      });

      prisma.inventory.findFirst.mockResolvedValue(seed);
      prisma.inventory.findMany.mockResolvedValue([day2]);
      prisma.$transaction.mockResolvedValue([]);

      await service.recascadeLeftovers(1, 1, '2024-01-01');

      expect(prisma.inventory.update.mock.calls[0][0]).toMatchObject({
        where: { id: 2 },
        data: { quantity: 30, leftover: 25 },
      });
    });

    it('propagates the seed leftover to all subsequent auto-generated rows', async () => {
      const seed = makeInvRow({ leftover: 30, date: new Date('2024-01-01') });
      const day2 = makeInvRow({
        id: 2,
        date: new Date('2024-01-02'),
        quantity: 10,
        leftover: 10,
        delivery: 0,
        isAutoGenerated: true,
        adjustments: [],
      });
      const day3 = makeInvRow({
        id: 3,
        date: new Date('2024-01-03'),
        quantity: 10,
        leftover: 10,
        delivery: 0,
        isAutoGenerated: true,
        adjustments: [],
      });

      prisma.inventory.findFirst.mockResolvedValue(seed);
      prisma.inventory.findMany.mockResolvedValue([day2, day3]);
      prisma.$transaction.mockResolvedValue([]);

      const result = await service.recascadeLeftovers(1, 1, '2024-01-01');

      expect(result).toEqual({ updated: 2 });
      // With no delivery and no adjustments on either placeholder, both simply
      // carry the seed leftover — one batched transaction, one write per row.
      const written = prisma.inventory.update.mock.calls.map((c) => c[0]);
      expect(written).toEqual([
        expect.objectContaining({ where: { id: 2 }, data: { quantity: 30, leftover: 30 } }),
        expect.objectContaining({ where: { id: 3 }, data: { quantity: 30, leftover: 30 } }),
      ]);
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // getSummary
  // ─────────────────────────────────────────────────────────────────────────

  describe('getSummary', () => {
    it('returns zeroed summary when there are no inventory rows', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.totalRevenue).toBe(0);
      expect(result.totalSold).toBe(0);
      expect(result.topProduct).toBeNull();
      expect(result.zeroSales).toEqual([]);
    });

    it('calculates sold as quantity + delivery + adjSum - leftover', async () => {
      const row = makeInvRow({
        quantity: 50,
        delivery: 20,
        leftover: 10,
        reject: 0,
        adjustments: [{ type: 'PULL_IN', value: 5 }],
        product: { id: 1, type: 'BREAD', price: 10, name: 'Pandesal' },
      });
      prisma.inventory.findMany.mockResolvedValue([row]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      // sold = 50 + 20 + 5 (PULL_IN, positive) - 10 = 65; revenue = 65 * 10 = 650
      expect(result.totalSold).toBe(65);
      expect(result.totalRevenue).toBe(650);
    });

    it('excludes rejects from sold and revenue', async () => {
      const row = makeInvRow({
        quantity: 50,
        delivery: 20,
        leftover: 10,
        reject: 8,
        adjustments: [{ type: 'PULL_IN', value: 5 }],
        product: { id: 1, type: 'BREAD', price: 10, name: 'Pandesal' },
      });
      prisma.inventory.findMany.mockResolvedValue([row]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      // sold = 50 + 20 + 5 - 10 - 8 (reject) = 57; revenue = 57 * 10 = 570
      expect(result.totalSold).toBe(57);
      expect(result.totalRevenue).toBe(570);
    });

    it('accumulates revenue by product type', async () => {
      const bread = makeInvRow({
        productId: 1,
        quantity: 100,
        delivery: 0,
        leftover: 0,
        adjustments: [],
        product: { id: 1, type: 'BREAD', price: 5, name: 'Tasty' },
      });
      const cake = makeInvRow({
        id: 2,
        productId: 2,
        quantity: 10,
        delivery: 0,
        leftover: 0,
        adjustments: [],
        product: { id: 2, type: 'CAKE', price: 100, name: 'Birthday' },
      });
      prisma.inventory.findMany.mockResolvedValue([bread, cake]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.revenueByType['BREAD']).toBe(500);
      expect(result.revenueByType['CAKE']).toBe(1000);
    });

    it('reports zero-sales products correctly', async () => {
      const row = makeInvRow({
        quantity: 0,
        delivery: 0,
        leftover: 0,
        adjustments: [],
        product: { id: 1, type: 'BREAD', price: 10, name: 'Unsold' },
      });
      prisma.inventory.findMany.mockResolvedValue([row]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.zeroSales).toHaveLength(1);
      expect(result.zeroSales[0].name).toBe('Unsold');
      // productId is what the UI keys React children on. Names are NOT unique
      // — the catalog deliberately seeds two products called "Bonette",
      // separated only by price — so a name-keyed list drops or duplicates
      // entries. See prisma/seed-products-apr2026.sql.
      expect(result.zeroSales[0].productId).toBe(1);
    });

    it('gives each same-named product its own zeroSales entry, distinguishable by productId', async () => {
      // Two real SKUs share the name "Bonette" at different prices.
      const rows = [
        makeInvRow({
          productId: 120,
          quantity: 0,
          delivery: 0,
          leftover: 0,
          reject: 0,
          product: { id: 120, type: 'SPECIAL', price: 30, name: 'Bonette' },
        }),
        makeInvRow({
          productId: 124,
          quantity: 0,
          delivery: 0,
          leftover: 0,
          reject: 0,
          product: { id: 124, type: 'SPECIAL', price: 8, name: 'Bonette' },
        }),
      ];
      prisma.inventory.findMany.mockResolvedValue(rows);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.zeroSales).toHaveLength(2);
      expect(result.zeroSales.map((z) => z.productId).sort()).toEqual([120, 124]);
      // Both carry the same name, which is exactly why the id is required.
      expect(result.zeroSales.every((z) => z.name === 'Bonette')).toBe(true);
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // update — cascade warning count
  // ─────────────────────────────────────────────────────────────────────────

  describe('update — cascade warning count', () => {
    const baseExisting = makeInvRow({ id: 10, leftover: 20 });
    const baseUpdated = {
      ...makeInvRow({ id: 10 }),
      branchId: 1,
      productId: 1,
      date: new Date('2024-01-01'),
    };

    it('returns cascadeWarning = 0 when leftover is unchanged', async () => {
      prisma.inventory.findFirst.mockResolvedValue({
        ...baseExisting,
        leftover: 20,
      });
      prisma.inventory.update.mockResolvedValue(baseUpdated);
      prisma.inventory.count.mockResolvedValue(0);

      const result = await service.update(10, { leftover: 20 });

      expect(result.cascadeWarning).toBe(0);
      expect(prisma.inventory.count).toHaveBeenCalledTimes(1);
    });

    it('does not count soft-deleted downstream rows as stale', async () => {
      prisma.inventory.findFirst.mockResolvedValue(makeInvRow({ leftover: 20 }));
      prisma.inventory.update.mockResolvedValue(makeInvRow({ leftover: 20 }));
      prisma.inventory.count.mockResolvedValue(0);

      await service.update(1, { delivery: 5 });

      const where = prisma.inventory.count.mock.calls[0][0].where;
      expect(where.deletedAt).toBeNull();
    });

    it('returns cascadeWarning > 0 when downstream auto-generated rows exist and leftover is unchanged', async () => {
      prisma.inventory.findFirst.mockResolvedValue({
        ...baseExisting,
        leftover: 20,
      });
      prisma.inventory.update.mockResolvedValue(baseUpdated);
      prisma.inventory.count.mockResolvedValue(3);

      const result = await service.update(10, { leftover: 20 });

      expect(result.cascadeWarning).toBe(3);
    });

    it('auto-cascades and returns cascadeWarning = 0 when leftover changes', async () => {
      prisma.inventory.findFirst
        .mockResolvedValueOnce({ ...baseExisting, leftover: 20 }) // update() lookup
        .mockResolvedValueOnce(baseUpdated); // recascadeLeftovers seed lookup
      prisma.inventory.update.mockResolvedValue(baseUpdated);
      prisma.inventory.findMany.mockResolvedValue([]); // no subsequent rows

      const result = await service.update(10, { leftover: 35 });

      // When leftover changes, recascade runs; cascadeWarning is always 0 in that branch
      expect(result.cascadeWarning).toBe(0);
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Branch scoping (#2) — managers must not read/modify other branches
  // ─────────────────────────────────────────────────────────────────────────

  describe('branch scoping', () => {
    it('findAll filters by branchId when a scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.findAll(1, 50, 7);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('findAll does not filter by branch when no scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.findAll(1, 50);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({ where: { deletedAt: null } }),
      );
    });

    it('search filters by branchId when a scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.search('pan', 1, 50, 7);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({ branchId: 7 }),
        }),
      );
    });

    it('findByProduct filters by branchId when a scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.findByProduct(3, 1, 50, 7);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { productId: 3, deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('findOne includes the branch scope in its where clause', async () => {
      prisma.inventory.findFirst.mockResolvedValue(makeInvRow());

      await service.findOne(10, 7);

      expect(prisma.inventory.findFirst).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 10, deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('findOne throws NotFound when the row is outside the branch scope', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(service.findOne(10, 7)).rejects.toThrow(NotFoundException);
    });

    it('update scopes its existence check to the branch', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(service.update(10, { leftover: 5 }, 7)).rejects.toThrow(
        NotFoundException,
      );
      expect(prisma.inventory.findFirst).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 10, deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('remove scopes its existence check to the branch', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(service.remove(10, 7)).rejects.toThrow(NotFoundException);
      expect(prisma.inventory.findFirst).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 10, deletedAt: null, branchId: 7 },
        }),
      );
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Aggregation caching (Task 4)
  // ─────────────────────────────────────────────────────────────────────────

  // ─────────────────────────────────────────────────────────────────────────
  // Date-range bounds
  //
  // Every other aggregate bounds its range. getSummary did not, so one request
  // could ask for a decade of rows with their adjustments and products —
  // across a cross-region database.
  // ─────────────────────────────────────────────────────────────────────────

  describe('date-range bounds', () => {
    it('refuses a summary range wider than the shared limit', async () => {
      await expect(
        service.getSummary(null, '2020-01-01', '2030-01-01'),
      ).rejects.toBeInstanceOf(BadRequestException);
      expect(prisma.inventory.findMany).not.toHaveBeenCalled();
    });

    it('refuses a summary whose end precedes its start', async () => {
      await expect(
        service.getSummary(null, '2026-09-08', '2026-09-01'),
      ).rejects.toBeInstanceOf(BadRequestException);
    });

    it('still allows a summary inside the limit', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await expect(
        service.getSummary(null, '2026-09-01', '2026-09-10'),
      ).resolves.toMatchObject({ totalRevenue: 0 });
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // updateBulk
  //
  // The sheet used to PATCH one row per edit through Promise.all. Against the
  // global 20-request/minute throttle, editing a 165-product sheet 429s after
  // the twentieth row — and Promise.all rejects on the first failure, so the
  // user gets "save failed" on a partial write. One request, one transaction.
  // ─────────────────────────────────────────────────────────────────────────

  // ─────────────────────────────────────────────────────────────────────────
  // Impossible rows
  //
  // Nothing stopped leftover + reject exceeding the stock that existed, so a
  // typo produced negative `sold` and negative revenue. `zeroSales` filters
  // `sold <= 0`, which quietly absorbed it instead of surfacing it.
  // ─────────────────────────────────────────────────────────────────────────

  // ─────────────────────────────────────────────────────────────────────────
  // Audit trail
  //
  // createdById answered "who entered this"; nothing answered "who changed it".
  // Edits move revenue, so they are exactly the writes worth attributing.
  // ─────────────────────────────────────────────────────────────────────────

  describe('audit trail', () => {
    it('records who amended a row', async () => {
      prisma.inventory.findFirst.mockResolvedValue(makeInvRow());
      prisma.inventory.update.mockResolvedValue(makeInvRow());
      prisma.inventory.count.mockResolvedValue(0);

      await service.update(1, { delivery: 5 }, undefined, 42);

      expect(prisma.inventory.update.mock.calls[0][0].data.updatedById).toBe(42);
    });

    it('records who amended each row of a bulk save', async () => {
      prisma.inventory.findMany
        .mockResolvedValueOnce([makeInvRow({ id: 1 }), makeInvRow({ id: 2 })])
        .mockResolvedValueOnce([]);
      prisma.$transaction.mockResolvedValue([]);

      await service.updateBulk([{ id: 1, delivery: 5 }, { id: 2, delivery: 6 }], undefined, 42);

      for (const call of prisma.inventory.update.mock.calls) {
        expect(call[0].data.updatedById).toBe(42);
      }
    });

    it('leaves the attribution null when there is no authenticated user', async () => {
      prisma.inventory.findFirst.mockResolvedValue(makeInvRow());
      prisma.inventory.update.mockResolvedValue(makeInvRow());
      prisma.inventory.count.mockResolvedValue(0);

      await service.update(1, { delivery: 5 });

      expect(prisma.inventory.update.mock.calls[0][0].data.updatedById).toBeNull();
    });
  });

  describe('impossible rows', () => {
    it('refuses an update whose leftover exceeds the stock on hand', async () => {
      prisma.inventory.findFirst.mockResolvedValue(
        makeInvRow({ quantity: 100, delivery: 0, leftover: 10, reject: 0 }),
      );

      await expect(
        service.update(1, { leftover: 500 }),
      ).rejects.toBeInstanceOf(BadRequestException);
      expect(prisma.inventory.update).not.toHaveBeenCalled();
    });

    it('refuses when leftover and reject together exceed the stock', async () => {
      prisma.inventory.findFirst.mockResolvedValue(
        makeInvRow({ quantity: 100, delivery: 0, leftover: 0, reject: 0 }),
      );

      await expect(
        service.update(1, { leftover: 60, reject: 60 }),
      ).rejects.toBeInstanceOf(BadRequestException);
    });

    it('counts adjustments as part of the stock on hand', async () => {
      // 100 opening + 50 pulled in leaves room for a 140 leftover.
      prisma.inventory.findFirst.mockResolvedValue(
        makeInvRow({
          quantity: 100,
          delivery: 0,
          leftover: 0,
          reject: 0,
          adjustments: [{ type: 'PULL_IN', value: 50 }],
        }),
      );
      prisma.inventory.update.mockResolvedValue(makeInvRow({ leftover: 140 }));
      prisma.inventory.findMany.mockResolvedValue([]); // nothing downstream to cascade
      prisma.inventory.count.mockResolvedValue(0);

      await expect(service.update(1, { leftover: 140 })).resolves.toBeDefined();
    });

    it('allows a row that sells out exactly', async () => {
      prisma.inventory.findFirst.mockResolvedValue(
        makeInvRow({ quantity: 100, delivery: 0, leftover: 0, reject: 0 }),
      );
      prisma.inventory.update.mockResolvedValue(makeInvRow({ leftover: 100 }));
      prisma.inventory.findMany.mockResolvedValue([]);
      prisma.inventory.count.mockResolvedValue(0);

      await expect(service.update(1, { leftover: 100 })).resolves.toBeDefined();
    });

    it('refuses an impossible row inside a bulk save', async () => {
      prisma.inventory.findMany.mockResolvedValueOnce([
        makeInvRow({ id: 1, quantity: 10, delivery: 0, leftover: 0, reject: 0 }),
      ]);

      await expect(
        service.updateBulk([{ id: 1, leftover: 500 }]),
      ).rejects.toBeInstanceOf(BadRequestException);
      expect(prisma.$transaction).not.toHaveBeenCalled();
    });
  });

  describe('updateBulk', () => {
    const rowsFor = (ids: number[]) =>
      ids.map((id) =>
        makeInvRow({ id, productId: id, leftover: 20, isAutoGenerated: false }),
      );

    it('writes every edit in a single transaction', async () => {
      prisma.inventory.findMany
        .mockResolvedValueOnce(rowsFor([1, 2, 3]))
        .mockResolvedValueOnce([]); // no downstream rows to carry or warn about
      prisma.$transaction.mockResolvedValue([]);

      const res = await service.updateBulk([
        { id: 1, delivery: 5 },
        { id: 2, delivery: 6 },
        { id: 3, delivery: 7 },
      ]);

      expect(res.updated).toBe(3);
      expect(prisma.$transaction).toHaveBeenCalledTimes(1);
      expect(prisma.inventory.update).toHaveBeenCalledTimes(3);
    });

    it('refuses the whole batch when a row is outside the branch scope', async () => {
      // Only two of the three ids come back once the scope is applied.
      prisma.inventory.findMany.mockResolvedValueOnce(rowsFor([1, 2]));

      await expect(
        service.updateBulk(
          [{ id: 1, delivery: 5 }, { id: 2, delivery: 6 }, { id: 3, delivery: 7 }],
          1,
        ),
      ).rejects.toBeInstanceOf(NotFoundException);
      expect(prisma.$transaction).not.toHaveBeenCalled();
    });

    it('scopes its lookup to the branch when one is given', async () => {
      prisma.inventory.findMany
        .mockResolvedValueOnce(rowsFor([1]))
        .mockResolvedValueOnce([]);
      prisma.$transaction.mockResolvedValue([]);

      await service.updateBulk([{ id: 1, delivery: 5 }], 7);

      const where = prisma.inventory.findMany.mock.calls[0][0].where;
      expect(where).toMatchObject({ branchId: 7, deletedAt: null });
    });

    it('cascades downstream auto rows when a leftover changes', async () => {
      prisma.inventory.findMany
        .mockResolvedValueOnce(rowsFor([1])) // the rows being edited
        .mockResolvedValueOnce([
          // downstream rows for product 1, ascending by date
          { id: 90, branchId: 1, productId: 1, date: new Date('2024-01-02'), isAutoGenerated: true, delivery: 0, adjustments: [] },
          { id: 91, branchId: 1, productId: 1, date: new Date('2024-01-03'), isAutoGenerated: true, delivery: 0, adjustments: [] },
          { id: 92, branchId: 1, productId: 1, date: new Date('2024-01-04'), isAutoGenerated: false, delivery: 0, adjustments: [] },
        ]);
      prisma.$transaction.mockResolvedValue([]);

      const res = await service.updateBulk([{ id: 1, leftover: 9 }]);

      // Stops at the manual row, exactly as recascadeLeftovers does.
      expect(res.cascadeUpdated).toBe(2);
      const cascaded = prisma.inventory.update.mock.calls
        .map((c) => c[0])
        .filter((c) => c.where.id === 90 || c.where.id === 91);
      expect(cascaded).toEqual([
        expect.objectContaining({ where: { id: 90 }, data: { quantity: 9, leftover: 9 } }),
        expect.objectContaining({ where: { id: 91 }, data: { quantity: 9, leftover: 9 } }),
      ]);
    });

    it('warns about stale downstream rows when leftover was not touched', async () => {
      // Editing only delivery leaves later placeholder days derived from an
      // older leftover. The single-row update() surfaced that as
      // cascadeWarning; the bulk path has to keep telling the user.
      prisma.inventory.findMany
        .mockResolvedValueOnce(rowsFor([1]))
        .mockResolvedValueOnce([
          { id: 90, branchId: 1, productId: 1, date: new Date('2024-01-02'), isAutoGenerated: true, delivery: 0, adjustments: [] },
        ]);
      prisma.$transaction.mockResolvedValue([]);

      const res = await service.updateBulk([{ id: 1, delivery: 5 }]);

      expect(res.cascadeUpdated).toBe(0);
      expect(res.cascadeWarnings).toEqual([
        { branchId: 1, productId: 1, fromDate: '2024-01-01' },
      ]);
    });

    it('does not warn about a row it already cascaded', async () => {
      prisma.inventory.findMany
        .mockResolvedValueOnce(rowsFor([1]))
        .mockResolvedValueOnce([
          { id: 90, branchId: 1, productId: 1, date: new Date('2024-01-02'), isAutoGenerated: true, delivery: 0, adjustments: [] },
        ]);
      prisma.$transaction.mockResolvedValue([]);

      const res = await service.updateBulk([{ id: 1, leftover: 9 }]);

      expect(res.cascadeUpdated).toBe(1);
      expect(res.cascadeWarnings).toEqual([]);
    });

    it('carries a placeholder delivery forward in the bulk cascade too', async () => {
      prisma.inventory.findMany
        .mockResolvedValueOnce(rowsFor([1]))
        .mockResolvedValueOnce([
          { id: 90, branchId: 1, productId: 1, date: new Date('2024-01-02'), isAutoGenerated: true, delivery: 12, adjustments: [] },
          { id: 91, branchId: 1, productId: 1, date: new Date('2024-01-03'), isAutoGenerated: true, delivery: 0, adjustments: [] },
        ]);
      prisma.$transaction.mockResolvedValue([]);

      const res = await service.updateBulk([{ id: 1, leftover: 9 }]);

      expect(res.cascadeUpdated).toBe(2);
      const written = prisma.inventory.update.mock.calls
        .map((c) => c[0])
        .filter((c) => c.where.id === 90 || c.where.id === 91);
      expect(written).toEqual([
        expect.objectContaining({ where: { id: 90 }, data: { quantity: 9, leftover: 21 } }),
        expect.objectContaining({ where: { id: 91 }, data: { quantity: 21, leftover: 21 } }),
      ]);
    });

    it('does not cascade when no leftover changed', async () => {
      prisma.inventory.findMany
        .mockResolvedValueOnce(rowsFor([1]))
        .mockResolvedValueOnce([]);
      prisma.$transaction.mockResolvedValue([]);

      const res = await service.updateBulk([{ id: 1, delivery: 5 }]);

      expect(res.cascadeUpdated).toBe(0);
      expect(res.cascadeWarnings).toEqual([]);
    });
  });

  describe('aggregation caching', () => {
    it('getSummary computes once, then serves from cache for identical args', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await service.getSummary(1, '2024-01-01', '2024-01-01');
      await service.getSummary(1, '2024-01-01', '2024-01-01');

      expect(prisma.inventory.findMany).toHaveBeenCalledTimes(1);
    });

    it('getSummary recomputes after the inventory namespace is bumped', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await service.getSummary(1, '2024-01-01', '2024-01-01');
      cache.bump('inventory-agg');
      await service.getSummary(1, '2024-01-01', '2024-01-01');

      expect(prisma.inventory.findMany).toHaveBeenCalledTimes(2);
    });

    it('getSummary caches per-branch/date (different args miss separately)', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await service.getSummary(1, '2024-01-01', '2024-01-01');
      await service.getSummary(2, '2024-01-01', '2024-01-01');

      expect(prisma.inventory.findMany).toHaveBeenCalledTimes(2);
    });
  });
});
