import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma, ProductType } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { getEffectivePrice } from '../common/utils/price-history.util';
import {
  computeAdjSum,
  computeSold,
} from '../common/utils/inventory-metrics.util';
import { csvField } from '../common/utils/csv.util';
import { CreateInventoryDto } from './dto/create-inventory.dto';
import { UpdateInventoryDto } from './dto/update-inventory.dto';
import { UpdateInventoryItemDto } from './dto/update-inventory-bulk.dto';
import { CacheNamespaceService } from '../common/cache/cache-namespace.service';
import { CACHE_NS } from '../common/cache/cache-namespaces';
import { clampPageSize } from '../common/constants/inventory.constants';
import {
  MAX_REPORT_RANGE_DAYS,
  assertDateRange,
  eachDayInclusive,
  toUtcDay,
} from '../common/utils/date-range.util';

/** The subset of an inventory row the bulk save and its cascade need. */
interface SheetRow {
  id: number;
  branchId: number;
  productId: number;
  date: Date;
  leftover: number;
}

/** A row whose later days are still placeholders derived from an older count. */
export interface CascadeWarning {
  branchId: number;
  productId: number;
  fromDate: string;
}

@Injectable()
export class InventoryService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly cache: CacheNamespaceService,
  ) {}

  /**
   * Returns today's calendar date as a UTC-midnight Date, resolved in Manila.
   *
   * This used to read the process timezone via `TZ=Asia/Manila`, which worked
   * on Cloud Run. **Vercel reserves `TZ` and refuses to set it**, so functions
   * always run UTC — and under UTC every call from 16:00–23:59 UTC, which is
   * **00:00–08:00 in Manila**, returned the *previous* date. That window is the
   * early-morning baking shift, so it would have been wrong precisely when the
   * inventory sheets are first opened each day.
   *
   * Pinning the zone explicitly is the only portable fix, and it matches what
   * jobs.service, autofill-on-demand, and suggestions.service already do.
   */
  private localToday(): Date {
    const str = new Intl.DateTimeFormat('en-CA', {
      timeZone: 'Asia/Manila',
    }).format(new Date());
    return new Date(`${str}T00:00:00.000Z`);
  }

  /**
   * Reject a row that claims more stock left over than ever existed.
   *
   * `sold = quantity + delivery + adjSum - leftover - reject`, so an entry
   * where leftover and reject together exceed the stock on hand makes `sold`
   * negative — and revenue with it. Nothing caught that: `zeroSales` filters
   * `sold <= 0`, so an impossible row was reported as a product that simply did
   * not sell, and the negative revenue quietly reduced the day's total.
   *
   * Deliberately not applied to the XLSX import, which reproduces a historical
   * sheet as it was actually written. Refusing a whole month's import over one
   * badly-typed row from last year would be the wrong trade; this guards entry,
   * where the person who made the typo is present to fix it.
   */
  private assertRowIsPossible(row: {
    quantity: number;
    delivery: number;
    leftover: number;
    reject: number;
    adjustments?: Array<{ type: string; value: number }>;
  }): void {
    const onHand =
      row.quantity + row.delivery + computeAdjSum(row.adjustments);
    const accountedFor = row.leftover + row.reject;
    if (accountedFor > onHand) {
      throw new BadRequestException(
        `Leftover (${row.leftover}) and reject (${row.reject}) come to ${accountedFor}, ` +
          `but only ${onHand} units existed for this product and day.`,
      );
    }
  }

  async create(body: CreateInventoryDto, userId?: number) {
    // Upsert: if a record for the same branch+product+date exists, update it.
    //
    // `@@unique([branchId, productId, date])` does not include `deletedAt`, so a
    // soft-deleted row still occupies the slot and this upsert matches it. Without
    // clearing `deletedAt` the write would succeed and the row would stay invisible
    // to every read, all of which filter `deletedAt: null`. Re-entering a deleted
    // day is a restore.
    return this.prisma.inventory.upsert({
      where: {
        branchId_productId_date: {
          branchId: body.branchId,
          productId: body.productId,
          date: toUtcDay(body.date),
        },
      },
      update: {
        quantity: body.quantity,
        delivery: body.delivery,
        leftover: body.leftover,
        reject: body.reject,
        notes: body.notes,
        isAutoGenerated: false,
        deletedAt: null,
      },
      create: {
        branchId: body.branchId,
        productId: body.productId,
        date: toUtcDay(body.date),
        quantity: body.quantity,
        delivery: body.delivery,
        leftover: body.leftover,
        reject: body.reject,
        notes: body.notes,
        isAutoGenerated: false,
        createdById: userId,
      },
      include: {
        branch: true,
        product: true,
      },
    });
  }

  async createBulk(items: CreateInventoryDto[], userId?: number) {
    return this.prisma.$transaction(
      items.map((item) =>
        this.prisma.inventory.upsert({
          where: {
            branchId_productId_date: {
              branchId: item.branchId,
              productId: item.productId,
              date: toUtcDay(item.date),
            },
          },
          update: {
            quantity: item.quantity,
            delivery: item.delivery,
            leftover: item.leftover,
            reject: item.reject,
            notes: item.notes,
            isAutoGenerated: false,
            // See create(): the unique key ignores deletedAt, so a re-entered
            // day must clear the tombstone or the write lands invisibly.
            deletedAt: null,
          },
          create: {
            branchId: item.branchId,
            productId: item.productId,
            date: toUtcDay(item.date),
            quantity: item.quantity,
            delivery: item.delivery,
            leftover: item.leftover,
            reject: item.reject,
            notes: item.notes,
            isAutoGenerated: false,
            createdById: userId,
          },
        }),
      ),
    );
  }

  async findAll(page = 1, limit = 50, branchId?: number) {
    limit = clampPageSize(limit);
    const skip = (page - 1) * limit;
    const where = {
      deletedAt: null,
      ...(branchId != null ? { branchId } : {}),
    };
    const [data, total] = await this.prisma.$transaction([
      this.prisma.inventory.findMany({
        where,
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: { branch: true, product: true },
      }),
      this.prisma.inventory.count({ where }),
    ]);
    return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  async search(q: string, page = 1, limit = 50, branchId?: number) {
    limit = clampPageSize(limit);
    const skip = (page - 1) * limit;
    const where = {
      deletedAt: null,
      ...(branchId != null ? { branchId } : {}),
      OR: [
        { notes: { contains: q, mode: Prisma.QueryMode.insensitive } },
        {
          branch: { name: { contains: q, mode: Prisma.QueryMode.insensitive } },
        },
        {
          product: {
            name: { contains: q, mode: Prisma.QueryMode.insensitive },
          },
        },
      ],
    };
    const [data, total] = await this.prisma.$transaction([
      this.prisma.inventory.findMany({
        where,
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: { branch: true, product: true },
      }),
      this.prisma.inventory.count({ where }),
    ]);
    return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  async findByBranch(branchId: number, page = 1, limit = 50) {
    limit = clampPageSize(limit);
    const skip = (page - 1) * limit;
    const where = { branchId, deletedAt: null };
    const [data, total] = await this.prisma.$transaction([
      this.prisma.inventory.findMany({
        where,
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: { product: true },
      }),
      this.prisma.inventory.count({ where }),
    ]);
    return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  async findByProduct(
    productId: number,
    page = 1,
    limit = 50,
    branchId?: number,
  ) {
    limit = clampPageSize(limit);
    const skip = (page - 1) * limit;
    const where = {
      productId,
      deletedAt: null,
      ...(branchId != null ? { branchId } : {}),
    };
    const [data, total] = await this.prisma.$transaction([
      this.prisma.inventory.findMany({
        where,
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: { branch: true },
      }),
      this.prisma.inventory.count({ where }),
    ]);
    return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  private aggregateInventoryMetrics(
    rows: Array<{
      productId: number;
      date: Date;
      quantity: number;
      delivery: number;
      leftover: number;
      reject: number;
      adjustments: Array<{ type: string; value: number }>;
      product: {
        type: string;
        price: number | { toNumber(): number };
        name: string;
      };
    }>,
    historyByProduct: Map<number, Array<{ effectiveAt: Date; price: number }>>,
  ): {
    totalRevenue: number;
    totalSold: number;
    totalDelivery: number;
    totalLeftover: number;
    totalReject: number;
    revenueByType: Record<string, number>;
    revenueByProduct: Map<
      number,
      { productId: number; name: string; revenue: number; sold: number }
    >;
  } {
    let totalRevenue = 0;
    let totalSold = 0;
    let totalDelivery = 0;
    let totalLeftover = 0;
    let totalReject = 0;
    const revenueByType: Record<string, number> = {
      BREAD: 0,
      CAKE: 0,
      SPECIAL: 0,
      MISCELLANEOUS: 0,
    };
    // Keyed by productId, and the VALUE carries productId too: consumers take
    // .values() and hand the result to the UI, which needs a unique React key.
    // Product names are deliberately not unique (two "Bonette" rows, ₱30 and
    // ₱8), so a name-keyed list drops or duplicates entries.
    const revenueByProduct = new Map<
      number,
      { productId: number; name: string; revenue: number; sold: number }
    >();

    for (const inv of rows) {
      const sold = computeSold(inv);
      const effectivePrice = getEffectivePrice(
        inv.productId,
        inv.date,
        Number(inv.product.price),
        historyByProduct,
      );
      const revenue = sold * effectivePrice;

      totalRevenue += revenue;
      totalSold += sold;
      totalDelivery += inv.delivery;
      totalLeftover += inv.leftover;
      totalReject += inv.reject;

      if (inv.product.type in revenueByType)
        revenueByType[inv.product.type] += revenue;
      const prev = revenueByProduct.get(inv.productId);
      revenueByProduct.set(inv.productId, {
        productId: inv.productId,
        name: inv.product.name,
        revenue: (prev?.revenue ?? 0) + revenue,
        sold: (prev?.sold ?? 0) + sold,
      });
    }

    return {
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      revenueByProduct,
    };
  }

  private async fetchHistoryMap(
    productIds: number[],
  ): Promise<Map<number, { price: number; effectiveAt: Date }[]>> {
    if (productIds.length === 0) return new Map();
    const histories = await this.prisma.productPriceHistory.findMany({
      where: { productId: { in: productIds } },
      orderBy: { effectiveAt: 'asc' },
    });
    const map = new Map<number, { price: number; effectiveAt: Date }[]>();
    for (const h of histories) {
      const arr = map.get(h.productId) ?? [];
      arr.push({ price: h.price.toNumber(), effectiveAt: h.effectiveAt });
      map.set(h.productId, arr);
    }
    return map;
  }

  async findByDate(branchId: number, date: string) {
    const rows = await this.prisma.inventory.findMany({
      where: {
        branchId,
        date: toUtcDay(date),
        deletedAt: null,
      },
      orderBy: [
        { product: { type: 'asc' } },
        { product: { sortOrder: 'asc' } },
        { product: { name: 'asc' } },
      ],
      include: {
        product: true,
        adjustments: {
          where: { deletedAt: null },
          orderBy: { createdAt: 'asc' },
        },
      },
    });
    const historyMap = await this.fetchHistoryMap([
      ...new Set(rows.map((r) => r.productId)),
    ]);
    return rows.map((r) => ({
      ...r,
      effectivePrice: getEffectivePrice(
        r.productId,
        r.date,
        Number(r.product.price),
        historyMap,
      ),
    }));
  }

  async findByBranchDateRange(
    branchId: number,
    startDate: string,
    endDate?: string,
  ) {
    const start = toUtcDay(startDate);
    const end = endDate ? toUtcDay(endDate) : start;
    assertDateRange(start, end);

    const rows = await this.prisma.inventory.findMany({
      where: {
        branchId,
        date:
          start.getTime() === end.getTime() ? start : { gte: start, lte: end },
        deletedAt: null,
      },
      orderBy: [
        { date: 'asc' },
        { product: { type: 'asc' } },
        { product: { sortOrder: 'asc' } },
        { product: { name: 'asc' } },
      ],
      include: {
        product: true,
        adjustments: {
          where: { deletedAt: null },
          orderBy: { createdAt: 'asc' },
        },
      },
    });
    const historyMap = await this.fetchHistoryMap([
      ...new Set(rows.map((r) => r.productId)),
    ]);
    return rows.map((r) => ({
      ...r,
      effectivePrice: getEffectivePrice(
        r.productId,
        r.date,
        Number(r.product.price),
        historyMap,
      ),
    }));
  }

  async findByDateAllBranches(
    startDate?: string,
    endDate?: string,
    branchId?: number,
  ) {
    const start = startDate ? toUtcDay(startDate) : undefined;
    const end = endDate ? toUtcDay(endDate) : start;
    if (start && end) assertDateRange(start, end);
    const dateFilter = start
      ? start.getTime() === end?.getTime()
        ? { date: start }
        : { date: { gte: start, lte: end } }
      : {};
    const rows = await this.prisma.inventory.findMany({
      where: {
        ...dateFilter,
        deletedAt: null,
        ...(branchId != null ? { branchId } : {}),
      },
      orderBy: [
        { branchId: 'asc' },
        { date: 'asc' },
        { product: { type: 'asc' } },
        { product: { sortOrder: 'asc' } },
        { product: { name: 'asc' } },
      ],
      include: {
        branch: true,
        product: true,
        adjustments: {
          where: { deletedAt: null },
          orderBy: { createdAt: 'asc' },
        },
      },
    });
    const historyMap = await this.fetchHistoryMap([
      ...new Set(rows.map((r) => r.productId)),
    ]);
    return rows.map((r) => ({
      ...r,
      effectivePrice: getEffectivePrice(
        r.productId,
        r.date,
        Number(r.product.price),
        historyMap,
      ),
    }));
  }

  async findOne(id: number, branchId?: number) {
    const inventory = await this.prisma.inventory.findFirst({
      where: { id, deletedAt: null, ...(branchId != null ? { branchId } : {}) },
      include: {
        branch: true,
        product: true,
        adjustments: {
          where: { deletedAt: null },
          orderBy: { createdAt: 'asc' },
        },
      },
    });
    if (!inventory) {
      throw new NotFoundException('Inventory record not found');
    }
    return inventory;
  }

  async update(
    id: number,
    body: UpdateInventoryDto,
    branchId?: number,
    userId?: number,
  ) {
    const existing = await this.prisma.inventory.findFirst({
      where: { id, deletedAt: null, ...(branchId != null ? { branchId } : {}) },
      include: { adjustments: { where: { deletedAt: null } } },
    });
    if (!existing) throw new NotFoundException('Inventory record not found');

    // Validate the row as it will be *after* the merge, not the fields in
    // isolation: raising delivery and leftover together is legitimate.
    this.assertRowIsPossible({
      quantity: body.quantity ?? existing.quantity,
      delivery: body.delivery ?? existing.delivery,
      leftover: body.leftover ?? existing.leftover,
      reject: body.reject ?? existing.reject,
      adjustments: existing.adjustments,
    });

    const leftoverChanged =
      body.leftover !== undefined && body.leftover !== existing.leftover;

    const updated = await this.prisma.inventory.update({
      where: { id },
      data: {
        // No branch/product/date: the DTO does not carry them, because
        // re-keying a row is not an edit. See UpdateInventoryDto.
        quantity: body.quantity,
        delivery: body.delivery,
        leftover: body.leftover,
        reject: body.reject,
        notes: body.notes,
        // Always flip to manually-entered when a user edits a row
        isAutoGenerated: false,
        updatedById: userId ?? null,
      },
      include: { branch: true, product: true },
    });

    // Auto-recascade downstream auto-generated rows when leftover changes so
    // they don't need a separate manual recascade call.
    if (leftoverChanged) {
      const fromDate = updated.date.toISOString().slice(0, 10);
      const { updated: cascadeUpdated } = await this.recascadeLeftovers(
        updated.branchId,
        updated.productId,
        fromDate,
      );
      return { ...updated, cascadeWarning: 0, cascadeUpdated };
    }

    // Leftover unchanged — still warn if downstream stale rows exist.
    const cascadeWarning = await this.prisma.inventory.count({
      where: {
        branchId: updated.branchId,
        productId: updated.productId,
        date: { gt: updated.date },
        isAutoGenerated: true,
        deletedAt: null,
      },
    });

    return { ...updated, cascadeWarning, cascadeUpdated: 0 };
  }

  /**
   * Apply a whole sheet's worth of edits in one request.
   *
   * The sheet used to send one PATCH per edited row. Two things break at scale:
   * the global 20-requests-per-minute throttle rejects everything past the
   * twentieth row, and `Promise.all` rejects on the first failure, so the user
   * is told the save failed while some rows did land.
   *
   * Round trips matter more than statements here — the database is
   * cross-region, ~300ms per statement — so this is written to be a fixed
   * number of round trips regardless of row count: one read, one batched
   * transaction of updates, one read of downstream rows, one batched
   * transaction of cascades. Prisma pipelines an array `$transaction` into a
   * single round trip, which is what makes that possible.
   */
  async updateBulk(
    items: UpdateInventoryItemDto[],
    branchId?: number,
    userId?: number,
  ) {
    if (items.length === 0)
      return { updated: 0, cascadeUpdated: 0, cascadeWarnings: [] };

    const ids = items.map((i) => i.id);
    const existing = await this.prisma.inventory.findMany({
      where: {
        id: { in: ids },
        deletedAt: null,
        ...(branchId != null ? { branchId } : {}),
      },
      select: {
        id: true,
        branchId: true,
        productId: true,
        date: true,
        quantity: true,
        delivery: true,
        leftover: true,
        reject: true,
        adjustments: {
          where: { deletedAt: null },
          select: { type: true, value: true },
        },
      },
    });

    // All-or-nothing. A partial save is exactly the failure mode this replaces,
    // and a row missing from a branch-scoped read is one the caller may not touch.
    if (existing.length !== ids.length) {
      const found = new Set(existing.map((r) => r.id));
      const missing = ids.filter((id) => !found.has(id));
      throw new NotFoundException(
        `Inventory rows not found or outside your branch: ${missing.join(', ')}`,
      );
    }

    const byId = new Map(existing.map((r) => [r.id, r]));

    // Validate the whole batch before writing any of it — a partial save is
    // exactly what this endpoint exists to prevent.
    for (const item of items) {
      const row = byId.get(item.id)!;
      this.assertRowIsPossible({
        quantity: item.quantity ?? row.quantity,
        delivery: item.delivery ?? row.delivery,
        leftover: item.leftover ?? row.leftover,
        reject: item.reject ?? row.reject,
        adjustments: row.adjustments,
      });
    }

    await this.prisma.$transaction(
      items.map((item) =>
        this.prisma.inventory.update({
          where: { id: item.id },
          data: {
            quantity: item.quantity,
            delivery: item.delivery,
            leftover: item.leftover,
            reject: item.reject,
            notes: item.notes,
            // Matches update(): a user-edited row is no longer a placeholder.
            isAutoGenerated: false,
            updatedById: userId ?? null,
          },
        }),
      ),
    );

    // Rows whose leftover moved carry forward; the rest are only checked for
    // downstream placeholders still derived from an older number.
    const seeds: Array<{ row: SheetRow; leftover: number }> = [];
    const unchanged: SheetRow[] = [];
    for (const item of items) {
      const row = byId.get(item.id)!;
      if (item.leftover !== undefined && item.leftover !== row.leftover) {
        seeds.push({ row, leftover: item.leftover });
      } else {
        unchanged.push(row);
      }
    }

    const { cascadeUpdated, cascadeWarnings } = await this.cascadeMany(
      seeds,
      unchanged,
    );

    return { updated: items.length, cascadeUpdated, cascadeWarnings };
  }

  /**
   * Batched equivalent of recascadeLeftovers for many seed rows at once.
   *
   * Same rule as the single-row version: walk forward through contiguous
   * auto-generated rows and stop at the first manually-entered one, because a
   * manual entry is an authoritative boundary. Rows sharing a target value are
   * collapsed into one updateMany so the statement count tracks distinct
   * leftovers rather than edited products.
   */
  private async cascadeMany(
    seeds: Array<{ row: SheetRow; leftover: number }>,
    unchanged: SheetRow[] = [],
  ): Promise<{ cascadeUpdated: number; cascadeWarnings: CascadeWarning[] }> {
    const all = [...seeds.map((s) => s.row), ...unchanged];
    if (all.length === 0) return { cascadeUpdated: 0, cascadeWarnings: [] };

    const branchIds = [...new Set(all.map((r) => r.branchId))];
    const productIds = [...new Set(all.map((r) => r.productId))];
    const earliest = new Date(Math.min(...all.map((r) => r.date.getTime())));

    const downstream = await this.prisma.inventory.findMany({
      where: {
        branchId: { in: branchIds },
        productId: { in: productIds },
        date: { gt: earliest },
        deletedAt: null,
      },
      orderBy: { date: 'asc' },
      select: {
        id: true,
        branchId: true,
        productId: true,
        date: true,
        isAutoGenerated: true,
        delivery: true,
        adjustments: {
          where: { deletedAt: null },
          select: { type: true, value: true },
        },
      },
    });

    const byPair = new Map<string, typeof downstream>();
    for (const row of downstream) {
      const key = `${row.branchId}-${row.productId}`;
      const list = byPair.get(key) ?? [];
      list.push(row);
      byPair.set(key, list);
    }

    // Each placeholder opens on the previous balance and closes on that plus
    // whatever landed on it, so the values differ per row — see
    // buildCarryForward, which this shares with the single-row cascade.
    const writes: Array<{ id: number; quantity: number; leftover: number }> = [];
    for (const seed of seeds) {
      const key = `${seed.row.branchId}-${seed.row.productId}`;
      const after = (byPair.get(key) ?? []).filter(
        (r) => r.date > seed.row.date,
      );
      writes.push(...this.buildCarryForward(seed.leftover, after));
    }

    // A row the user did not re-count, but whose later days are still
    // placeholders carried from an older leftover. update() reported this as
    // cascadeWarning and offered an explicit recascade; so does this.
    const cascadeWarnings: CascadeWarning[] = [];
    for (const row of unchanged) {
      const rest = byPair.get(`${row.branchId}-${row.productId}`) ?? [];
      const hasStale = rest.some(
        (r) => r.date > row.date && r.isAutoGenerated,
      );
      if (hasStale) {
        cascadeWarnings.push({
          branchId: row.branchId,
          productId: row.productId,
          fromDate: row.date.toISOString().slice(0, 10),
        });
      }
    }

    if (writes.length === 0) return { cascadeUpdated: 0, cascadeWarnings };

    await this.prisma.$transaction(
      writes.map(({ id, quantity, leftover }) =>
        this.prisma.inventory.update({
          where: { id },
          data: { quantity, leftover },
        }),
      ),
    );

    return { cascadeUpdated: writes.length, cascadeWarnings };
  }

  async remove(id: number, branchId?: number) {
    const existing = await this.prisma.inventory.findFirst({
      where: { id, deletedAt: null, ...(branchId != null ? { branchId } : {}) },
    });
    if (!existing) throw new NotFoundException('Inventory record not found');
    return this.prisma.inventory.update({
      where: { id },
      data: { deletedAt: new Date() },
    });
  }

  getSummary(branchId: number | null, startDate?: string, endDate?: string) {
    return this.cache.wrap(
      CACHE_NS.INVENTORY_AGG,
      ['summary', branchId ?? 'all', startDate ?? '', endDate ?? ''],
      () => this.getSummaryUncached(branchId, startDate, endDate),
    );
  }

  private async getSummaryUncached(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
  ) {
    const today = this.localToday();
    const start = startDate ? toUtcDay(startDate) : today;
    const end = endDate ? toUtcDay(endDate) : start;
    assertDateRange(start, end);

    const rows = await this.prisma.inventory.findMany({
      where: {
        deletedAt: null,
        date:
          start.getTime() === end.getTime() ? start : { gte: start, lte: end },
        ...(branchId != null ? { branchId } : {}),
      },
      include: {
        adjustments: { where: { deletedAt: null } },
        product: { select: { id: true, type: true, price: true, name: true } },
      },
    });

    if (rows.length === 0) {
      return {
        totalRevenue: 0,
        totalSold: 0,
        totalDelivery: 0,
        totalLeftover: 0,
        totalReject: 0,
        revenueByType: { BREAD: 0, CAKE: 0, SPECIAL: 0, MISCELLANEOUS: 0 },
        topProduct: null,
        zeroSales: [] as { productId: number; name: string; revenue: number; sold: number }[],
      };
    }

    const productIds = [...new Set(rows.map((r) => r.productId))];
    const historyByProduct = await this.fetchHistoryMap(productIds);
    const {
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      revenueByProduct,
    } = this.aggregateInventoryMetrics(rows, historyByProduct);

    const sorted = Array.from(revenueByProduct.values()).sort(
      (a, b) => b.revenue - a.revenue,
    );

    return {
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      topProduct: sorted[0] ?? null,
      zeroSales: sorted.filter((r) => r.sold <= 0),
    };
  }

  getDashboard(branchId: number | null, startDate?: string, endDate?: string) {
    return this.cache.wrap(
      CACHE_NS.INVENTORY_AGG,
      ['dashboard', branchId ?? 'all', startDate ?? '', endDate ?? ''],
      () => this.getDashboardUncached(branchId, startDate, endDate),
    );
  }

  private async getDashboardUncached(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
  ) {
    const today = this.localToday();
    const start = startDate ? toUtcDay(startDate) : today;
    const end = endDate ? toUtcDay(endDate) : start;
    assertDateRange(start, end);

    const rows = await this.prisma.inventory.findMany({
      where: {
        deletedAt: null,
        date:
          start.getTime() === end.getTime() ? start : { gte: start, lte: end },
        ...(branchId ? { branchId } : {}),
      },
      orderBy: { date: 'asc' },
      include: {
        adjustments: { where: { deletedAt: null } },
        product: { select: { id: true, type: true, price: true, name: true } },
      },
    });

    const isRange = start.getTime() !== end.getTime();
    const dateRange = {
      startDate: start.toISOString().slice(0, 10),
      endDate: end.toISOString().slice(0, 10),
    };

    if (rows.length === 0) {
      return {
        dateRange,
        isRange,
        totalRevenue: 0,
        totalSold: 0,
        totalDelivery: 0,
        totalLeftover: 0,
        totalReject: 0,
        revenueByType: { BREAD: 0, CAKE: 0, SPECIAL: 0, MISCELLANEOUS: 0 },
        topProduct: null,
        zeroSales: [] as { productId: number; name: string; revenue: number; sold: number }[],
        dailyBreakdown: [] as {
          date: string;
          revenue: number;
          sold: number;
          delivery: number;
          leftover: number;
        }[],
      };
    }

    const productIds = [...new Set(rows.map((r) => r.productId))];
    const historyByProduct = await this.fetchHistoryMap(productIds);
    const {
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      revenueByProduct,
    } = this.aggregateInventoryMetrics(rows, historyByProduct);

    // Daily breakdown (dashboard-only) — single additional pass
    const dailyMap = new Map<
      string,
      { revenue: number; sold: number; delivery: number; leftover: number }
    >();
    for (const inv of rows) {
      const sold = computeSold(inv);
      const effectivePrice = getEffectivePrice(
        inv.productId,
        inv.date,
        Number(inv.product.price),
        historyByProduct,
      );
      const revenue = sold * effectivePrice;
      const dk = inv.date.toISOString().slice(0, 10);
      const day = dailyMap.get(dk) ?? {
        revenue: 0,
        sold: 0,
        delivery: 0,
        leftover: 0,
      };
      dailyMap.set(dk, {
        revenue: day.revenue + revenue,
        sold: day.sold + sold,
        delivery: day.delivery + inv.delivery,
        leftover: day.leftover + inv.leftover,
      });
    }

    const sorted = Array.from(revenueByProduct.values()).sort(
      (a, b) => b.revenue - a.revenue,
    );
    const dailyBreakdown = Array.from(dailyMap.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, v]) => ({ date, ...v }));

    return {
      dateRange,
      isRange,
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      topProduct: sorted[0] ?? null,
      zeroSales: sorted.filter((r) => r.sold <= 0),
      dailyBreakdown,
    };
  }

  async exportSalesCsv(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
  ): Promise<string> {
    const data = await this.getDashboard(branchId, startDate, endDate);
    const lines: string[] = [];

    lines.push('Sales Report');
    lines.push(
      `Period,${data.dateRange.startDate} to ${data.dateRange.endDate}`,
    );
    lines.push('');
    lines.push('SUMMARY');
    lines.push(`Total Revenue,${Number(data.totalRevenue).toFixed(2)}`);
    lines.push(`Total Sold,${data.totalSold}`);
    lines.push(`Total Delivered,${data.totalDelivery}`);
    lines.push(`Total Leftover,${data.totalLeftover}`);
    lines.push(`Total Reject,${data.totalReject}`);
    lines.push('');
    lines.push('REVENUE BY PRODUCT TYPE');
    lines.push('Type,Revenue');
    for (const [type, revenue] of Object.entries(data.revenueByType)) {
      lines.push(`${type},${Number(revenue).toFixed(2)}`);
    }
    if (data.topProduct) {
      lines.push('');
      lines.push('TOP PRODUCT');
      lines.push(`Name,Sold,Revenue`);
      lines.push(
        `${csvField(data.topProduct.name)},${data.topProduct.sold},${Number(data.topProduct.revenue).toFixed(2)}`,
      );
    }
    if (data.dailyBreakdown.length > 0) {
      lines.push('');
      lines.push('DAILY BREAKDOWN');
      lines.push('Date,Revenue,Sold,Delivery,Leftover');
      for (const d of data.dailyBreakdown) {
        lines.push(
          `${d.date},${Number(d.revenue).toFixed(2)},${d.sold},${d.delivery},${d.leftover}`,
        );
      }
    }
    if (data.zeroSales.length > 0) {
      lines.push('');
      lines.push('ZERO SALES PRODUCTS');
      lines.push('Product,Sold,Revenue');
      for (const z of data.zeroSales) {
        lines.push(
          `${csvField(z.name)},${z.sold},${Number(z.revenue).toFixed(2)}`,
        );
      }
    }

    return lines.join('\r\n');
  }

  /**
   * Return all branch × product × date combos that have no Inventory entry
   * within the given date range. Limited to 31 days to prevent huge payloads.
   */
  getGaps(branchId: number | null, startDate: string, endDate: string) {
    return this.cache.wrap(
      CACHE_NS.INVENTORY_AGG,
      ['gaps', branchId ?? 'all', startDate, endDate],
      () => this.getGapsUncached(branchId, startDate, endDate),
    );
  }

  private async getGapsUncached(
    branchId: number | null,
    startDate: string,
    endDate: string,
  ) {
    const start = toUtcDay(startDate);
    const end = toUtcDay(endDate);
    assertDateRange(start, end);

    const dates = eachDayInclusive(start, end);

    // Fetch active branches and products
    const [branches, products] = await Promise.all([
      this.prisma.branch.findMany({
        where: {
          deletedAt: null,
          isActive: true,
          ...(branchId ? { id: branchId } : {}),
        },
        select: { id: true, name: true },
      }),
      this.prisma.product.findMany({
        where: { deletedAt: null, isActive: true },
        select: { id: true, name: true },
        orderBy: [{ type: 'asc' }, { sortOrder: 'asc' }, { name: 'asc' }],
      }),
    ]);

    // Fetch existing inventory rows in the range
    const existing = await this.prisma.inventory.findMany({
      where: {
        deletedAt: null,
        date: { gte: start, lte: end },
        ...(branchId ? { branchId } : {}),
      },
      select: { branchId: true, productId: true, date: true },
    });

    // Build a Set of keys for O(1) lookup: "branchId-productId-YYYY-MM-DD"
    const existingKeys = new Set(
      existing.map(
        (r) =>
          `${r.branchId}-${r.productId}-${r.date.toISOString().slice(0, 10)}`,
      ),
    );

    const missing: {
      branchId: number;
      branchName: string;
      productId: number;
      productName: string;
      date: string;
    }[] = [];
    for (const branch of branches) {
      for (const product of products) {
        for (const date of dates) {
          const key = `${branch.id}-${product.id}-${date.toISOString().slice(0, 10)}`;
          if (!existingKeys.has(key)) {
            missing.push({
              branchId: branch.id,
              branchName: branch.name,
              productId: product.id,
              productName: product.name,
              date: date.toISOString().slice(0, 10),
            });
          }
        }
      }
    }

    return { missing, total: missing.length };
  }

  /**
   * Walk forward from fromDate through contiguous auto-generated rows, carrying
   * each day's closing balance into the next. Stops at the first
   * manually-entered row, which is an authoritative boundary.
   *
   * This used to write one flat `seed.leftover` to every downstream row with a
   * single updateMany. That is only right while a placeholder has no delivery
   * and no adjustments — but a delivery can land on a day nobody entered, and a
   * transfer can be booked against one, and the flat write silently discarded
   * both. Nothing is sold on a placeholder day, so its closing balance is
   * simply everything it had on hand.
   */
  async recascadeLeftovers(
    branchId: number,
    productId: number,
    fromDate: string,
  ) {
    const seed = await this.prisma.inventory.findFirst({
      where: {
        branchId,
        productId,
        date: toUtcDay(fromDate),
        deletedAt: null,
      },
    });
    if (!seed) throw new NotFoundException('Source inventory row not found');

    // Fetch ALL subsequent rows (auto and manual) and stop at the first manually-entered
    // row, since a manual entry is an authoritative boundary the cascade must not cross.
    const allSubsequent = await this.prisma.inventory.findMany({
      where: { branchId, productId, date: { gt: seed.date }, deletedAt: null },
      orderBy: { date: 'asc' },
      select: {
        id: true,
        isAutoGenerated: true,
        delivery: true,
        adjustments: {
          where: { deletedAt: null },
          select: { type: true, value: true },
        },
      },
    });

    const writes = this.buildCarryForward(seed.leftover, allSubsequent);
    if (writes.length === 0) return { updated: 0 };

    await this.prisma.$transaction(
      writes.map(({ id, quantity, leftover }) =>
        this.prisma.inventory.update({
          where: { id },
          data: { quantity, leftover },
        }),
      ),
    );

    return { updated: writes.length };
  }

  /**
   * Roll a closing balance forward through contiguous placeholder rows.
   *
   * Each row opens on the previous balance and closes on that plus whatever it
   * received — a delivery, a transfer — because a placeholder is a day nobody
   * recorded a sale on. Stops at the first manual row.
   */
  private buildCarryForward(
    openingBalance: number,
    subsequent: Array<{
      id: number;
      isAutoGenerated: boolean;
      delivery: number;
      adjustments: Array<{ type: string; value: number }>;
    }>,
  ): Array<{ id: number; quantity: number; leftover: number }> {
    const writes: Array<{ id: number; quantity: number; leftover: number }> = [];
    let running = openingBalance;
    for (const row of subsequent) {
      if (!row.isAutoGenerated) break;
      const closing = running + row.delivery + computeAdjSum(row.adjustments);
      writes.push({ id: row.id, quantity: running, leftover: closing });
      running = closing;
    }
    return writes;
  }

  getRejectionByProduct(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
    type?: ProductType,
  ) {
    return this.cache.wrap(
      CACHE_NS.INVENTORY_AGG,
      [
        'rejection',
        branchId ?? 'all',
        startDate ?? '',
        endDate ?? '',
        type ?? 'all',
      ],
      () =>
        this.getRejectionByProductUncached(branchId, startDate, endDate, type),
    );
  }

  private async getRejectionByProductUncached(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
    type?: ProductType,
  ) {
    const today = this.localToday();
    const start = startDate ? toUtcDay(startDate) : today;
    const end = endDate ? toUtcDay(endDate) : start;
    assertDateRange(start, end, MAX_REPORT_RANGE_DAYS);

    // Step 1: resolve qualifying products (excludes soft-deleted products).
    const products = await this.prisma.product.findMany({
      where: { deletedAt: null, ...(type ? { type } : {}) },
      select: { id: true, name: true, type: true },
    });

    if (products.length === 0) return [];

    const productIds = products.map((p) => p.id);

    // Step 2: aggregate in the database rather than in application memory.
    const grouped = await this.prisma.inventory.groupBy({
      by: ['productId'],
      where: {
        deletedAt: null,
        productId: { in: productIds },
        date:
          start.getTime() === end.getTime() ? start : { gte: start, lte: end },
        ...(branchId ? { branchId } : {}),
      },
      _sum: { delivery: true, reject: true },
    });

    const productMap = new Map(products.map((p) => [p.id, p]));

    return grouped
      .map((row) => {
        const product = productMap.get(row.productId)!;
        const totalDelivery = row._sum.delivery ?? 0;
        const totalReject = row._sum.reject ?? 0;
        return {
          productId: row.productId,
          name: product.name,
          type: product.type,
          totalDelivery,
          totalReject,
          rejectRate:
            totalDelivery > 0 ? (totalReject / totalDelivery) * 100 : 0,
        };
      })
      .sort((a, b) => b.totalReject - a.totalReject);
  }
}
