import { NotFoundException } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { InventoryService } from './inventory.service';
import { PrismaService } from '../prisma/prisma.service';
import { CacheNamespaceService } from '../common/cache/cache-namespace.service';

// ---------------------------------------------------------------------------
// Minimal Prisma mock factory
// ---------------------------------------------------------------------------

function makePrisma() {
  return {
    inventory: {
      findFirst: jest.fn(),
      findUnique: jest.fn(),
      findMany: jest.fn(),
      update: jest.fn(),
      updateMany: jest.fn(),
      count: jest.fn(),
      upsert: jest.fn(),
      delete: jest.fn(),
    },
    productPriceHistory: {
      findMany: jest.fn(),
    },
    branch: { findMany: jest.fn() },
    product: { findMany: jest.fn() },
    $transaction: jest.fn(),
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeInvRow(
  overrides: Partial<{
    id: number;
    branchId: number;
    productId: number;
    date: Date;
    quantity: number;
    delivery: number;
    leftover: number;
    reject: number;
    isAutoGenerated: boolean;
    adjustments: { type: string; value: number }[];
    product: { id: number; type: string; price: number; name: string };
  }> = {},
) {
  return {
    id: 1,
    branchId: 1,
    productId: 1,
    date: new Date('2024-01-01'),
    quantity: 100,
    delivery: 0,
    leftover: 20,
    reject: 0,
    isAutoGenerated: true,
    adjustments: [],
    product: { id: 1, type: 'BREAD', price: 10, name: 'Pandesal' },
    ...overrides,
  };
}

function makeCache() {
  const store = new Map<string, unknown>();
  return {
    store,
    wrap: jest.fn(
      async (
        ns: string,
        parts: (string | number)[],
        fn: () => Promise<unknown>,
      ) => {
        const key = `${ns}:${parts.join(':')}`;
        if (store.has(key)) return store.get(key);
        const val = await fn();
        store.set(key, val);
        return val;
      },
    ),
    bump: jest.fn((ns: string) => {
      for (const k of [...store.keys()])
        if (k.startsWith(`${ns}:`)) store.delete(k);
    }),
  };
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('InventoryService', () => {
  let service: InventoryService;
  let prisma: ReturnType<typeof makePrisma>;
  let cache: ReturnType<typeof makeCache>;

  beforeEach(async () => {
    prisma = makePrisma();
    cache = makeCache();
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        InventoryService,
        { provide: PrismaService, useValue: prisma },
        { provide: CacheNamespaceService, useValue: cache },
      ],
    }).compile();

    service = module.get<InventoryService>(InventoryService);
  });

  afterEach(() => jest.clearAllMocks());

  // ─────────────────────────────────────────────────────────────────────────
  // recascadeLeftovers
  // ─────────────────────────────────────────────────────────────────────────

  describe('recascadeLeftovers', () => {
    it('throws NotFoundException when the seed row does not exist', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(
        service.recascadeLeftovers(1, 1, '2024-01-01'),
      ).rejects.toThrow(NotFoundException);
    });

    it('returns { updated: 0 } when there are no subsequent auto-generated rows', async () => {
      prisma.inventory.findFirst.mockResolvedValue(
        makeInvRow({ leftover: 30 }),
      );
      prisma.inventory.findMany.mockResolvedValue([]);

      const result = await service.recascadeLeftovers(1, 1, '2024-01-01');

      expect(result).toEqual({ updated: 0 });
      expect(prisma.inventory.update).not.toHaveBeenCalled();
    });

    it('propagates the seed leftover to all subsequent auto-generated rows', async () => {
      const seed = makeInvRow({ leftover: 30, date: new Date('2024-01-01') });
      const day2 = makeInvRow({
        id: 2,
        date: new Date('2024-01-02'),
        quantity: 10,
        leftover: 10,
        isAutoGenerated: true,
      });
      const day3 = makeInvRow({
        id: 3,
        date: new Date('2024-01-03'),
        quantity: 10,
        leftover: 10,
        isAutoGenerated: true,
      });

      prisma.inventory.findFirst.mockResolvedValue(seed);
      prisma.inventory.findMany.mockResolvedValue([day2, day3]);
      prisma.inventory.updateMany.mockResolvedValue({ count: 2 });

      const result = await service.recascadeLeftovers(1, 1, '2024-01-01');

      expect(result).toEqual({ updated: 2 });
      // both rows are updated in a single updateMany carrying the seed leftover
      expect(prisma.inventory.updateMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: { in: [2, 3] } },
          data: { quantity: 30, leftover: 30 },
        }),
      );
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // getSummary
  // ─────────────────────────────────────────────────────────────────────────

  describe('getSummary', () => {
    it('returns zeroed summary when there are no inventory rows', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.totalRevenue).toBe(0);
      expect(result.totalSold).toBe(0);
      expect(result.topProduct).toBeNull();
      expect(result.zeroSales).toEqual([]);
    });

    it('calculates sold as quantity + delivery + adjSum - leftover', async () => {
      const row = makeInvRow({
        quantity: 50,
        delivery: 20,
        leftover: 10,
        reject: 0,
        adjustments: [{ type: 'PULL_IN', value: 5 }],
        product: { id: 1, type: 'BREAD', price: 10, name: 'Pandesal' },
      });
      prisma.inventory.findMany.mockResolvedValue([row]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      // sold = 50 + 20 + 5 (PULL_IN, positive) - 10 = 65; revenue = 65 * 10 = 650
      expect(result.totalSold).toBe(65);
      expect(result.totalRevenue).toBe(650);
    });

    it('excludes rejects from sold and revenue', async () => {
      const row = makeInvRow({
        quantity: 50,
        delivery: 20,
        leftover: 10,
        reject: 8,
        adjustments: [{ type: 'PULL_IN', value: 5 }],
        product: { id: 1, type: 'BREAD', price: 10, name: 'Pandesal' },
      });
      prisma.inventory.findMany.mockResolvedValue([row]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      // sold = 50 + 20 + 5 - 10 - 8 (reject) = 57; revenue = 57 * 10 = 570
      expect(result.totalSold).toBe(57);
      expect(result.totalRevenue).toBe(570);
    });

    it('accumulates revenue by product type', async () => {
      const bread = makeInvRow({
        productId: 1,
        quantity: 100,
        delivery: 0,
        leftover: 0,
        adjustments: [],
        product: { id: 1, type: 'BREAD', price: 5, name: 'Tasty' },
      });
      const cake = makeInvRow({
        id: 2,
        productId: 2,
        quantity: 10,
        delivery: 0,
        leftover: 0,
        adjustments: [],
        product: { id: 2, type: 'CAKE', price: 100, name: 'Birthday' },
      });
      prisma.inventory.findMany.mockResolvedValue([bread, cake]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.revenueByType['BREAD']).toBe(500);
      expect(result.revenueByType['CAKE']).toBe(1000);
    });

    it('reports zero-sales products correctly', async () => {
      const row = makeInvRow({
        quantity: 0,
        delivery: 0,
        leftover: 0,
        adjustments: [],
        product: { id: 1, type: 'BREAD', price: 10, name: 'Unsold' },
      });
      prisma.inventory.findMany.mockResolvedValue([row]);
      prisma.productPriceHistory.findMany.mockResolvedValue([]);

      const result = await service.getSummary(null, '2024-01-01');

      expect(result.zeroSales).toHaveLength(1);
      expect(result.zeroSales[0].name).toBe('Unsold');
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // update — cascade warning count
  // ─────────────────────────────────────────────────────────────────────────

  describe('update — cascade warning count', () => {
    const baseExisting = makeInvRow({ id: 10, leftover: 20 });
    const baseUpdated = {
      ...makeInvRow({ id: 10 }),
      branchId: 1,
      productId: 1,
      date: new Date('2024-01-01'),
    };

    it('returns cascadeWarning = 0 when leftover is unchanged', async () => {
      prisma.inventory.findFirst.mockResolvedValue({
        ...baseExisting,
        leftover: 20,
      });
      prisma.inventory.update.mockResolvedValue(baseUpdated);
      prisma.inventory.count.mockResolvedValue(0);

      const result = await service.update(10, { leftover: 20 });

      expect(result.cascadeWarning).toBe(0);
      expect(prisma.inventory.count).toHaveBeenCalledTimes(1);
    });

    it('returns cascadeWarning > 0 when downstream auto-generated rows exist and leftover is unchanged', async () => {
      prisma.inventory.findFirst.mockResolvedValue({
        ...baseExisting,
        leftover: 20,
      });
      prisma.inventory.update.mockResolvedValue(baseUpdated);
      prisma.inventory.count.mockResolvedValue(3);

      const result = await service.update(10, { leftover: 20 });

      expect(result.cascadeWarning).toBe(3);
    });

    it('auto-cascades and returns cascadeWarning = 0 when leftover changes', async () => {
      prisma.inventory.findFirst
        .mockResolvedValueOnce({ ...baseExisting, leftover: 20 }) // update() lookup
        .mockResolvedValueOnce(baseUpdated); // recascadeLeftovers seed lookup
      prisma.inventory.update.mockResolvedValue(baseUpdated);
      prisma.inventory.findMany.mockResolvedValue([]); // no subsequent rows

      const result = await service.update(10, { leftover: 35 });

      // When leftover changes, recascade runs; cascadeWarning is always 0 in that branch
      expect(result.cascadeWarning).toBe(0);
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Branch scoping (#2) — managers must not read/modify other branches
  // ─────────────────────────────────────────────────────────────────────────

  describe('branch scoping', () => {
    it('findAll filters by branchId when a scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.findAll(1, 50, 7);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('findAll does not filter by branch when no scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.findAll(1, 50);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({ where: { deletedAt: null } }),
      );
    });

    it('search filters by branchId when a scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.search('pan', 1, 50, 7);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: expect.objectContaining({ branchId: 7 }),
        }),
      );
    });

    it('findByProduct filters by branchId when a scope is provided', async () => {
      prisma.$transaction.mockResolvedValue([[], 0]);

      await service.findByProduct(3, 1, 50, 7);

      expect(prisma.inventory.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { productId: 3, deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('findOne includes the branch scope in its where clause', async () => {
      prisma.inventory.findFirst.mockResolvedValue(makeInvRow());

      await service.findOne(10, 7);

      expect(prisma.inventory.findFirst).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 10, deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('findOne throws NotFound when the row is outside the branch scope', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(service.findOne(10, 7)).rejects.toThrow(NotFoundException);
    });

    it('update scopes its existence check to the branch', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(service.update(10, { leftover: 5 }, 7)).rejects.toThrow(
        NotFoundException,
      );
      expect(prisma.inventory.findFirst).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 10, deletedAt: null, branchId: 7 },
        }),
      );
    });

    it('remove scopes its existence check to the branch', async () => {
      prisma.inventory.findFirst.mockResolvedValue(null);

      await expect(service.remove(10, 7)).rejects.toThrow(NotFoundException);
      expect(prisma.inventory.findFirst).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 10, deletedAt: null, branchId: 7 },
        }),
      );
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Aggregation caching (Task 4)
  // ─────────────────────────────────────────────────────────────────────────

  describe('aggregation caching', () => {
    it('getSummary computes once, then serves from cache for identical args', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await service.getSummary(1, '2024-01-01', '2024-01-01');
      await service.getSummary(1, '2024-01-01', '2024-01-01');

      expect(prisma.inventory.findMany).toHaveBeenCalledTimes(1);
    });

    it('getSummary recomputes after the inventory namespace is bumped', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await service.getSummary(1, '2024-01-01', '2024-01-01');
      cache.bump('inventory-agg');
      await service.getSummary(1, '2024-01-01', '2024-01-01');

      expect(prisma.inventory.findMany).toHaveBeenCalledTimes(2);
    });

    it('getSummary caches per-branch/date (different args miss separately)', async () => {
      prisma.inventory.findMany.mockResolvedValue([]);

      await service.getSummary(1, '2024-01-01', '2024-01-01');
      await service.getSummary(2, '2024-01-01', '2024-01-01');

      expect(prisma.inventory.findMany).toHaveBeenCalledTimes(2);
    });
  });
});
