import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma, ProductType } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { getEffectivePrice } from '../common/utils/price-history.util';
import { computeSold } from '../common/utils/inventory-metrics.util';
import { csvField } from '../common/utils/csv.util';
import { CreateInventoryDto } from './dto/create-inventory.dto';
import { UpdateInventoryDto } from './dto/update-inventory.dto';
import { CacheNamespaceService } from '../common/cache/cache-namespace.service';
import { CACHE_NS } from '../common/cache/cache-namespaces';

@Injectable()
export class InventoryService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly cache: CacheNamespaceService,
  ) {}

  /**
   * Returns today's calendar date as a UTC-midnight Date, resolved in Manila.
   *
   * This used to read the process timezone via `TZ=Asia/Manila`, which worked
   * on Cloud Run. **Vercel reserves `TZ` and refuses to set it**, so functions
   * always run UTC — and under UTC every call from 16:00–23:59 UTC, which is
   * **00:00–08:00 in Manila**, returned the *previous* date. That window is the
   * early-morning baking shift, so it would have been wrong precisely when the
   * inventory sheets are first opened each day.
   *
   * Pinning the zone explicitly is the only portable fix, and it matches what
   * jobs.service, autofill-on-demand, and suggestions.service already do.
   */
  private localToday(): Date {
    const str = new Intl.DateTimeFormat('en-CA', {
      timeZone: 'Asia/Manila',
    }).format(new Date());
    return new Date(`${str}T00:00:00.000Z`);
  }

  private validateDateRange(start: Date, end: Date, maxDays = 31): void {
    const diffDays = Math.floor(
      (end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24),
    );
    if (diffDays < 0)
      throw new BadRequestException('endDate must be on or after startDate');
    if (diffDays >= maxDays)
      throw new BadRequestException(`Date range cannot exceed ${maxDays} days`);
  }

  async create(body: CreateInventoryDto, userId?: number) {
    // Upsert: if a record for the same branch+product+date exists, update it
    return this.prisma.inventory.upsert({
      where: {
        branchId_productId_date: {
          branchId: body.branchId,
          productId: body.productId,
          date: new Date(body.date),
        },
      },
      update: {
        quantity: body.quantity,
        delivery: body.delivery,
        leftover: body.leftover,
        reject: body.reject,
        notes: body.notes,
        isAutoGenerated: false,
      },
      create: {
        branchId: body.branchId,
        productId: body.productId,
        date: new Date(body.date),
        quantity: body.quantity,
        delivery: body.delivery,
        leftover: body.leftover,
        reject: body.reject,
        notes: body.notes,
        isAutoGenerated: false,
        createdById: userId,
      },
      include: {
        branch: true,
        product: true,
      },
    });
  }

  async createBulk(items: CreateInventoryDto[], userId?: number) {
    return this.prisma.$transaction(
      items.map((item) =>
        this.prisma.inventory.upsert({
          where: {
            branchId_productId_date: {
              branchId: item.branchId,
              productId: item.productId,
              date: new Date(item.date),
            },
          },
          update: {
            quantity: item.quantity,
            delivery: item.delivery,
            leftover: item.leftover,
            reject: item.reject,
            notes: item.notes,
            isAutoGenerated: false,
          },
          create: {
            branchId: item.branchId,
            productId: item.productId,
            date: new Date(item.date),
            quantity: item.quantity,
            delivery: item.delivery,
            leftover: item.leftover,
            reject: item.reject,
            notes: item.notes,
            isAutoGenerated: false,
            createdById: userId,
          },
        }),
      ),
    );
  }

  async findAll(page = 1, limit = 50, branchId?: number) {
    const skip = (page - 1) * limit;
    const where = {
      deletedAt: null,
      ...(branchId != null ? { branchId } : {}),
    };
    const [data, total] = await this.prisma.$transaction([
      this.prisma.inventory.findMany({
        where,
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: { branch: true, product: true },
      }),
      this.prisma.inventory.count({ where }),
    ]);
    return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  async search(q: string, page = 1, limit = 50, branchId?: number) {
    const skip = (page - 1) * limit;
    const where = {
      deletedAt: null,
      ...(branchId != null ? { branchId } : {}),
      OR: [
        { notes: { contains: q, mode: Prisma.QueryMode.insensitive } },
        {
          branch: { name: { contains: q, mode: Prisma.QueryMode.insensitive } },
        },
        {
          product: {
            name: { contains: q, mode: Prisma.QueryMode.insensitive },
          },
        },
      ],
    };
    const [data, total] = await this.prisma.$transaction([
      this.prisma.inventory.findMany({
        where,
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: { branch: true, product: true },
      }),
      this.prisma.inventory.count({ where }),
    ]);
    return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  async findByBranch(branchId: number, page = 1, limit = 50) {
    const skip = (page - 1) * limit;
    const where = { branchId, deletedAt: null };
    const [data, total] = await this.prisma.$transaction([
      this.prisma.inventory.findMany({
        where,
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: { product: true },
      }),
      this.prisma.inventory.count({ where }),
    ]);
    return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  async findByProduct(
    productId: number,
    page = 1,
    limit = 50,
    branchId?: number,
  ) {
    const skip = (page - 1) * limit;
    const where = {
      productId,
      deletedAt: null,
      ...(branchId != null ? { branchId } : {}),
    };
    const [data, total] = await this.prisma.$transaction([
      this.prisma.inventory.findMany({
        where,
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: { branch: true },
      }),
      this.prisma.inventory.count({ where }),
    ]);
    return { data, total, page, limit, totalPages: Math.ceil(total / limit) };
  }

  private aggregateInventoryMetrics(
    rows: Array<{
      productId: number;
      date: Date;
      quantity: number;
      delivery: number;
      leftover: number;
      reject: number;
      adjustments: Array<{ type: string; value: number }>;
      product: {
        type: string;
        price: number | { toNumber(): number };
        name: string;
      };
    }>,
    historyByProduct: Map<number, Array<{ effectiveAt: Date; price: number }>>,
  ): {
    totalRevenue: number;
    totalSold: number;
    totalDelivery: number;
    totalLeftover: number;
    totalReject: number;
    revenueByType: Record<string, number>;
    revenueByProduct: Map<
      number,
      { name: string; revenue: number; sold: number }
    >;
  } {
    let totalRevenue = 0;
    let totalSold = 0;
    let totalDelivery = 0;
    let totalLeftover = 0;
    let totalReject = 0;
    const revenueByType: Record<string, number> = {
      BREAD: 0,
      CAKE: 0,
      SPECIAL: 0,
      MISCELLANEOUS: 0,
    };
    const revenueByProduct = new Map<
      number,
      { name: string; revenue: number; sold: number }
    >();

    for (const inv of rows) {
      const sold = computeSold(inv);
      const effectivePrice = getEffectivePrice(
        inv.productId,
        inv.date,
        Number(inv.product.price),
        historyByProduct,
      );
      const revenue = sold * effectivePrice;

      totalRevenue += revenue;
      totalSold += sold;
      totalDelivery += inv.delivery;
      totalLeftover += inv.leftover;
      totalReject += inv.reject;

      if (inv.product.type in revenueByType)
        revenueByType[inv.product.type] += revenue;
      const prev = revenueByProduct.get(inv.productId);
      revenueByProduct.set(inv.productId, {
        name: inv.product.name,
        revenue: (prev?.revenue ?? 0) + revenue,
        sold: (prev?.sold ?? 0) + sold,
      });
    }

    return {
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      revenueByProduct,
    };
  }

  private async fetchHistoryMap(
    productIds: number[],
  ): Promise<Map<number, { price: number; effectiveAt: Date }[]>> {
    if (productIds.length === 0) return new Map();
    const histories = await this.prisma.productPriceHistory.findMany({
      where: { productId: { in: productIds } },
      orderBy: { effectiveAt: 'asc' },
    });
    const map = new Map<number, { price: number; effectiveAt: Date }[]>();
    for (const h of histories) {
      const arr = map.get(h.productId) ?? [];
      arr.push({ price: h.price.toNumber(), effectiveAt: h.effectiveAt });
      map.set(h.productId, arr);
    }
    return map;
  }

  async findByDate(branchId: number, date: string) {
    const rows = await this.prisma.inventory.findMany({
      where: {
        branchId,
        date: new Date(date),
        deletedAt: null,
      },
      orderBy: [
        { product: { type: 'asc' } },
        { product: { sortOrder: 'asc' } },
        { product: { name: 'asc' } },
      ],
      include: {
        product: true,
        adjustments: {
          where: { deletedAt: null },
          orderBy: { createdAt: 'asc' },
        },
      },
    });
    const historyMap = await this.fetchHistoryMap([
      ...new Set(rows.map((r) => r.productId)),
    ]);
    return rows.map((r) => ({
      ...r,
      effectivePrice: getEffectivePrice(
        r.productId,
        r.date,
        Number(r.product.price),
        historyMap,
      ),
    }));
  }

  async findByBranchDateRange(
    branchId: number,
    startDate: string,
    endDate?: string,
  ) {
    const start = new Date(startDate);
    const end = endDate ? new Date(endDate) : start;
    this.validateDateRange(start, end);

    const rows = await this.prisma.inventory.findMany({
      where: {
        branchId,
        date:
          start.getTime() === end.getTime() ? start : { gte: start, lte: end },
        deletedAt: null,
      },
      orderBy: [
        { date: 'asc' },
        { product: { type: 'asc' } },
        { product: { sortOrder: 'asc' } },
        { product: { name: 'asc' } },
      ],
      include: {
        product: true,
        adjustments: {
          where: { deletedAt: null },
          orderBy: { createdAt: 'asc' },
        },
      },
    });
    const historyMap = await this.fetchHistoryMap([
      ...new Set(rows.map((r) => r.productId)),
    ]);
    return rows.map((r) => ({
      ...r,
      effectivePrice: getEffectivePrice(
        r.productId,
        r.date,
        Number(r.product.price),
        historyMap,
      ),
    }));
  }

  async findByDateAllBranches(
    startDate?: string,
    endDate?: string,
    branchId?: number,
  ) {
    const start = startDate ? new Date(startDate) : undefined;
    const end = endDate ? new Date(endDate) : start;
    if (start && end) this.validateDateRange(start, end);
    const dateFilter = start
      ? start.getTime() === end?.getTime()
        ? { date: start }
        : { date: { gte: start, lte: end } }
      : {};
    const rows = await this.prisma.inventory.findMany({
      where: {
        ...dateFilter,
        deletedAt: null,
        ...(branchId != null ? { branchId } : {}),
      },
      orderBy: [
        { branchId: 'asc' },
        { date: 'asc' },
        { product: { type: 'asc' } },
        { product: { sortOrder: 'asc' } },
        { product: { name: 'asc' } },
      ],
      include: {
        branch: true,
        product: true,
        adjustments: {
          where: { deletedAt: null },
          orderBy: { createdAt: 'asc' },
        },
      },
    });
    const historyMap = await this.fetchHistoryMap([
      ...new Set(rows.map((r) => r.productId)),
    ]);
    return rows.map((r) => ({
      ...r,
      effectivePrice: getEffectivePrice(
        r.productId,
        r.date,
        Number(r.product.price),
        historyMap,
      ),
    }));
  }

  async findOne(id: number, branchId?: number) {
    const inventory = await this.prisma.inventory.findFirst({
      where: { id, deletedAt: null, ...(branchId != null ? { branchId } : {}) },
      include: {
        branch: true,
        product: true,
        adjustments: {
          where: { deletedAt: null },
          orderBy: { createdAt: 'asc' },
        },
      },
    });
    if (!inventory) {
      throw new NotFoundException('Inventory record not found');
    }
    return inventory;
  }

  async update(id: number, body: UpdateInventoryDto, branchId?: number) {
    const existing = await this.prisma.inventory.findFirst({
      where: { id, deletedAt: null, ...(branchId != null ? { branchId } : {}) },
    });
    if (!existing) throw new NotFoundException('Inventory record not found');

    const leftoverChanged =
      body.leftover !== undefined && body.leftover !== existing.leftover;

    const updated = await this.prisma.inventory.update({
      where: { id },
      data: {
        branchId: body.branchId,
        productId: body.productId,
        date: body.date ? new Date(body.date) : undefined,
        quantity: body.quantity,
        delivery: body.delivery,
        leftover: body.leftover,
        reject: body.reject,
        notes: body.notes,
        // Always flip to manually-entered when a user edits a row
        isAutoGenerated: false,
      },
      include: { branch: true, product: true },
    });

    // Auto-recascade downstream auto-generated rows when leftover changes so
    // they don't need a separate manual recascade call.
    if (leftoverChanged) {
      const fromDate = updated.date.toISOString().slice(0, 10);
      const { updated: cascadeUpdated } = await this.recascadeLeftovers(
        updated.branchId,
        updated.productId,
        fromDate,
      );
      return { ...updated, cascadeWarning: 0, cascadeUpdated };
    }

    // Leftover unchanged — still warn if downstream stale rows exist.
    const cascadeWarning = await this.prisma.inventory.count({
      where: {
        branchId: updated.branchId,
        productId: updated.productId,
        date: { gt: updated.date },
        isAutoGenerated: true,
      },
    });

    return { ...updated, cascadeWarning, cascadeUpdated: 0 };
  }

  async remove(id: number, branchId?: number) {
    const existing = await this.prisma.inventory.findFirst({
      where: { id, deletedAt: null, ...(branchId != null ? { branchId } : {}) },
    });
    if (!existing) throw new NotFoundException('Inventory record not found');
    return this.prisma.inventory.update({
      where: { id },
      data: { deletedAt: new Date() },
    });
  }

  getSummary(branchId: number | null, startDate?: string, endDate?: string) {
    return this.cache.wrap(
      CACHE_NS.INVENTORY_AGG,
      ['summary', branchId ?? 'all', startDate ?? '', endDate ?? ''],
      () => this.getSummaryUncached(branchId, startDate, endDate),
    );
  }

  private async getSummaryUncached(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
  ) {
    const today = this.localToday();
    const start = startDate ? new Date(startDate) : today;
    const end = endDate ? new Date(endDate) : start;

    const rows = await this.prisma.inventory.findMany({
      where: {
        deletedAt: null,
        date:
          start.getTime() === end.getTime() ? start : { gte: start, lte: end },
        ...(branchId ? { branchId } : {}),
      },
      include: {
        adjustments: { where: { deletedAt: null } },
        product: { select: { id: true, type: true, price: true, name: true } },
      },
    });

    if (rows.length === 0) {
      return {
        totalRevenue: 0,
        totalSold: 0,
        totalDelivery: 0,
        totalLeftover: 0,
        totalReject: 0,
        revenueByType: { BREAD: 0, CAKE: 0, SPECIAL: 0, MISCELLANEOUS: 0 },
        topProduct: null,
        zeroSales: [] as { name: string; revenue: number; sold: number }[],
      };
    }

    const productIds = [...new Set(rows.map((r) => r.productId))];
    const historyByProduct = await this.fetchHistoryMap(productIds);
    const {
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      revenueByProduct,
    } = this.aggregateInventoryMetrics(rows, historyByProduct);

    const sorted = Array.from(revenueByProduct.values()).sort(
      (a, b) => b.revenue - a.revenue,
    );

    return {
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      topProduct: sorted[0] ?? null,
      zeroSales: sorted.filter((r) => r.sold <= 0),
    };
  }

  getDashboard(branchId: number | null, startDate?: string, endDate?: string) {
    return this.cache.wrap(
      CACHE_NS.INVENTORY_AGG,
      ['dashboard', branchId ?? 'all', startDate ?? '', endDate ?? ''],
      () => this.getDashboardUncached(branchId, startDate, endDate),
    );
  }

  private async getDashboardUncached(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
  ) {
    const today = this.localToday();
    const start = startDate ? new Date(startDate) : today;
    const end = endDate ? new Date(endDate) : start;
    this.validateDateRange(start, end);

    const rows = await this.prisma.inventory.findMany({
      where: {
        deletedAt: null,
        date:
          start.getTime() === end.getTime() ? start : { gte: start, lte: end },
        ...(branchId ? { branchId } : {}),
      },
      orderBy: { date: 'asc' },
      include: {
        adjustments: { where: { deletedAt: null } },
        product: { select: { id: true, type: true, price: true, name: true } },
      },
    });

    const isRange = start.getTime() !== end.getTime();
    const dateRange = {
      startDate: start.toISOString().slice(0, 10),
      endDate: end.toISOString().slice(0, 10),
    };

    if (rows.length === 0) {
      return {
        dateRange,
        isRange,
        totalRevenue: 0,
        totalSold: 0,
        totalDelivery: 0,
        totalLeftover: 0,
        totalReject: 0,
        revenueByType: { BREAD: 0, CAKE: 0, SPECIAL: 0, MISCELLANEOUS: 0 },
        topProduct: null,
        zeroSales: [] as { name: string; revenue: number; sold: number }[],
        dailyBreakdown: [] as {
          date: string;
          revenue: number;
          sold: number;
          delivery: number;
          leftover: number;
        }[],
      };
    }

    const productIds = [...new Set(rows.map((r) => r.productId))];
    const historyByProduct = await this.fetchHistoryMap(productIds);
    const {
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      revenueByProduct,
    } = this.aggregateInventoryMetrics(rows, historyByProduct);

    // Daily breakdown (dashboard-only) — single additional pass
    const dailyMap = new Map<
      string,
      { revenue: number; sold: number; delivery: number; leftover: number }
    >();
    for (const inv of rows) {
      const sold = computeSold(inv);
      const effectivePrice = getEffectivePrice(
        inv.productId,
        inv.date,
        Number(inv.product.price),
        historyByProduct,
      );
      const revenue = sold * effectivePrice;
      const dk = inv.date.toISOString().slice(0, 10);
      const day = dailyMap.get(dk) ?? {
        revenue: 0,
        sold: 0,
        delivery: 0,
        leftover: 0,
      };
      dailyMap.set(dk, {
        revenue: day.revenue + revenue,
        sold: day.sold + sold,
        delivery: day.delivery + inv.delivery,
        leftover: day.leftover + inv.leftover,
      });
    }

    const sorted = Array.from(revenueByProduct.values()).sort(
      (a, b) => b.revenue - a.revenue,
    );
    const dailyBreakdown = Array.from(dailyMap.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, v]) => ({ date, ...v }));

    return {
      dateRange,
      isRange,
      totalRevenue,
      totalSold,
      totalDelivery,
      totalLeftover,
      totalReject,
      revenueByType,
      topProduct: sorted[0] ?? null,
      zeroSales: sorted.filter((r) => r.sold <= 0),
      dailyBreakdown,
    };
  }

  async exportSalesCsv(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
  ): Promise<string> {
    const data = await this.getDashboard(branchId, startDate, endDate);
    const lines: string[] = [];

    lines.push('Sales Report');
    lines.push(
      `Period,${data.dateRange.startDate} to ${data.dateRange.endDate}`,
    );
    lines.push('');
    lines.push('SUMMARY');
    lines.push(`Total Revenue,${Number(data.totalRevenue).toFixed(2)}`);
    lines.push(`Total Sold,${data.totalSold}`);
    lines.push(`Total Delivered,${data.totalDelivery}`);
    lines.push(`Total Leftover,${data.totalLeftover}`);
    lines.push(`Total Reject,${data.totalReject}`);
    lines.push('');
    lines.push('REVENUE BY PRODUCT TYPE');
    lines.push('Type,Revenue');
    for (const [type, revenue] of Object.entries(data.revenueByType)) {
      lines.push(`${type},${Number(revenue).toFixed(2)}`);
    }
    if (data.topProduct) {
      lines.push('');
      lines.push('TOP PRODUCT');
      lines.push(`Name,Sold,Revenue`);
      lines.push(
        `${csvField(data.topProduct.name)},${data.topProduct.sold},${Number(data.topProduct.revenue).toFixed(2)}`,
      );
    }
    if (data.dailyBreakdown.length > 0) {
      lines.push('');
      lines.push('DAILY BREAKDOWN');
      lines.push('Date,Revenue,Sold,Delivery,Leftover');
      for (const d of data.dailyBreakdown) {
        lines.push(
          `${d.date},${Number(d.revenue).toFixed(2)},${d.sold},${d.delivery},${d.leftover}`,
        );
      }
    }
    if (data.zeroSales.length > 0) {
      lines.push('');
      lines.push('ZERO SALES PRODUCTS');
      lines.push('Product,Sold,Revenue');
      for (const z of data.zeroSales) {
        lines.push(
          `${csvField(z.name)},${z.sold},${Number(z.revenue).toFixed(2)}`,
        );
      }
    }

    return lines.join('\r\n');
  }

  /**
   * Return all branch × product × date combos that have no Inventory entry
   * within the given date range. Limited to 31 days to prevent huge payloads.
   */
  getGaps(branchId: number | null, startDate: string, endDate: string) {
    return this.cache.wrap(
      CACHE_NS.INVENTORY_AGG,
      ['gaps', branchId ?? 'all', startDate, endDate],
      () => this.getGapsUncached(branchId, startDate, endDate),
    );
  }

  private async getGapsUncached(
    branchId: number | null,
    startDate: string,
    endDate: string,
  ) {
    const start = new Date(startDate);
    const end = new Date(endDate);
    const diffDays = Math.floor(
      (end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24),
    );
    if (diffDays < 0)
      throw new BadRequestException('endDate must be on or after startDate');
    if (diffDays > 30)
      throw new BadRequestException('Date range cannot exceed 31 days');

    // Build the expected date array
    const dates: Date[] = [];
    for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
      dates.push(new Date(d));
    }

    // Fetch active branches and products
    const [branches, products] = await Promise.all([
      this.prisma.branch.findMany({
        where: {
          deletedAt: null,
          isActive: true,
          ...(branchId ? { id: branchId } : {}),
        },
        select: { id: true, name: true },
      }),
      this.prisma.product.findMany({
        where: { deletedAt: null, isActive: true },
        select: { id: true, name: true },
        orderBy: [{ type: 'asc' }, { sortOrder: 'asc' }, { name: 'asc' }],
      }),
    ]);

    // Fetch existing inventory rows in the range
    const existing = await this.prisma.inventory.findMany({
      where: {
        deletedAt: null,
        date: { gte: start, lte: end },
        ...(branchId ? { branchId } : {}),
      },
      select: { branchId: true, productId: true, date: true },
    });

    // Build a Set of keys for O(1) lookup: "branchId-productId-YYYY-MM-DD"
    const existingKeys = new Set(
      existing.map(
        (r) =>
          `${r.branchId}-${r.productId}-${r.date.toISOString().slice(0, 10)}`,
      ),
    );

    const missing: {
      branchId: number;
      branchName: string;
      productId: number;
      productName: string;
      date: string;
    }[] = [];
    for (const branch of branches) {
      for (const product of products) {
        for (const date of dates) {
          const key = `${branch.id}-${product.id}-${date.toISOString().slice(0, 10)}`;
          if (!existingKeys.has(key)) {
            missing.push({
              branchId: branch.id,
              branchName: branch.name,
              productId: product.id,
              productName: product.name,
              date: date.toISOString().slice(0, 10),
            });
          }
        }
      }
    }

    return { missing, total: missing.length };
  }

  /**
   * Walk forward from fromDate through contiguous auto-generated inventory rows
   * and update each one's leftover (and quantity) to carry forward the prior
   * day's leftover. Stops at the first manually-entered row.
   */
  async recascadeLeftovers(
    branchId: number,
    productId: number,
    fromDate: string,
  ) {
    const seed = await this.prisma.inventory.findFirst({
      where: { branchId, productId, date: new Date(fromDate), deletedAt: null },
    });
    if (!seed) throw new NotFoundException('Source inventory row not found');

    // Fetch ALL subsequent rows (auto and manual) and stop at the first manually-entered
    // row, since a manual entry is an authoritative boundary the cascade must not cross.
    const allSubsequent = await this.prisma.inventory.findMany({
      where: { branchId, productId, date: { gt: seed.date }, deletedAt: null },
      orderBy: { date: 'asc' },
      select: { id: true, isAutoGenerated: true },
    });

    const toUpdate: { id: number }[] = [];
    for (const row of allSubsequent) {
      if (!row.isAutoGenerated) break;
      toUpdate.push({ id: row.id });
    }

    if (toUpdate.length === 0) return { updated: 0 };

    await this.prisma.inventory.updateMany({
      where: { id: { in: toUpdate.map((r) => r.id) } },
      data: { quantity: seed.leftover, leftover: seed.leftover },
    });

    return { updated: toUpdate.length };
  }

  getRejectionByProduct(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
    type?: ProductType,
  ) {
    return this.cache.wrap(
      CACHE_NS.INVENTORY_AGG,
      [
        'rejection',
        branchId ?? 'all',
        startDate ?? '',
        endDate ?? '',
        type ?? 'all',
      ],
      () =>
        this.getRejectionByProductUncached(branchId, startDate, endDate, type),
    );
  }

  private async getRejectionByProductUncached(
    branchId: number | null,
    startDate?: string,
    endDate?: string,
    type?: ProductType,
  ) {
    const today = this.localToday();
    const start = startDate ? new Date(startDate) : today;
    const end = endDate ? new Date(endDate) : start;
    this.validateDateRange(start, end, 90);

    // Step 1: resolve qualifying products (excludes soft-deleted products).
    const products = await this.prisma.product.findMany({
      where: { deletedAt: null, ...(type ? { type } : {}) },
      select: { id: true, name: true, type: true },
    });

    if (products.length === 0) return [];

    const productIds = products.map((p) => p.id);

    // Step 2: aggregate in the database rather than in application memory.
    const grouped = await this.prisma.inventory.groupBy({
      by: ['productId'],
      where: {
        deletedAt: null,
        productId: { in: productIds },
        date:
          start.getTime() === end.getTime() ? start : { gte: start, lte: end },
        ...(branchId ? { branchId } : {}),
      },
      _sum: { delivery: true, reject: true },
    });

    const productMap = new Map(products.map((p) => [p.id, p]));

    return grouped
      .map((row) => {
        const product = productMap.get(row.productId)!;
        const totalDelivery = row._sum.delivery ?? 0;
        const totalReject = row._sum.reject ?? 0;
        return {
          productId: row.productId,
          name: product.name,
          type: product.type,
          totalDelivery,
          totalReject,
          rejectRate:
            totalDelivery > 0 ? (totalReject / totalDelivery) * 100 : 0,
        };
      })
      .sort((a, b) => b.totalReject - a.totalReject);
  }
}
