// ────────────────────────────────────────────────────────────────
// Enums
// ────────────────────────────────────────────────────────────────
export type UserRole = 'USER' | 'VIEWER' | 'INVENTORY' | 'MANAGER' | 'ADMIN';
export type FileStatus = 'PENDING' | 'UPLOADED' | 'PROCESSING' | 'FAILED';
export type ProductType = 'BREAD' | 'CAKE' | 'SPECIAL' | 'MISCELLANEOUS';
export type JobStatus = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
export type AdjustmentType = 'PULL_IN' | 'PULL_OUT' | 'ANOMALY';
export type MeasurementUnit =
  | 'KG'
  | 'G'
  | 'LITER'
  | 'ML'
  | 'PIECE'
  | 'DOZEN'
  | 'BAG'
  | 'SACHET'
  | 'CUP'
  | 'TBSP'
  | 'TSP';

// ────────────────────────────────────────────────────────────────
// Auth
// ────────────────────────────────────────────────────────────────
export interface User {
  id: number;
  email: string;
  role: UserRole;
  isActive: boolean;
  mustChangePassword: boolean;
  branchId: number | null;
  managedBranch?: Pick<Branch, 'id' | 'name'> | null;
  createdBy?: Pick<User, 'id' | 'email'> | null;
  createdAt: string;
  updatedAt: string;
  /** Effective feature keys. Returned by GET /auth/me; absent elsewhere. */
  permissions?: string[];
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  user: User;
}

// ────────────────────────────────────────────────────────────────
// Products
// ────────────────────────────────────────────────────────────────
export interface Product {
  id: number;
  name: string;
  type: ProductType;
  sortOrder: number;
  price: number;
  isActive: boolean;
  date: string;
  createdAt: string;
  deletedAt: string | null;
}

// ────────────────────────────────────────────────────────────────
// Branches
// ────────────────────────────────────────────────────────────────
export interface Branch {
  id: number;
  name: string;
  address: string | null;
  phone: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
  manager?: Pick<User, 'id' | 'email'> | null;
}

// ────────────────────────────────────────────────────────────────
// Inventory
// ────────────────────────────────────────────────────────────────
export interface InventoryAdjustment {
  id: number;
  inventoryId: number;
  type: AdjustmentType;
  value: number;
  notes: string | null;
  linkedAdjustmentId: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface TransferResult {
  pullOut: InventoryAdjustment;
  pullIn: InventoryAdjustment;
}

export interface Inventory {
  id: number;
  branchId: number;
  productId: number;
  createdById: number | null;
  quantity: number;
  delivery: number;
  leftover: number;
  reject: number;
  date: string;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  branch?: Branch;
  product?: Product;
  adjustments?: InventoryAdjustment[];
  effectivePrice?: number;
  isAutoGenerated?: boolean;
}

// ────────────────────────────────────────────────────────────────
// Suppliers
// ────────────────────────────────────────────────────────────────
export interface Supplier {
  id: number;
  name: string;
  contact: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

// ────────────────────────────────────────────────────────────────
// Materials
// ────────────────────────────────────────────────────────────────
export interface Material {
  id: number;
  name: string;
  unit: MeasurementUnit;
  pricePerUnit: number;
  reorderLevel: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

// ────────────────────────────────────────────────────────────────
// Recipes
// ────────────────────────────────────────────────────────────────
export interface RecipeItem {
  id: number;
  recipeId: number;
  materialId: number;
  quantity: number;
  unit: MeasurementUnit;
  material?: Material;
}

export interface Recipe {
  id: number;
  productId: number;
  recipeYield: number;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  items: RecipeItem[];
  product?: Product;
}

export interface RecipeCost {
  recipeId: number;
  productId: number;
  productName: string;
  productPrice: number;
  recipeYield: number;
  totalBatchCost: number;
  costPerUnit: number;
  grossProfitPerUnit: number;
  /** Decimal ratio 0–1 (e.g. 0.42 = 42%). Multiply by 100 to display as percent. */
  grossMarginPercent: number;
  items: {
    materialId: number;
    materialName: string;
    quantity: number;
    unit: MeasurementUnit;
    quantityInBaseUnit: number;
    baseUnit: MeasurementUnit;
    pricePerUnit: number;
    cost: number;
  }[];
}

// ────────────────────────────────────────────────────────────────
// Sales
// ────────────────────────────────────────────────────────────────
export interface SaleRecord {
  productId: number;
  productName: string;
  date: string;
  delivery: number;
  leftover: number;
  reject: number;
  sold: number;
  revenue: number;
}

export interface SaleSummary {
  date: string;
  totalSold: number;
  totalRevenue: number;
}

// ────────────────────────────────────────────────────────────────
// Material Inventory
// ────────────────────────────────────────────────────────────────
export interface MaterialAdjustment {
  id: number;
  materialInventoryId: number;
  type: 'PULL_IN' | 'PULL_OUT' | 'ANOMALY';
  value: number;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface MaterialInventory {
  id: number;
  materialId: number;
  date: string;
  supplierId: number | null;
  createdById: number | null;
  batchNumber: string | null;
  expiresAt: string | null;
  quantity: number;
  delivery: number;
  used: number;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  material?: Material;
  supplier?: Supplier;
  adjustments?: MaterialAdjustment[];
}

// ────────────────────────────────────────────────────────────────
// Production
// ────────────────────────────────────────────────────────────────
export interface Production {
  id: number;
  branchId: number;
  productId: number;
  date: string;
  yield: number;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  branch?: Branch;
  product?: Product;
  isAutoGenerated?: boolean;
}

// ────────────────────────────────────────────────────────────────
// Unit Conversions
// ────────────────────────────────────────────────────────────────
export interface UnitConversion {
  id: number;
  fromUnit: MeasurementUnit;
  toUnit: MeasurementUnit;
  factor: number;
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────────
// Inventory Import
// ────────────────────────────────────────────────────────────────
export interface SheetImportResult {
  sheetName: string;
  date: string;
  processed: number;
  skipped: number;
  errors: string[];
}

export interface InventoryImportResult {
  summary: {
    totalSheets: number;
    totalProcessed: number;
    totalSkipped: number;
    totalErrors: number;
  };
  sheets: SheetImportResult[];
}

export interface ImportLog {
  id: number;
  branchId: number;
  fileName: string;
  fileHash: string;
  importedBy: number | null;
  importedAt: string;
  sheetCount: number;
  rowCount: number;
  skippedCount: number;
  status: 'SUCCESS' | 'PARTIAL';
  notes: string | null;
  branch: { name: string };
  importedByUser: { email: string } | null;
}

export interface ImportLogsResponse {
  total: number;
  page: number;
  limit: number;
  items: ImportLog[];
}

// ────────────────────────────────────────────────────────────────
// Price History
// ────────────────────────────────────────────────────────────────
export interface MaterialPriceHistory {
  id: number;
  materialId: number;
  supplierId: number | null;
  pricePerUnit: number;
  effectiveAt: string;
  createdAt: string;
  supplier?: Supplier;
}

export interface ProductPriceHistory {
  id: number;
  productId: number;
  price: number;
  effectiveAt: string;
  createdAt: string;
}

// ────────────────────────────────────────────────────────────────
// Material Consumption (Production → Materials)
// ────────────────────────────────────────────────────────────────
export interface MaterialConsumptionItem {
  materialId: number;
  materialName: string;
  materialUnit: string;
  recipeUnit: string;
  consumed: number;
  pricePerUnit: number;
  totalCost: number;
}

export interface MaterialConsumption {
  productionId: number;
  productName: string;
  date: string;
  yield: number;
  plannedYield: number;
  items: MaterialConsumptionItem[];
  totalMaterialCost: number;
}

// ────────────────────────────────────────────────────────────────
// Consumption Summary (Daily batch total)
// ────────────────────────────────────────────────────────────────
export interface ConsumptionSummaryItem {
  materialId: number;
  materialName: string;
  unit: string;
  totalConsumed: number;
  totalCost: number;
}

export interface ConsumptionSummary {
  date: string;
  items: ConsumptionSummaryItem[];
  grandTotalCost: number;
}

// ────────────────────────────────────────────────────────────────
// Production Efficiency
// ────────────────────────────────────────────────────────────────
export interface ProductionEfficiencyItem {
  productId: number;
  productName: string;
  productType: ProductType;
  totalYield: number;
  totalDelivered: number;
  totalLeftover: number;
  totalReject: number;
  sold: number;
  soldRate: number;
  wasteRate: number;
}

// ────────────────────────────────────────────────────────────────
// Inventory Import Preview
// ────────────────────────────────────────────────────────────────
export interface DryRunSheet {
  sheetName: string;
  date: string; // '' when the date could not be determined
  // Rows already stored for this sheet's date+branch. Placeholders are
  // untouched autofill rows (safe to absorb); real rows block the import
  // unless it is re-run with conflictMode 'overwrite'.
  existing?: { placeholders: number; real: number };
  matched: number; // distinct products found in the catalog
  unmatchedCount: number; // distinct names that did not match a product
  unmatched: string[]; // distinct unmatched names
  ambiguous: string[]; // labels matching several products with no alias
  error?: string; // sheet-level problem (e.g. no date header)
}

// A sheet label that matched no product, described richly enough to create the
// product without retyping anything. Deduplicated per label across the whole
// workbook — the same name appears on every day sheet.
export interface UnknownProduct {
  label: string; // verbatim column A text
  price: number; // price at the earliest sheet that names it
  page: number; // which PAGE block it sits under
  suggestedType: ProductType; // derived from `page`; the operator confirms it
  occurrences: number; // how many day sheets name it
  firstSeen: string; // YYYY-MM-DD of the earliest such sheet
  // Every distinct price the label carries, in date order. A label seen at two
  // prices is one product that was repriced, not two SKUs.
  priceChanges: { price: number; effectiveAt: string }[];
}

export interface DryRunResult {
  fileName: string;
  branch: { id: number; name: string } | null;
  alreadyImported: { logId: number; importedAt: string } | null;
  summary: {
    totalSheets: number;
    totalMatched: number;
    totalUnmatched: number;
    totalAmbiguous: number;
    datesDetected: string[];
  };
  sheets: DryRunSheet[];
  unknownProducts: UnknownProduct[];
}

// The operator's decision for one unknown label: create it as a product of
// this type, or skip it. Name and price always come from the sheet.
export type UnknownDecision =
  | { kind: 'create'; type: ProductType }
  | { kind: 'skip' };

// ────────────────────────────────────────────────────────────────
// Pagination
// ────────────────────────────────────────────────────────────────
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

// ────────────────────────────────────────────────────────────────
// Dashboard
// ────────────────────────────────────────────────────────────────
export interface DashboardStats {
  products: { total: number; active: number };
  branches: { total: number; active: number };
  materials: { total: number };
  recipes: { total: number };
}

export interface DashboardProductionBreakdown {
  type: ProductType;
  totalYield: number;
}

export interface DashboardBranchSummary {
  id: number;
  name: string;
  address: string | null;
  isActive: boolean;
}

/**
 * Every field is optional: the server omits the ones whose dashboard panel
 * permission the caller does not hold, so a denied panel's data never reaches
 * the browser. Read each through a presence check, not a `!`.
 */
export interface DashboardSummary {
  /** `dashboard:kpis` */
  stats?: DashboardStats;
  /** `dashboard:production-mix` */
  production?: {
    date: string;
    totalYield: number;
    byType: DashboardProductionBreakdown[];
  };
  /** `dashboard:low-stock` */
  lowStock?: {
    id: number;
    name: string;
    unit: string;
    currentStock: number;
    reorderLevel: number;
  }[];
  /** `dashboard:kpis` */
  products?: {
    id: number;
    name: string;
    type: ProductType;
    price: number;
    isActive: boolean;
  }[];
  /** `dashboard:branch-gaps` */
  branches?: DashboardBranchSummary[];
  /** `dashboard:branch-gaps` — active branches with no entry for the date. */
  branchGaps?: DashboardBranchSummary[];
}

// ────────────────────────────────────────────────────────────────
// Inventory Summary
// ────────────────────────────────────────────────────────────────
export interface InventorySummaryData {
  totalRevenue: number;
  totalSold: number;
  totalDelivery: number;
  totalLeftover: number;
  totalReject: number;
  revenueByType: Record<ProductType, number>;
  topProduct: { productId: number; name: string; revenue: number; sold: number } | null;
  zeroSales: { productId: number; name: string; revenue: number; sold: number }[];
}

export interface InventoryDashboardData {
  dateRange: { startDate: string; endDate: string };
  isRange: boolean;
  totalRevenue: number;
  totalSold: number;
  totalDelivery: number;
  totalLeftover: number;
  totalReject: number;
  revenueByType: Record<ProductType, number>;
  topProduct: { productId: number; name: string; revenue: number; sold: number } | null;
  zeroSales: { productId: number; name: string; revenue: number; sold: number }[];
  dailyBreakdown: { date: string; revenue: number; sold: number; delivery: number; leftover: number }[];
}

// ────────────────────────────────────────────────────────────────
// Inventory Gaps
// ────────────────────────────────────────────────────────────────
export interface GapEntry {
  branchId: number;
  branchName: string;
  productId: number;
  productName: string;
  date: string;
}

export interface InventoryGapsResult {
  missing: GapEntry[];
  total: number;
}

export interface InventoryUpdateResult extends Inventory {
  cascadeWarning: number;
}

// ────────────────────────────────────────────────────────────────
// Production Orders
// ────────────────────────────────────────────────────────────────
export type ProductionOrderStatus = 'DRAFT' | 'FINALIZED' | 'CANCELLED';

export interface ProductionOrderItem {
  id: number;
  productionOrderId: number;
  productId: number;
  yield: number;
  product?: Product;
}

export interface ProductionOrder {
  id: number;
  branchId: number | null;
  date: string;
  status: ProductionOrderStatus;
  notes: string | null;
  createdById: number | null;
  createdAt: string;
  updatedAt: string;
  items: ProductionOrderItem[];
  branch?: Branch;
  createdBy?: { id: number; email: string; role: UserRole };
}

export interface PlannedYield {
  productId: number;
  plannedYield: number;
}

// ────────────────────────────────────────────────────────────────
// Material Stock Gaps
// ────────────────────────────────────────────────────────────────
export interface MaterialGapEntry {
  materialId: number;
  materialName: string;
  date: string;
}

export interface MaterialGapsResult {
  missing: MaterialGapEntry[];
  total: number;
}

export interface RejectionByProductItem {
  productId: number;
  name: string;
  type: ProductType;
  totalDelivery: number;
  totalReject: number;
  rejectRate: number;
}

// ────────────────────────────────────────────────────────────────
// Feature Permissions
// ────────────────────────────────────────────────────────────────
export interface Feature {
  id: number;
  key: string;
  label: string;
  description: string | null;
  createdAt: string;
}

export interface RolePermissionState {
  default: boolean;
  effective: boolean;
  overridden: boolean;
  /** ADMIN may not have this revoked; the switch renders disabled. */
  locked: boolean;
  /**
   * False when the role sits below the `@Roles()` floor on this key's
   * endpoints, so granting it would produce a control that 403s. The switch
   * renders unavailable rather than offering an impossible grant.
   */
  available: boolean;
}

/** Metadata every matrix row carries, whether it is a screen, action or panel. */
export interface PermissionRowMeta {
  key: string;
  label: string;
  description: string | null;
  group: string | null;
  platform: 'web' | 'mobile' | 'both';
  /** Null for a screen; the owning screen's key for an action or panel. */
  parent: string | null;
  kind: 'feature' | 'action' | 'panel';
  /** Actions only: the role floor its endpoints enforce. */
  minRole: string | null;
  /**
   * Panels only. `sensitive` means the server withholds the data as well as the
   * UI hiding it; `presentation` means the gate is layout only.
   */
  sensitivity: 'presentation' | 'sensitive' | null;
}

export interface PermissionsMatrixFeature extends PermissionRowMeta {
  roles: Record<string, RolePermissionState>;
}

export interface PermissionsMatrixResponse {
  features: PermissionsMatrixFeature[];
}

/**
 * One row per feature for a single account.
 *
 * Replaces the previous shape, which stamped that user's override across every
 * role column — it rendered correctly only because the UI read one column.
 */
export interface UserPermissionRow extends PermissionRowMeta {
  /** What ROLE_DEFAULTS grants this user's role. */
  roleDefault: boolean;
  /** After any role-level override. */
  roleEffective: boolean;
  /** This user's own override, or null when they inherit the role. */
  userOverride: boolean | null;
  /** The net result actually enforced. */
  effective: boolean;
  /**
   * Whether the owning screen is granted. A child key with this false is inert
   * however it is toggled, so the UI shows it as blocked by its parent.
   */
  parentEffective: boolean;
  available: boolean;
  locked: boolean;
}

export interface UserPermissionsResponse {
  user: { id: number; email: string; role: UserRole; isActive: boolean };
  features: UserPermissionRow[];
}

export interface UserFeaturePermission {
  id: number;
  userId: number;
  featureKey: string;
  enabled: boolean;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────────
// Production suggestions
// ────────────────────────────────────────────────────────────────
export type SuggestionPeriod = 'prev-day' | '7d' | '30d';

export interface ProductionSuggestion {
  productId: number;
  avgSold: number;
  suggestedQty: number;
  daysWithData: number;
}

export interface ProductionSuggestionsResponse {
  branchId: number;
  period: SuggestionPeriod;
  window: { startDate: string; endDate: string };
  suggestions: ProductionSuggestion[];
}

// ────────────────────────────────────────────────────────────────
// Background job runs
// ────────────────────────────────────────────────────────────────
export interface JobRun {
  id: number;
  jobName: string;
  trigger: 'cron' | 'manual' | 'boot';
  targetDate: string | null;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
  startedAt: string;
  finishedAt: string | null;
  result: Record<string, unknown> | null;
  error: string | null;
}

export interface JobRunsResponse {
  runs: JobRun[];
  latest: JobRun[];
}
