import { BadRequestException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { InventoryAdjustmentsService } from './inventory-adjustments.service';
import { FakeStockDb, day } from '../common/testing/fake-stock-db';

/**
 * A transfer names the destination BRANCH; the server finds that branch's row for the product and
 * day (creating an empty placeholder if it is missing).
 *
 * Why: the adjustments dialog used to look the destination row up itself, by reading the other
 * branch's daily sheet — a read BranchGuard answers 403 for a branch-confined manager. So a manager,
 * who the server explicitly intends to send stock out, could not send from the UI at all.
 */
describe('InventoryAdjustmentsService — transfer to a branch', () => {
  let db: FakeStockDb;
  let service: InventoryAdjustmentsService;
  const admin = { id: 1, branchId: null, permissions: ['all-branches'] };
  const atBranch = (branchId: number) => ({ id: 10 + branchId, branchId, permissions: [] });
  const DATE = '2026-09-15';

  beforeEach(() => {
    db = new FakeStockDb();
    service = new InventoryAdjustmentsService(db as never);
    db.seed('branch', { id: 1, name: 'Sender' });
    db.seed('branch', { id: 2, name: 'Receiver' });
  });

  /** Sender has 30 on hand today. */
  const seedSender = () =>
    db.seed('inventory', {
      branchId: 1, productId: 7, date: day(DATE),
      quantity: 0, delivery: 30, leftover: 30, isAutoGenerated: true,
    });
  const seedReceiver = (extra: Record<string, unknown> = {}) =>
    db.seed('inventory', {
      branchId: 2, productId: 7, date: day(DATE),
      quantity: 5, leftover: 5, isAutoGenerated: true, ...extra,
    });
  const receiverRows = () => db.tables.inventory.filter((r) => r.branchId === 2 && r.productId === 7);
  const sendTo = (fromId: number, toBranchId: number, value = 10, user: object = atBranch(1)) =>
    service.transfer({ fromInventoryId: fromId, toBranchId, value } as never, user as never);

  describe('a branch-confined manager sending stock out', () => {
    it('reaches the receiver\'s existing row without reading its sheet, and the pull-out is pending', async () => {
      const src = seedSender();
      const dst = seedReceiver();

      const result = await sendTo(src.id, 2);

      expect(result.status).toBe('PENDING');
      expect(result.pullOut.transferToInventoryId).toBe(dst.id);
      expect(result.pullOut).toMatchObject({ type: 'PULL_OUT', value: 10, transferStatus: 'PENDING' });
      // The receiver is credited only when it accepts.
      expect(db.live('inventoryAdjustment', { inventoryId: dst.id })).toHaveLength(0);
    });

    it('creates an empty placeholder for the receiver when it has no row yet', async () => {
      const src = seedSender();

      const result = await sendTo(src.id, 2);

      const created = receiverRows();
      expect(created).toHaveLength(1);
      expect(created[0]).toMatchObject({
        branchId: 2, productId: 7, delivery: 0, reject: 0, isAutoGenerated: true, leftoverCountedAt: null,
      });
      expect(created[0].date.getTime()).toBe(day(DATE).getTime());
      // Nothing is sold or counted on it, and the transfer points at it.
      expect(result.pullOut.transferToInventoryId).toBe(created[0].id);
    });

    it('opens the created placeholder on the receiver\'s previous close', async () => {
      db.seed('inventory', {
        branchId: 2, productId: 7, date: day('2026-09-14'),
        quantity: 0, delivery: 4, leftover: 4, isAutoGenerated: true,
      });
      const src = seedSender();

      await sendTo(src.id, 2);

      const today = receiverRows().find((r) => r.date.getTime() === day(DATE).getTime())!;
      expect(today.quantity).toBe(4);
    });

    it('restores a soft-deleted receiver row instead of leaving the transfer pointing at a tombstone', async () => {
      const src = seedSender();
      const dst = seedReceiver({ deletedAt: new Date(), delivery: 99, reject: 3 });

      const result = await sendTo(src.id, 2);

      expect(result.pullOut.transferToInventoryId).toBe(dst.id);
      const restored = db.tables.inventory.find((r) => r.id === dst.id)!;
      expect(restored.deletedAt).toBeNull();
      // Restored empty, not resurrecting what was typed before it was deleted.
      expect(restored).toMatchObject({ delivery: 0, reject: 0, leftoverCountedAt: null });
    });
  });

  describe('refusals', () => {
    it('is still capped by the sender\'s on-hand stock, and a refused transfer creates nothing', async () => {
      const src = seedSender();

      await expect(sendTo(src.id, 2, 31)).rejects.toBeInstanceOf(BadRequestException);

      expect(receiverRows()).toHaveLength(0); // the placeholder was rolled back with the rest
      expect(db.live('inventoryAdjustment')).toHaveLength(0);
    });

    it('cannot send another branch\'s stock', async () => {
      const src = seedSender();

      await expect(sendTo(src.id, 2, 10, atBranch(3))).rejects.toBeInstanceOf(ForbiddenException);
      expect(receiverRows()).toHaveLength(0);
    });

    it('refuses the sender\'s own branch', async () => {
      const src = seedSender();
      await expect(sendTo(src.id, 1)).rejects.toThrow(/different branches/);
    });

    it('refuses a branch that does not exist', async () => {
      const src = seedSender();
      await expect(sendTo(src.id, 99)).rejects.toBeInstanceOf(NotFoundException);
      expect(receiverRows()).toHaveLength(0);
    });

    it('refuses a deleted branch', async () => {
      const src = seedSender();
      db.seed('branch', { id: 3, name: 'Gone', deletedAt: new Date() });
      await expect(sendTo(src.id, 3)).rejects.toBeInstanceOf(NotFoundException);
    });

    it('refuses an inactive branch', async () => {
      const src = seedSender();
      db.seed('branch', { id: 4, name: 'Closed', isActive: false });
      await expect(sendTo(src.id, 4)).rejects.toBeInstanceOf(BadRequestException);
      expect(db.tables.inventory.filter((r) => r.branchId === 4)).toHaveLength(0);
    });

    it('refuses a request that names both a destination row and a branch', async () => {
      const src = seedSender();
      const dst = seedReceiver();
      await expect(
        service.transfer(
          { fromInventoryId: src.id, toInventoryId: dst.id, toBranchId: 2, value: 5 } as never,
          atBranch(1) as never,
        ),
      ).rejects.toThrow(/either/i);
    });

    it('refuses a request that names neither', async () => {
      const src = seedSender();
      await expect(
        service.transfer({ fromInventoryId: src.id, value: 5 } as never, atBranch(1) as never),
      ).rejects.toBeInstanceOf(BadRequestException);
    });
  });

  it('still accepts a destination row id (admin / existing callers)', async () => {
    const src = seedSender();
    const dst = seedReceiver();

    const result = await service.transfer(
      { fromInventoryId: src.id, toInventoryId: dst.id, value: 10 } as never,
      admin as never,
    );

    expect(result.status).toBe('PENDING');
    expect(result.pullOut.transferToInventoryId).toBe(dst.id);
  });
});
