import { InventoryAdjustmentsService } from './inventory-adjustments.service';
import { FakeStockDb, day } from '../common/testing/fake-stock-db';

/** Adjustments move a day's stock, so the following days must follow. */
describe('InventoryAdjustmentsService — carry-forward', () => {
  let db: FakeStockDb;
  let service: InventoryAdjustmentsService;
  const admin = { id: 1, branchId: null, permissions: ['all-branches'] };

  beforeEach(() => {
    db = new FakeStockDb();
    service = new InventoryAdjustmentsService(db as never);
  });

  /** Two branches, same product: a placeholder day, then another placeholder. */
  function seed() {
    const src = db.seed('inventory', {
      branchId: 1, productId: 7, date: day('2026-09-15'),
      quantity: 30, leftover: 30, isAutoGenerated: true,
    });
    db.seed('inventory', {
      branchId: 1, productId: 7, date: day('2026-09-16'),
      quantity: 30, leftover: 30, isAutoGenerated: true,
    });
    const dst = db.seed('inventory', {
      branchId: 2, productId: 7, date: day('2026-09-15'),
      quantity: 5, leftover: 5, isAutoGenerated: true,
    });
    db.seed('inventory', {
      branchId: 2, productId: 7, date: day('2026-09-16'),
      quantity: 5, leftover: 5, isAutoGenerated: true,
    });
    return { src, dst };
  }
  const openings = (branchId: number) =>
    db.live('inventory', { branchId }).map((r) => r.quantity);

  it('moves both branches’ following days when a transfer is booked', async () => {
    const { src, dst } = seed();

    await service.transfer(
      { fromInventoryId: src.id, toInventoryId: dst.id, value: 10 },
      admin,
    );

    expect(openings(1)).toEqual([30, 20]);
    expect(openings(2)).toEqual([5, 15]);
  });

  it('puts the stock back on both sides when the transfer is deleted', async () => {
    const { src, dst } = seed();
    const { pullOut } = await service.transfer(
      { fromInventoryId: src.id, toInventoryId: dst.id, value: 10 },
      admin,
    );

    await service.remove(pullOut.id, admin);

    expect(openings(1)).toEqual([30, 30]);
    expect(openings(2)).toEqual([5, 5]);
  });

  it('carries a standalone pull-out forward', async () => {
    const { src } = seed();

    await service.create({ inventoryId: src.id, type: 'PULL_OUT', value: 4 }, admin);

    expect(openings(1)).toEqual([30, 26]);
  });
});
