// src/jobs/jobs.service.spec.ts
import { Test, TestingModule } from '@nestjs/testing';
import { JobsService } from './jobs.service';
import { PrismaService } from '../prisma/prisma.service';
import { MaterialInventoryService } from '../material-inventory/material-inventory.service';

function makePrisma() {
  return {
    inventory: {
      findMany: jest.fn().mockResolvedValue([]),
      findFirst: jest.fn().mockResolvedValue(null),
      createMany: jest
        .fn()
        .mockImplementation(({ data }: { data: unknown[] }) => ({
          count: data.length,
        })),
    },
    production: {
      findMany: jest.fn().mockResolvedValue([]),
      createMany: jest
        .fn()
        .mockImplementation(({ data }: { data: unknown[] }) => ({
          count: data.length,
        })),
    },
    branch: { findMany: jest.fn().mockResolvedValue([]) },
    product: { findMany: jest.fn().mockResolvedValue([]) },
    material: { findMany: jest.fn().mockResolvedValue([]) },
    materialInventory: { findFirst: jest.fn().mockResolvedValue(null) },
    jobRun: {
      create: jest.fn().mockResolvedValue({ id: 99 }),
      update: jest.fn().mockResolvedValue({}),
      findMany: jest.fn().mockResolvedValue([]),
    },
    $queryRaw: jest.fn().mockResolvedValue([]),
    $transaction: jest
      .fn()
      .mockImplementation((ops: unknown[]) => Promise.all(ops)),
  };
}

describe('JobsService', () => {
  let service: JobsService;
  let prisma: ReturnType<typeof makePrisma>;
  const materialInventoryService = {
    initDate: jest.fn().mockResolvedValue({ created: 0 }),
  };

  beforeEach(async () => {
    jest.clearAllMocks();
    materialInventoryService.initDate.mockResolvedValue({ created: 0 });
    prisma = makePrisma();
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        JobsService,
        { provide: PrismaService, useValue: prisma },
        {
          provide: MaterialInventoryService,
          useValue: materialInventoryService,
        },
      ],
    }).compile();
    service = module.get(JobsService);
  });

  describe('autofillMissingEntries (carry-forward correctness)', () => {
    beforeEach(() => {
      prisma.branch.findMany.mockResolvedValue([{ id: 1, name: 'Main' }]);
      prisma.product.findMany.mockResolvedValue([{ id: 5, name: 'Pandesal' }]);
    });

    it('creates a placeholder that carries forward the prior leftover', async () => {
      // Most recent prior entry has leftover 12
      prisma.inventory.findMany.mockResolvedValueOnce([]); // existing inventory for target date
      prisma.$queryRaw.mockResolvedValueOnce([
        { branchId: 1, productId: 5, leftover: 12 },
      ]); // latest prior leftover per pair
      prisma.production.findMany.mockResolvedValue([]);

      const result = await service.autofillMissingEntries('2026-06-13');

      expect(result).toEqual({
        inventoryCreated: 1,
        productionCreated: 1,
        date: '2026-06-13',
      });
      expect(prisma.inventory.createMany).toHaveBeenCalledWith(
        expect.objectContaining({
          data: [
            expect.objectContaining({
              branchId: 1,
              productId: 5,
              quantity: 12,
              leftover: 12,
              isAutoGenerated: true,
            }),
          ],
          skipDuplicates: true,
        }),
      );
    });

    it('defaults the carried-forward leftover to 0 when no prior entry exists', async () => {
      prisma.inventory.findMany.mockResolvedValueOnce([]);

      await service.autofillMissingEntries('2026-06-13');

      expect(prisma.inventory.createMany).toHaveBeenCalledWith(
        expect.objectContaining({
          data: [expect.objectContaining({ quantity: 0, leftover: 0 })],
        }),
      );
    });

    it('batches all missing pairs into a single createMany per table', async () => {
      // 2 branches × 3 products = 6 pairs → exactly one createMany call each,
      // never one statement per pair (the regression that caused 300s runs).
      prisma.branch.findMany.mockResolvedValue([
        { id: 1, name: 'Main' },
        { id: 2, name: 'Cubao' },
      ]);
      prisma.product.findMany.mockResolvedValue([
        { id: 5, name: 'Pandesal' },
        { id: 6, name: 'Ensaymada' },
        { id: 7, name: 'Pandecoco' },
      ]);

      const result = await service.autofillMissingEntries('2026-06-13');

      expect(result.inventoryCreated).toBe(6);
      expect(result.productionCreated).toBe(6);
      expect(prisma.inventory.createMany).toHaveBeenCalledTimes(1);
      expect(prisma.production.createMany).toHaveBeenCalledTimes(1);
      const [invArgs] = prisma.inventory.createMany.mock.calls[0] as [
        { data: unknown[] },
      ];
      const [prodArgs] = prisma.production.createMany.mock.calls[0] as [
        { data: unknown[] },
      ];
      expect(invArgs.data).toHaveLength(6);
      expect(prodArgs.data).toHaveLength(6);
    });

    it('is idempotent — existing pairs produce no writes', async () => {
      prisma.inventory.findMany.mockResolvedValueOnce([
        { branchId: 1, productId: 5 },
      ]);
      prisma.production.findMany.mockResolvedValue([
        { branchId: 1, productId: 5 },
      ]);

      const result = await service.autofillMissingEntries('2026-06-13');

      expect(result.inventoryCreated).toBe(0);
      expect(result.productionCreated).toBe(0);
      expect(prisma.$transaction).not.toHaveBeenCalled();
    });

    it('defaults to today in Manila when no targetDate is given', async () => {
      const manilaToday = new Intl.DateTimeFormat('en-CA', {
        timeZone: 'Asia/Manila',
      }).format(new Date());

      const result = await service.autofillMissingEntries();

      expect(result.date).toBe(manilaToday);
      expect(result.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    });
  });

  describe('recordRun lifecycle (via autofillMissingEntries)', () => {
    beforeEach(() => {
      prisma.branch.findMany.mockResolvedValue([]);
      prisma.product.findMany.mockResolvedValue([]);
    });

    it('records a RUNNING row then marks it COMPLETED with the result', async () => {
      await service.autofillMissingEntries('2026-06-13');

      expect(prisma.jobRun.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({
            jobName: 'inventory-autofill',
            // The default is 'auto', not 'cron': there is no scheduler any
            // more, so an untagged run came from the on-demand page trigger.
            trigger: 'auto',
          }),
        }),
      );
      expect(prisma.jobRun.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 99 },
          data: expect.objectContaining({
            status: 'COMPLETED',
            result: expect.objectContaining({
              inventoryCreated: 0,
              productionCreated: 0,
            }),
          }),
        }),
      );
    });

    it('records the manual trigger when invoked from the controller path', async () => {
      await service.autofillMissingEntries('2026-06-13', 'manual');

      expect(prisma.jobRun.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({ trigger: 'manual' }),
        }),
      );
    });

    it('marks the run FAILED and rethrows when the job throws', async () => {
      prisma.branch.findMany.mockRejectedValue(new Error('db down'));

      await expect(
        service.autofillMissingEntries('2026-06-13'),
      ).rejects.toThrow('db down');

      expect(prisma.jobRun.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 99 },
          data: expect.objectContaining({
            status: 'FAILED',
            error: 'db down',
          }),
        }),
      );
    });

    it('still runs the job when the log write itself fails', async () => {
      prisma.jobRun.create.mockRejectedValue(new Error('log table missing'));

      const result = await service.autofillMissingEntries('2026-06-13');

      expect(result.date).toBe('2026-06-13');
      expect(prisma.jobRun.update).not.toHaveBeenCalled();
    });
  });

  describe('autofillMaterialStock', () => {
    it('delegates to materialInventoryService and records a run', async () => {
      materialInventoryService.initDate.mockResolvedValue({ created: 3 });

      const result = await service.autofillMaterialStock('2026-06-13');

      expect(result).toEqual({ created: 3, date: '2026-06-13' });
      expect(prisma.jobRun.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({ jobName: 'material-autofill' }),
        }),
      );
    });
  });

  // The boot-backfill test was removed with onModuleInit itself: Nest now
  // bootstraps on every serverless cold start, so a startup backfill would
  // have run constantly and blocked the first request each time. The
  // equivalent behaviour — and its failure isolation — is covered by
  // autofill-on-demand.service.spec.ts.

  describe('getRuns', () => {
    it('returns recent runs newest-first plus a latest-per-job summary', async () => {
      const rows = [{ id: 2 }, { id: 1 }];
      prisma.jobRun.findMany
        .mockResolvedValueOnce(rows) // list query
        .mockResolvedValueOnce([{ id: 2 }]); // distinct latest query

      const result = await service.getRuns(undefined, 20);

      expect(result).toEqual({ runs: rows, latest: [{ id: 2 }] });
      expect(prisma.jobRun.findMany).toHaveBeenNthCalledWith(
        1,
        expect.objectContaining({
          orderBy: { startedAt: 'desc' },
          take: 20,
        }),
      );
      expect(prisma.jobRun.findMany).toHaveBeenNthCalledWith(
        2,
        expect.objectContaining({
          distinct: ['jobName'],
          orderBy: { startedAt: 'desc' },
        }),
      );
    });

    it('filters by jobName and caps the limit at 100', async () => {
      prisma.jobRun.findMany.mockResolvedValue([]);

      await service.getRuns('inventory-autofill', 500);

      expect(prisma.jobRun.findMany).toHaveBeenNthCalledWith(
        1,
        expect.objectContaining({
          where: { jobName: 'inventory-autofill' },
          take: 100,
        }),
      );
    });
  });
});
