import { plainToInstance } from 'class-transformer';
import { validate } from 'class-validator';
import { UpdateInventoryDto } from './update-inventory.dto';
import { MAX_UNITS } from '../../common/constants/inventory.constants';

/**
 * Mirrors the global pipe: `{ whitelist: true, forbidNonWhitelisted: true }`.
 * Under that config a property the DTO does not declare is a 400, not a silent
 * strip — which is what makes removing a field an actual guarantee.
 */
async function check(payload: Record<string, unknown>) {
  const dto = plainToInstance(UpdateInventoryDto, payload, {
    excludeExtraneousValues: false,
  });
  return validate(dto, { whitelist: true, forbidNonWhitelisted: true });
}

describe('UpdateInventoryDto', () => {
  it('accepts the fields a sheet edit actually changes', async () => {
    expect(
      await check({ delivery: 10, leftover: 3, reject: 1, notes: 'ok' }),
    ).toEqual([]);
  });

  it.each(['branchId', 'productId', 'date'])(
    'refuses to re-key a row via %s',
    async (field) => {
      // A row's identity is (branch, product, date). Changing it through a
      // PATCH moved the row onto another day or branch, taking its adjustments
      // with it and breaking the leftover cascade on both the old key and the
      // new one. Moving a row is a delete plus a create, not an edit.
      const value = field === 'date' ? '2026-09-08' : 2;
      const errors = await check({ [field]: value });
      expect(errors).not.toEqual([]);
    },
  );

  it('refuses isAutoGenerated, which the service always overrode anyway', async () => {
    expect(await check({ isAutoGenerated: true })).not.toEqual([]);
  });

  it('refuses a quantity beyond the sane ceiling', async () => {
    expect(await check({ quantity: MAX_UNITS + 1 })).not.toEqual([]);
  });

  it('refuses a negative quantity', async () => {
    expect(await check({ quantity: -1 })).not.toEqual([]);
  });
});
