import {
  IsInt,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
} from 'class-validator';
import {
  MAX_NOTES_LENGTH,
  MAX_UNITS,
} from '../../common/constants/inventory.constants';

/**
 * A row's identity — (branch, product, date) — is deliberately absent.
 *
 * Accepting those through a PATCH let a row be re-keyed onto a different day or
 * branch, carrying its adjustments with it and leaving the leftover cascade
 * broken on both the old key and the new one. Moving a row is a delete plus a
 * create, not an edit. Under the global pipe's `forbidNonWhitelisted`, sending
 * one of them is now a 400 rather than a silent re-key.
 */
export class UpdateInventoryDto {
  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(MAX_UNITS)
  quantity?: number;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(MAX_UNITS)
  delivery?: number;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(MAX_UNITS)
  leftover?: number;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(MAX_UNITS)
  reject?: number;

  @IsOptional()
  @IsString()
  @MaxLength(MAX_NOTES_LENGTH)
  notes?: string;

  // No isAutoGenerated: update() always forces it to false, because a row a
  // user has edited is by definition no longer a placeholder. Accepting the
  // field and silently discarding it only invited callers to believe otherwise.
}
