import { Prisma } from '@prisma/client';

/**
 * Change history for stock figures, payroll and branch cash records (the AuditEvent table).
 *
 * Every writer records what it changed, inside its own transaction, so the
 * history can never disagree with the data: "who changed this count, and from
 * what" has an answer for every stored value. Carry-forward rewrites are
 * recorded too (action `carry-forward`), so a changed opening can be traced to
 * the correction that caused it.
 */

export type AuditEntity =
  | 'Inventory'
  | 'MaterialInventory'
  | 'Production'
  | 'InventoryAdjustment'
  | 'Employee'
  | 'EmployeeRate'
  | 'RecurringDeduction'
  | 'Absence'
  | 'PayrollAdjustment'
  | 'RecurringDeductionSkip'
  | 'PayrollRun'
  | 'ExpenseCategory'
  | 'BranchExpense'
  | 'BranchVale'
  | 'BranchCashDay';

export type AuditAction =
  | 'create'
  | 'update'
  | 'delete'
  | 'restore'
  | 'carry-forward';

/** The fields whose changes are worth recording, per entity. */
export const AUDITED_FIELDS: Record<AuditEntity, readonly string[]> = {
  Inventory: ['quantity', 'delivery', 'leftover', 'reject', 'notes', 'isAutoGenerated'],
  MaterialInventory: ['quantity', 'delivery', 'used', 'notes', 'supplierId', 'batchNumber'],
  Production: ['yield', 'notes', 'branchId', 'productId', 'date'],
  InventoryAdjustment: ['type', 'value', 'notes'],
  Employee: ['firstName', 'lastName', 'jobRoleId', 'branchId', 'restDays', 'hiredOn', 'separatedOn', 'userId', 'phone', 'address'],
  EmployeeRate: ['dailyRate', 'effectiveOn', 'deletedAt'],
  RecurringDeduction: ['name', 'employeeShare', 'employerShare', 'isActive'],
  Absence: ['employeeId', 'date', 'note', 'deletedAt'],
  PayrollAdjustment: ['employeeId', 'periodStart', 'kind', 'category', 'description', 'amount', 'deletedAt'],
  RecurringDeductionSkip: ['recurringDeductionId', 'periodStart', 'deletedAt'],
  PayrollRun: ['status', 'voidReason'],
  ExpenseCategory: ['name', 'sortOrder', 'isActive', 'requiresNote'],
  BranchExpense: ['branchId', 'date', 'categoryId', 'amount', 'note', 'deletedAt'],
  BranchVale: ['branchId', 'date', 'employeeId', 'amount', 'note', 'deletedAt'],
  BranchCashDay: ['actualCash', 'note', 'status', 'salesAtVerify', 'expensesAtVerify', 'valeAtVerify'],
};

type Row = Record<string, unknown> | null | undefined;

export interface AuditEntry {
  entity: AuditEntity;
  entityId: number;
  before: Row;
  after: Row;
  /** Inferred from before/after when omitted. */
  action?: AuditAction;
}

const plain = (v: unknown): unknown => {
  if (v === undefined) return null;
  if (v instanceof Date || Object.prototype.toString.call(v) === '[object Date]') {
    return (v as Date).toISOString();
  }
  if (v && typeof v === 'object' && 'toNumber' in v) {
    return (v as { toNumber(): number }).toNumber(); // Prisma.Decimal
  }
  return v;
};

/** `{ field: [before, after] }` for each audited field that differs. */
export function diffFields(
  entity: AuditEntity,
  before: Row,
  after: Row,
): Record<string, [unknown, unknown]> {
  const changes: Record<string, [unknown, unknown]> = {};
  for (const field of AUDITED_FIELDS[entity]) {
    const b = plain(before?.[field]);
    const a = plain(after?.[field]);
    if (JSON.stringify(b) !== JSON.stringify(a)) changes[field] = [b, a];
  }
  return changes;
}

/**
 * Write the entries that changed something. Entries with no audited
 * difference (an edit that re-typed the same count) are skipped.
 */
export async function recordChanges(
  tx: Pick<Prisma.TransactionClient, 'auditEvent'>,
  entries: AuditEntry[],
  userId?: number | null,
): Promise<void> {
  const data: Prisma.AuditEventCreateManyInput[] = [];
  for (const e of entries) {
    const action =
      e.action ??
      (e.before == null ? 'create' : e.after == null ? 'delete' : 'update');
    const changes = diffFields(e.entity, e.before, e.after);
    if (Object.keys(changes).length === 0 && action === 'update') continue;
    data.push({
      entity: e.entity,
      entityId: e.entityId,
      action,
      changes: changes as Prisma.InputJsonValue,
      userId: userId ?? null,
    });
  }
  if (data.length > 0) await tx.auditEvent.createMany({ data });
}
