import {
  reconcileInventoryChains,
  reconcileMaterialChains,
} from './stock-chain';
import { FakeStockDb, day } from '../testing/fake-stock-db';
import { MaterialInventoryService } from '../../material-inventory/material-inventory.service';
import { MaterialAdjustmentsService } from '../../material-adjustments/material-adjustments.service';

describe('reconcileMaterialChains', () => {
  let db: FakeStockDb;
  beforeEach(() => (db = new FakeStockDb()));

  const card = (date: string, c: Record<string, unknown>) =>
    db.seed('materialInventory', { materialId: 3, date: day(date), ...c });
  const openings = () => db.live('materialInventory').map((c) => c.quantity);

  // The shape the diagnostics found on the test database: Sep 2 was edited
  // after Sep 3's card had been created, and Sep 3 kept the stale opening.
  it('re-opens later cards on an edited card’s close', async () => {
    card('2026-09-02', { quantity: 60, delivery: 20, used: 22.5 }); // closes 57.5
    card('2026-09-03', { quantity: 60.5, delivery: 0, used: 10 }); // stale
    card('2026-09-04', { quantity: 50.5, delivery: 0, used: 5 });

    const written = await reconcileMaterialChains(db as never, [
      { materialId: 3, fromDate: day('2026-09-02') },
    ]);

    expect(openings()).toEqual([60, 57.5, 47.5]);
    expect(written).toBe(2);
  });

  it('folds adjustments into the close', async () => {
    const sep2 = card('2026-09-02', { quantity: 50, delivery: 0, used: 0 });
    db.seed('materialAdjustment', { materialInventoryId: sep2.id, type: 'ANOMALY', value: 20 });
    card('2026-09-03', { quantity: 50 });

    await reconcileMaterialChains(db as never, [{ materialId: 3, fromDate: day('2026-09-02') }]);

    expect(openings()).toEqual([50, 30]);
  });

  it('never opens below zero (the close is clamped)', async () => {
    card('2026-09-02', { quantity: 5, used: 8 });
    card('2026-09-03', { quantity: 5 });

    await reconcileMaterialChains(db as never, [{ materialId: 3, fromDate: day('2026-09-02') }]);

    expect(openings()).toEqual([5, 0]);
  });

  it('stops at the first card that already agrees, unless asked to walk it all', async () => {
    card('2026-09-02', { quantity: 10 });
    card('2026-09-03', { quantity: 10 }); // agrees
    card('2026-09-04', { quantity: 99 }); // broken further on

    await reconcileMaterialChains(db as never, [{ materialId: 3, fromDate: day('2026-09-02') }]);
    expect(openings()).toEqual([10, 10, 99]);

    await reconcileMaterialChains(
      db as never,
      [{ materialId: 3, fromDate: day('2026-09-02') }],
      { full: true },
    );
    expect(openings()).toEqual([10, 10, 10]);
  });

  it('skips deleted cards', async () => {
    card('2026-09-02', { quantity: 10, delivery: 5 });
    card('2026-09-03', { quantity: 15, delivery: 100, deletedAt: new Date() });
    card('2026-09-04', { quantity: 0 });

    await reconcileMaterialChains(db as never, [{ materialId: 3, fromDate: day('2026-09-02') }]);

    expect(openings()).toEqual([10, 15]);
  });
});

describe('reconcileInventoryChains', () => {
  let db: FakeStockDb;
  beforeEach(() => (db = new FakeStockDb()));

  it('reconciles several products in one call, each from its own day', async () => {
    const r = (productId: number, date: string, c: Record<string, unknown>) =>
      db.seed('inventory', { branchId: 1, productId, date: day(date), ...c });
    r(1, '2026-09-14', { quantity: 0, leftover: 5 });
    r(1, '2026-09-15', { quantity: 9, leftover: 3 });
    r(2, '2026-09-14', { quantity: 0, leftover: 7 });
    r(2, '2026-09-15', { quantity: 9, leftover: 3 });
    r(2, '2026-09-16', { quantity: 9, leftover: 1 });

    await reconcileInventoryChains(db as never, [
      { branchId: 1, productId: 1, fromDate: day('2026-09-15') },
      { branchId: 1, productId: 2, fromDate: day('2026-09-16') },
    ]);

    const opening = (p: number) =>
      db.live('inventory', { productId: p }).map((x) => x.quantity);
    expect(opening(1)).toEqual([0, 5]);
    // Product 2 starts on the 16th: the 15th is left as it was.
    expect(opening(2)).toEqual([0, 9, 3]);
  });

  it('closes a placeholder net of its rejects', async () => {
    db.seed('inventory', { branchId: 1, productId: 1, date: day('2026-09-14'), leftover: 10 });
    db.seed('inventory', {
      branchId: 1, productId: 1, date: day('2026-09-15'),
      quantity: 0, delivery: 6, reject: 2, isAutoGenerated: true,
    });

    await reconcileInventoryChains(db as never, [
      { branchId: 1, productId: 1, fromDate: day('2026-09-15') },
    ]);

    expect(db.live('inventory')[1]).toEqual(
      expect.objectContaining({ quantity: 10, leftover: 14 }),
    );
  });
});

describe('material writers carry forward', () => {
  let db: FakeStockDb;
  beforeEach(() => {
    db = new FakeStockDb();
    db.seed('materialInventory', { materialId: 3, date: day('2026-09-02'), quantity: 40 });
    db.seed('materialInventory', { materialId: 3, date: day('2026-09-03'), quantity: 40 });
  });
  const openings = () => db.live('materialInventory').map((c) => c.quantity);

  it('a delivery added to a past card reaches the next day', async () => {
    const service = new MaterialInventoryService(db as never, {} as never);
    const [sep2] = db.live('materialInventory');

    await service.update(sep2.id, { delivery: 25 });

    expect(openings()).toEqual([40, 65]);
  });

  it('spoilage recorded on a past card reaches the next day', async () => {
    const service = new MaterialAdjustmentsService(db as never);
    const [sep2] = db.live('materialInventory');

    await service.create({ materialInventoryId: sep2.id, type: 'ANOMALY', value: 15 });

    expect(openings()).toEqual([40, 25]);
  });

  it('deleting a card re-opens the next one on the card before it', async () => {
    db.seed('materialInventory', { materialId: 3, date: day('2026-09-04'), quantity: 0 });
    const service = new MaterialInventoryService(db as never, {} as never);
    const [, sep3] = db.live('materialInventory');

    await service.remove(sep3.id);

    expect(openings()).toEqual([40, 40]);
  });
});
