/**
 * A small in-memory stand-in for the Prisma client, for tests only.
 *
 * Covers the stock tables (Inventory, InventoryAdjustment, MaterialInventory,
 * MaterialAdjustment, Production, AuditEvent) and exactly the query shapes the stock
 * services use: equality / `in` / date-range / null filters, `increment`,
 * compound-unique upserts, nested `adjustments` reads, the DISTINCT ON anchor
 * query in stock-chain.ts, and `$transaction` with rollback on throw.
 *
 * It lets tests assert on what the data *ends up as* — every day's opening and
 * close — rather than on which mocked call received which argument, which is
 * what made the old cascade tests break on every refactor.
 */

type Row = Record<string, any>;

type Tables = {
  inventory: Row[];
  inventoryAdjustment: Row[];
  materialInventory: Row[];
  materialAdjustment: Row[];
  production: Row[];
  auditEvent: Row[];
};

const UNIQUE_KEYS: Record<keyof Tables, Record<string, string[]>> = {
  inventory: { branchId_productId_date: ['branchId', 'productId', 'date'] },
  inventoryAdjustment: {},
  materialInventory: { materialId_date: ['materialId', 'date'] },
  materialAdjustment: {},
  production: { branchId_productId_date: ['branchId', 'productId', 'date'] },
  auditEvent: {},
};

/** Child rows attached by `include`/`select: { adjustments }`. */
const ADJUSTMENTS: Partial<Record<keyof Tables, { table: keyof Tables; fk: string }>> = {
  inventory: { table: 'inventoryAdjustment', fk: 'inventoryId' },
  materialInventory: { table: 'materialAdjustment', fk: 'materialInventoryId' },
};

/** Parent rows attached by `include`/`select: { <name> }` on a child. */
const PARENTS: Partial<Record<keyof Tables, Record<string, { table: keyof Tables; fk: string }>>> = {
  inventoryAdjustment: {
    inventory: { table: 'inventory', fk: 'inventoryId' },
    transferTo: { table: 'inventory', fk: 'transferToInventoryId' },
  },
  materialAdjustment: { materialInventory: { table: 'materialInventory', fk: 'materialInventoryId' } },
};

const DEFAULTS: Record<keyof Tables, Row> = {
  inventory: {
    quantity: 0, delivery: 0, leftover: 0, reject: 0, isAutoGenerated: false,
    deletedAt: null, notes: null, createdById: null, updatedById: null,
  },
  inventoryAdjustment: {
    deletedAt: null, notes: null, linkedAdjustmentId: null, createdById: null, updatedById: null,
  },
  materialInventory: { quantity: 0, delivery: 0, used: 0, deletedAt: null },
  materialAdjustment: { deletedAt: null, notes: null },
  production: {
    yield: 0, isAutoGenerated: false, notes: null, deletedAt: null,
    createdById: null, updatedById: null,
  },
  auditEvent: { userId: null },
};

/**
 * Realm-safe Date check. Jest runs tests in a VM context, and structuredClone
 * (used for rollback) builds Dates from the host realm, so `instanceof Date`
 * is false for every date a rolled-back transaction restored.
 */
const isDate = (v: unknown): v is Date =>
  Object.prototype.toString.call(v) === '[object Date]';

const time = (v: unknown): number => (isDate(v) ? v.getTime() : (v as number));

const same = (a: unknown, b: unknown) =>
  isDate(a) && isDate(b) ? a.getTime() === b.getTime() : a === b;

function matchValue(value: unknown, cond: unknown): boolean {
  if (cond === null) return value === null || value === undefined;
  if (isDate(cond) || typeof cond !== 'object') return same(value, cond);
  const c = cond as Record<string, any>;
  if ('in' in c) return c.in.some((v: unknown) => same(value, v));
  if ('not' in c) return !matchValue(value, c.not);
  if ('notIn' in c) return !c.notIn.some((v: unknown) => same(value, v));
  const n = time(value);
  if ('lt' in c && !(n < time(c.lt))) return false;
  if ('lte' in c && !(n <= time(c.lte))) return false;
  if ('gt' in c && !(n > time(c.gt))) return false;
  if ('gte' in c && !(n >= time(c.gte))) return false;
  return true;
}

function matches(row: Row, where: Row | undefined): boolean {
  if (!where) return true;
  for (const [key, cond] of Object.entries(where)) {
    if (cond === undefined) continue;
    if (key === 'OR') {
      if (!(cond as Row[]).some((w) => matches(row, w))) return false;
      continue;
    }
    if (key === 'AND') {
      if (!(cond as Row[]).every((w) => matches(row, w))) return false;
      continue;
    }
    if (key === 'NOT') {
      if (matches(row, cond as Row)) return false;
      continue;
    }
    if (!matchValue(row[key], cond)) return false;
  }
  return true;
}

/** Relation filters (`where: { inventory: { … } }`) resolved against parents. */
function matchesWithRelations(db: FakeStockDb, table: keyof Tables, row: Row, where: Row | undefined): boolean {
  if (!where) return true;
  const parents = PARENTS[table] ?? {};
  const plain: Row = {};
  for (const [key, cond] of Object.entries(where)) {
    const rel = parents[key];
    if (rel && cond && typeof cond === 'object') {
      const parent = db.tables[rel.table].find((r) => r.id === row[rel.fk]);
      if (!parent || !matches(parent, cond as Row)) return false;
    } else {
      plain[key] = cond;
    }
  }
  return matches(row, plain);
}

function sortRows(rows: Row[], orderBy: unknown): Row[] {
  if (!orderBy) return rows;
  const specs = (Array.isArray(orderBy) ? orderBy : [orderBy]) as Row[];
  return [...rows].sort((a, b) => {
    for (const spec of specs) {
      const [field, dir] = Object.entries(spec)[0] as [string, string];
      const av = time(a[field]);
      const bv = time(b[field]);
      if (av < bv) return dir === 'desc' ? 1 : -1;
      if (av > bv) return dir === 'desc' ? -1 : 1;
    }
    return 0;
  });
}

function applyData(row: Row, data: Row): void {
  for (const [key, value] of Object.entries(data)) {
    if (value === undefined) continue;
    if (value && typeof value === 'object' && !isDate(value)) {
      if ('increment' in value) row[key] = (row[key] ?? 0) + value.increment;
      else if ('decrement' in value) row[key] = (row[key] ?? 0) - value.decrement;
      // relation writes (connect/create) are not modelled
      continue;
    }
    row[key] = value;
  }
}

export class FakeStockDb {
  tables: Tables = {
    inventory: [],
    inventoryAdjustment: [],
    materialInventory: [],
    materialAdjustment: [],
    production: [],
    auditEvent: [],
  };
  private nextId = 1;

  inventory = makeModel(this, 'inventory');
  inventoryAdjustment = makeModel(this, 'inventoryAdjustment');
  materialInventory = makeModel(this, 'materialInventory');
  materialAdjustment = makeModel(this, 'materialAdjustment');
  production = makeModel(this, 'production');
  auditEvent = makeModel(this, 'auditEvent');

  /** Seed a row, filling defaults and an id. Returns the stored row. */
  seed(table: keyof Tables, row: Row): Row {
    const full = { ...DEFAULTS[table], id: this.nextId++, ...row };
    this.tables[table].push(full);
    return full;
  }

  /** Live rows of a table, date-ascending, for assertions. */
  live(table: keyof Tables, where?: Row): Row[] {
    return sortRows(
      this.tables[table].filter((r) => r.deletedAt == null && matches(r, where)),
      { date: 'asc' },
    );
  }

  async $transaction(arg: unknown): Promise<unknown> {
    if (Array.isArray(arg)) return Promise.all(arg);
    const snapshot = structuredClone(this.tables);
    const nextId = this.nextId;
    try {
      return await (arg as (tx: this) => Promise<unknown>)(this);
    } catch (err) {
      this.tables = snapshot;
      this.nextId = nextId;
      throw err;
    }
  }

  /** Advisory locks taken, in order, as `ns:key` — for lock-order tests. */
  locks: string[] = [];

  /** Only the chain locks in stock-chain.ts are supported. */
  async $executeRaw(strings: TemplateStringsArray, ...values: any[]): Promise<number> {
    const sql = strings.join('?');
    if (sql.includes('pg_advisory_xact_lock')) {
      this.locks.push(`${values[0]}:${values[1]}`);
      return 1;
    }
    throw new Error(`FakeStockDb: unsupported raw statement: ${sql}`);
  }

  /** Only the anchor query in stock-chain.ts is supported. */
  async $queryRaw(strings: TemplateStringsArray, ...values: any[]): Promise<Row[]> {
    const sql = strings.join('?');
    if (/DISTINCT ON \("branchId", "productId"\)[\s\S]*FROM "Inventory"/.test(sql)) {
      const [branchIds, productIds, before] = [values[0].values, values[1].values, values[2]];
      const latest = new Map<string, Row>();
      for (const r of sortRows(this.tables.inventory, { date: 'asc' })) {
        if (r.deletedAt != null || !(time(r.date) < time(before))) continue;
        if (!branchIds.includes(r.branchId) || !productIds.includes(r.productId)) continue;
        latest.set(`${r.branchId}:${r.productId}`, r);
      }
      return [...latest.values()].map((r) => ({
        branchId: r.branchId,
        productId: r.productId,
        leftover: r.leftover,
      }));
    }
    throw new Error(`FakeStockDb: unsupported raw query: ${sql}`);
  }
}

function makeModel(db: FakeStockDb, table: keyof Tables) {
  const rows = () => db.tables[table];

  const findByUnique = (where: Row): Row | undefined => {
    if ('id' in where) return rows().find((r) => r.id === where.id);
    for (const [name, fields] of Object.entries(UNIQUE_KEYS[table])) {
      if (name in where) {
        return rows().find((r) => fields.every((f) => same(r[f], where[name][f])));
      }
    }
    return rows().find((r) => matches(r, where));
  };

  const shape = (row: Row | undefined, args: Row = {}): Row | null => {
    if (!row) return null;
    const out: Row = { ...row };
    const wants = { ...(args.include ?? {}), ...(args.select ?? {}) };
    const rel = ADJUSTMENTS[table];
    if (rel && wants.adjustments) {
      const spec = wants.adjustments === true ? {} : wants.adjustments;
      out.adjustments = sortRows(
        db.tables[rel.table].filter(
          (a) => a[rel.fk] === row.id && matches(a, spec.where),
        ),
        spec.orderBy,
      ).map((a) => ({ ...a }));
    }
    for (const [name, rel] of Object.entries(PARENTS[table] ?? {})) {
      if (wants[name]) {
        const parent = db.tables[rel.table].find((r) => r.id === row[rel.fk]);
        const spec = wants[name] === true ? {} : wants[name];
        out[name] = parent ? db[rel.table].shapeRow(parent, spec) : null;
      }
    }
    for (const name of ['branch', 'product', 'material']) {
      if (wants[name]) out[name] = { id: row[`${name}Id`], name: `${name} ${row[`${name}Id`]}` };
    }
    return out;
  };

  return {
    /** Shape a row as a read with these include/select args would. */
    shapeRow: (row: Row, args: Row) => shape(row, args),
    findUnique: async (args: Row) => shape(findByUnique(args.where), args),
    findUniqueOrThrow: async (args: Row) => {
      const row = findByUnique(args.where);
      if (!row) throw new Error(`FakeStockDb: ${table} not found`);
      return shape(row, args);
    },
    findFirst: async (args: Row = {}) =>
      shape(sortRows(rows().filter((r) => matchesWithRelations(db, table, r, args.where)), args.orderBy)[0], args),
    findMany: async (args: Row = {}) =>
      sortRows(rows().filter((r) => matchesWithRelations(db, table, r, args.where)), args.orderBy)
        .slice(args.skip ?? 0, args.take ? (args.skip ?? 0) + args.take : undefined)
        .map((r) => shape(r, args)!),
    count: async (args: Row = {}) => rows().filter((r) => matchesWithRelations(db, table, r, args.where)).length,
    create: async (args: Row) => shape(db.seed(table, args.data), args),
    createMany: async (args: Row) => {
      let count = 0;
      for (const data of args.data as Row[]) {
        const unique = Object.values(UNIQUE_KEYS[table])[0];
        if (unique && args.skipDuplicates && rows().some((r) => unique.every((f) => same(r[f], data[f])))) {
          continue;
        }
        db.seed(table, data);
        count++;
      }
      return { count };
    },
    update: async (args: Row) => {
      const row = findByUnique(args.where);
      if (!row) throw new Error(`FakeStockDb: ${table} not found`);
      applyData(row, args.data);
      return shape(row, args);
    },
    delete: async (args: Row) => {
      const row = findByUnique(args.where);
      if (!row) throw new Error(`FakeStockDb: ${table} not found`);
      db.tables[table] = rows().filter((r) => r !== row);
      return { ...row };
    },
    updateMany: async (args: Row) => {
      const hit = rows().filter((r) => matchesWithRelations(db, table, r, args.where));
      hit.forEach((r) => applyData(r, args.data));
      return { count: hit.length };
    },
    upsert: async (args: Row) => {
      const row = findByUnique(args.where);
      if (row) {
        applyData(row, args.update);
        return shape(row, args);
      }
      const created = db.seed(table, {});
      applyData(created, args.create);
      return shape(created, args);
    },
  };
}

/** UTC midnight for a `YYYY-MM-DD` string. */
export const day = (s: string) => new Date(`${s}T00:00:00.000Z`);
