import type { Inventory, Product } from '@/types';
import { getAdjSum, getRevenue, getSold, getTotalStock } from './useInventoryColumns';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeInventory(overrides: Partial<Inventory> = {}): Inventory {
  return {
    id: 1,
    branchId: 1,
    productId: 1,
    quantity: 100,
    delivery: 0,
    leftover: 20,
    reject: 0,
    date: '2024-01-01',
    notes: null,
    isAutoGenerated: false,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    adjustments: [],
    effectivePrice: undefined,
    ...overrides,
  } as Inventory;
}

function makeProduct(overrides: Partial<Product> = {}): Product {
  return {
    id: 1,
    name: 'Pandesal',
    type: 'BREAD',
    sortOrder: 0,
    price: 10,
    isActive: true,
    date: '2024-01-01',
    createdAt: '2024-01-01T00:00:00.000Z',
    deletedAt: null,
    ...overrides,
  };
}

function makeProductMap(products: Product[] = []): Map<number, Product> {
  return new Map(products.map((p) => [p.id, p]));
}

// ---------------------------------------------------------------------------
// getAdjSum
// ---------------------------------------------------------------------------

describe('getAdjSum', () => {
  it('returns 0 for no adjustments', () => {
    expect(getAdjSum(makeInventory({ adjustments: [] }))).toBe(0);
  });

  it('adds PULL_IN values and subtracts PULL_OUT values', () => {
    const inv = makeInventory({
      adjustments: [
        { type: 'PULL_IN', value: 5 },
        { type: 'PULL_OUT', value: 3 },
      ] as never,
    });
    expect(getAdjSum(inv)).toBe(2);
  });

  it('subtracts ANOMALY values', () => {
    const inv = makeInventory({ adjustments: [{ type: 'ANOMALY', value: 4 }] as never });
    expect(getAdjSum(inv)).toBe(-4);
  });

  it('handles undefined adjustments gracefully', () => {
    const inv = makeInventory({ adjustments: undefined as never });
    expect(getAdjSum(inv)).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// getSold
// ---------------------------------------------------------------------------

describe('getSold', () => {
  it('calculates sold = quantity + delivery + adjSum - leftover', () => {
    const inv = makeInventory({ quantity: 100, delivery: 20, leftover: 10, adjustments: [] });
    expect(getSold(inv, makeProductMap())).toBe(110);
  });

  it('includes PULL_IN adjustments positively in sold count', () => {
    const inv = makeInventory({
      quantity: 50, delivery: 0, leftover: 10,
      adjustments: [{ type: 'PULL_IN', value: 10 }] as never,
    });
    // sold = 50 + 0 + 10 - 10 = 50
    expect(getSold(inv, makeProductMap())).toBe(50);
  });

  it('includes PULL_OUT adjustments negatively in sold count', () => {
    const inv = makeInventory({
      quantity: 50, delivery: 0, leftover: 10,
      adjustments: [{ type: 'PULL_OUT', value: 5 }] as never,
    });
    // sold = 50 + 0 + (-5) - 10 = 35
    expect(getSold(inv, makeProductMap())).toBe(35);
  });

  it('can return a negative sold value when leftover exceeds opening', () => {
    const inv = makeInventory({ quantity: 5, delivery: 0, leftover: 10, adjustments: [] });
    expect(getSold(inv, makeProductMap())).toBe(-5);
  });

  it('returns 0 sold when nothing moved', () => {
    const inv = makeInventory({ quantity: 0, delivery: 0, leftover: 0, adjustments: [] });
    expect(getSold(inv, makeProductMap())).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// getRevenue
// ---------------------------------------------------------------------------

describe('getRevenue', () => {
  it('uses effectivePrice when present', () => {
    const inv = makeInventory({ quantity: 10, delivery: 0, leftover: 0, adjustments: [], effectivePrice: 25 });
    // sold = 10, revenue = 10 * 25 = 250
    expect(getRevenue(inv, makeProductMap())).toBe(250);
  });

  it('falls back to product price when effectivePrice is absent', () => {
    const product = makeProduct({ price: 15 });
    const inv = makeInventory({ quantity: 10, delivery: 0, leftover: 0, adjustments: [], effectivePrice: undefined });
    expect(getRevenue(inv, makeProductMap([product]))).toBe(150);
  });

  it('falls back to 0 when neither effectivePrice nor product are available', () => {
    const inv = makeInventory({ quantity: 10, delivery: 0, leftover: 0, adjustments: [], effectivePrice: undefined });
    expect(getRevenue(inv, makeProductMap())).toBe(0);
  });

  it('returns 0 revenue when sold is 0', () => {
    const inv = makeInventory({ quantity: 0, delivery: 0, leftover: 0, adjustments: [], effectivePrice: 10 });
    expect(getRevenue(inv, makeProductMap())).toBe(0);
  });

  it('returns negative revenue when sold is negative (data anomaly)', () => {
    const inv = makeInventory({ quantity: 5, delivery: 0, leftover: 10, adjustments: [], effectivePrice: 10 });
    // sold = -5, revenue = -50
    expect(getRevenue(inv, makeProductMap())).toBe(-50);
  });
});

// ---------------------------------------------------------------------------
// getTotalStock
// ---------------------------------------------------------------------------

describe('getTotalStock', () => {
  it('returns quantity + delivery when there are no adjustments', () => {
    const inv = makeInventory({ quantity: 100, delivery: 30, adjustments: [] });
    expect(getTotalStock(inv)).toBe(130);
  });

  it('includes PULL_IN adjustments positively', () => {
    const inv = makeInventory({
      quantity: 100, delivery: 30,
      adjustments: [{ type: 'PULL_IN', value: 10 }] as never,
    });
    expect(getTotalStock(inv)).toBe(140);
  });

  it('includes PULL_OUT adjustments negatively', () => {
    const inv = makeInventory({
      quantity: 100, delivery: 30,
      adjustments: [{ type: 'PULL_OUT', value: 20 }] as never,
    });
    expect(getTotalStock(inv)).toBe(110);
  });

  it('returns 0 for an empty day', () => {
    const inv = makeInventory({ quantity: 0, delivery: 0, adjustments: [] });
    expect(getTotalStock(inv)).toBe(0);
  });
});
